### ISSUE TITLE
Binary 2 Teensy Attack (Deploy MSF payloads) error

### ISSUE THREAD

**Issue by mertsarica** [trustedsec/social-engineer-toolkit#10]
Hello,

Because there is no reports folder in the main set folder, generating Binary 2 Teensy Attack (Deploy MSF payloads) attempt failed with the error as shown below. (Tested on Kali VM)

[!] Something went wrong, printing the error: [Errno 2] No such file or directory: 'reports/binary2teensy.pde'

Regards,

**Comment by marticols** [comment]
i think is back
