### ISSUE TITLE
Waiting for payload generation to complete appear on setoolkit and doesn't stop 

### ISSUE THREAD

**Issue by galactghost** [trustedsec/social-engineer-toolkit#1020]
Hello, I'm writing here because I'm having a problem in generating payload with setoolkit.
setoolkit's version is 8.0.3 on my KaliLinux and I got  trouble: the message "Waiting for payload generation to complete"
( that appears after you chose the payload and set the options) doesn't stop to appear and the payload is not generated.

**Comment by Max190qw** [comment]
I have no awser you wrote this on a long time ago so did you solve this problem if yes can you tell me how?

**Comment by galactghost** [comment]
No, I did not.
