### ISSUE TITLE
HTTP:// changing to https//

### ISSUE THREAD

**Issue by riven-sudo** [trustedsec/social-engineer-toolkit#1021]
So, i’m currently stuck here at accessing my apache server, hosted by ngrok. so im accessing my ngrok link in my phone (different network) lets say my ngrok link is
http://abcd-<ngrok link>. 

After i logged in my ngrok url it displays into different ngrok link, http//a1cd-<ngrok link>. 

And my other problem is that the (:) on http:// 
is changing to http//<ngrok link> after i logged in. that’s why i can’t access my web after loggin in.
any fix from this? do php have to with this?

**Comment by riven-sudo** [comment]
> So, i’m currently stuck here at accessing my apache server, hosted by ngrok. so im accessing my ngrok link in my phone (different network) lets say my ngrok link is http://abcd-.
> 
> After i logged in my ngrok url it displays into different ngrok link, http//a1cd-.
> 
> And my other problem is that the (:) on http:// is changing to http// after i logged in. that’s why i can’t access my web after loggin in. any fix from this? do php have to with this?

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the Python 3 web attack, credential harvester, static file, SSL, and legacy payload handling fixes. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
