### ISSUE TITLE
Why showing this message on termax

### ISSUE THREAD

**Issue by anandjaiswal67** [trustedsec/social-engineer-toolkit#1067]
The Social-Engineer Toolkit (SET) - by David Kennedy (ReL1K)

Not running as root.

Exiting the Social-Engineer Toolkit (SET).

Thank you for shopping with the Social-Engineer Toolkit.

Hack the Gibson...and remember...hugs are worth more than handshakes.

Please answer me

**Comment by Dgoat201** [comment]
Check this tool out https://t.me/doomztar
