### ISSUE TITLE
Can't install pyOpenSSL

### ISSUE THREAD

**Issue by Karthi02116K** [trustedsec/social-engineer-toolkit#1071]
When I run  pip install pyopenssl
,it showing this Error 
How to solve

Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (**pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [151 lines of output]**
      running bdist_wheel
      running build
      running build_py
.
.
.
.
.
.If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

      This package requires Rust >=1.63.0.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  _**ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects**_

**Comment by Dgoat201** [comment]
Check this tool out 
https://t.me/doomztar
