### ISSUE TITLE
Standardized Build Script

### ISSUE THREAD

**Issue by 2mac** [trustedsec/social-engineer-toolkit#113]
Is there a particular reason this can't follow Python build script standards by using `setuptools` instead of writing the build script yourself?

That will also make it easier to migrate to Python 3 in the future.

**Comment by trustedsec** [comment]
Setup was built awhile back to make additional components installed, it could convert to setuptools, I'm working on major feature sets, may consider it in the future. Good news is SET is open source and we always take contributions!
