### ISSUE TITLE
 unfixable "Enter the file to use as an attachment"

### ISSUE THREAD

**Issue by forkmind** [trustedsec/social-engineer-toolkit#115]
In order to make a pdf embeded exe i have to specify the path of the pdf which is located on my desktop. But each time I have this error : '[!] ERROR:FILE NOT FOUND. Try Again.' ,
although I typed "/root/.../my_pdf"
Why ?

**Comment by trustedsec** [comment]
This should be fixed under SET version 6.3. Thanks for the report. Will be released tomorrow (FRIDAY)
