### ISSUE TITLE
Install missing gems

### ISSUE THREAD

**Issue by forkmind** [trustedsec/social-engineer-toolkit#117]
When I attempt to create a pyinjector-meterpreter payload the setoolkit give the following errors.

[*] Your attack has been created in the SET home directory folder 'autorun'
[*] Note a backup copy of template.pdf is also in /root/.set/template.pdf if needed.
[-] Copy the contents of the folder to a CD/DVD/USB to autorun
[-] The payload can be found in the SET home directory.
set> Start the listener now? [yes|no]: y
[-] Please wait while the Metasploit listener is loaded...
<strong>"Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems."</strong>

I have tried to type 'bundle install' into msfconsole but whitout sucess.
Then I have tried to re-install the metasploit framework but also without any sucess.

**Comment by L1ghtn1ng** [comment]
Try running gem install rake, there is a switch to specify the version but cannot remember what it is

**Comment by forkmind** [comment]
Aready did and doesn't works. Thanks for the help anyway.
I think the problem is a problem of version.

**Comment by byt3bl33d3r** [comment]
@forkmind if you have a git version of metasploit, cd to the directory and run ```bundle install```

**Comment by L1ghtn1ng** [comment]
Yeah you will probably have the latest version and it does not like it, there is a switch to install a specific version of the gem but you will need to Google it to find out

**Comment by forkmind** [comment]
@byt3bl33d3r 1. It's the preinstalled version in kali linux, not a "git clone https/..."
2. Yes, I know, i made a <strong>--purge</strong> reinstall of the framework but nothing change.
@L1ghtn1ng I google it and try the three first links, but again, there are no significals changes.

**Comment by L1ghtn1ng** [comment]
Think you will have to download the binary from metasploit dot com
On 19 Mar 2015 14:53, forkmind <notifications@github.com> wrote:@byt3bl33d3r 1. It's the preinstalled version in kali linux, not a "git clone https/..."
2. Yes, I know, i made a --purge reinstall of the framework but nothing change.
@L1ghtn1ng I google it and try the three first links, but again, there are no significals changes.

**Comment by byt3bl33d3r** [comment]
and if that doesn't work you probably broke your kali install

**Comment by trustedsec** [comment]
There is an issue with Metasploit at the moment, its requiring ruby2.1 at a minimum however only triggers when directly running from the Metasploit directory path located under either /opt/ or /usr/share/. I've addressed this in the new version of SET 6.3 by calling /usr/bin instead, if msfconsole is located with launcher it will directly call from there instead of pulling from a home directory as a workaround. Not a specific SET issue, but at least with this workaround you won't have to completely blow out MSF and re-install ruby.  Fixed and tested in next release. Should be releasing tomorrow (Friday).

**Comment by offensive-security** [comment]
https://bugs.kali.org/view.php?id=2220

**Comment by trustedsec** [comment]
It's actually a confirmed metasploit bug when launching from the root directory outside of a folder path introduced a few weeks ago. SET is python only never ruby. Regardless I released version 6.3 yesterday which changes the launch point as a workaround for metasploits bug and is already on github



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by trustedsec** [comment]
BTW hugs and miss you! Hope all is well.

I normally tells dooks when a new version is out, but I usually give it a day to see if anyone has any major issues with the release. Want me to contact dooks?

David Kennedy | Founder, Senior Principal Security Consultant
QSA, OSCE, OSCP, CISSP, ISO 27001, GSEC, MCSE
TRUSTEDSEC, LLC
P: (877).550.4728 Ext. 700
C: 440.668.0592
E: DAVID.KENNEDY@TRUSTEDSEC.COM
https://www.trustedsec.com<https://www.trustedsec.com/>

From: muts
Reply-To: trustedsec/social-engineer-toolkit
Date: Saturday, April 11, 2015 at 2:46 AM
To: trustedsec/social-engineer-toolkit
Cc: info
Subject: Re: [social-engineer-toolkit] Install missing gems (#117)


https://bugs.kali.org/view.php?id=2220

**Comment by offensive-security** [comment]
SET 6.3 packaged in Kali linux.

**Comment by wikijm** [comment]
Try `cd /usr/share/metasploit-framework/ ; bundle install`

**Comment by M45KL** [comment]
@wikijm hey man ! you safe my life <3 thanks so much <3 xD
