### ISSUE TITLE
Apache server is on but harvester log is empty

### ISSUE THREAD

**Issue by casperass** [trustedsec/social-engineer-toolkit#119]
I'm trying it on facebook -for only educational purpose of course- I successfully cloned it when I go to my external ip I can see it. But it doesn't save anything to var/www directory. All txt's are empty. I think there is a problem with the apache server.

Here is error logs from /var/log/apache2:

___________________________________________

[Thu Apr 09 18:27:20 2015] [error] [client 192.168.1.34] PHP Warning:  file_put_contents(): Only 0 of 944 bytes written, possibly out of free disk space in /var/www/post.php on line 1, referer: http://facebook.com/
[Thu Apr 09 18:27:21 2015] [error] [client 192.168.1.34] File does not exist: /var/www/favicon.ico, referer: http://192.168.1.38/post.php
[Thu Apr 09 18:28:12 2015] [error] [client 192.168.1.34] File does not exist: /var/www/ajax, referer: http://facebook.com/
[Thu Apr 09 18:28:24 2015] [error] [client 192.168.1.34] File does not exist: /var/www/ajax, referer: http://facebook.com/
[Thu Apr 09 18:28:25 2015] [error] [client 192.168.1.34] File does not exist: /var/www/ajax, referer: http://facebook.com/
[Thu Apr 09 18:28:26 2015] [error] [client 192.168.1.34] File does not exist: /var/www/ajax, referer: http://facebook.com/
[Thu Apr 09 18:28:28 2015] [error] [client 192.168.1.34] File does not exist: /var/www/ajax, referer: http://facebook.com/
[Thu Apr 09 18:28:30 2015] [error] [client 192.168.1.34] PHP Warning:  file_put_contents(): Only 0 of 966 bytes written, possibly out of free disk space in /var/www/post.php on line 1, referer: http://facebook.com/
[Thu Apr 09 18:46:59 2015] [error] [client 192.168.1.38] File does not exist: /var/www/ajax, referer: http://192.168.1.38/
[Thu Apr 09 18:47:05 2015] [error] [client 192.168.1.38] File does not exist: /var/www/ajax, referer: http://192.168.1.38/
[Thu Apr 09 18:47:05 2015] [error] [client 192.168.1.38] PHP Warning:  file_put_contents(): Only 0 of 951 bytes written, possibly out of free disk space in /var/www/post.php on line 1, referer: http://192.168.1.38/
[Thu Apr 09 19:01:32 2015] [error] [client 192.168.1.38] File does not exist: /var/www/ajax, referer: http://192.168.1.38/
[Thu Apr 09 19:01:32 2015] [error] [client 192.168.1.38] File does not exist: /var/www/ajax, referer: http://192.168.1.38/
[Thu Apr 09 19:01:34 2015] [error] [client 192.168.1.38] File does not exist: /var/www/ajax, referer: http://192.168.1.38/
[Thu Apr 09 19:01:36 2015] [error] [client 192.168.1.38] File does not exist: /var/www/ajax, referer: http://192.168.1.38/
[Thu Apr 09 19:01:36 2015] [error] [client 192.168.1.38] PHP Warning:  file_put_contents(): Only 0 of 780 bytes written, possibly out of free disk space in /var/www/post.php on line 1, referer: http://192.168.1.38/
_____________________________________

At first I tried on ettercrap that's why it says the refferer is "http://facebook.com" But after that as you can see I tried it local but the same error. I don't know what the error says. Should there be ajax directory in www?

Here is the screenshoot right after I cloned the website:
![screenshot from 2015-04-09 19 12 41](https://cloud.githubusercontent.com/assets/11530785/7071200/53e7a73e-ded3-11e4-8e66-a2b3bf57c835.png)

And the last question is that should it show the username and the password in terminal? I saw that on this video. I shows the username and the password in the terminal. Here is the screenshoot:

![screenshot from 2015-04-09 19 14 21](https://cloud.githubusercontent.com/assets/11530785/7071244/abc0d30e-ded3-11e4-89c9-5790e2e7c46c.png)

If any information is needed to solve this problem just tell me, I can provide it. Thank you :)

**Comment by casperass** [comment]
And on the error log why does it say that I have a free disk problem? I am using Kali Linux set up on USB. I have 200mb free disk space why can't it write 700bytes on it?

**Comment by trustedsec** [comment]
The method to show the passwords in the terminal is if you turn APACHE_SERVER to OFF under config/set_config. This is turned off by default because the HTTP server sockets in Python are buggy and not fully reliable (not as much as Apache that is). 

Unfortunately this does not appear to be a SET bug, it's working fine:

root@kali:/var/www# cat harvester_2015-04-09\ 22\:01\:20.961855.txt 
Array
(
    [lsd] => AVoLhR4z
    [display] => 
    [enable_profile_selector] => 
    [legacy_return] => 1
    [profile_selector_ids] => 
    [trynum] => 1
    [timezone] => 420
    [lgndim] => eyJ3IjoxNDYyLCJoIjoxMDAyLCJhdyI6MTQ2MiwiYWgiOjk2MiwiYyI6MjR9
    [lgnrnd] => 190120_fAMU
    [lgnjs] => 1428631326
    [email] => jiojoi
    [pass] => jiojoi
    [default_persistent] => 0
    [qsstamp] => W1tbMTMsNDQsNjIsMTIxLDEyMiwxNTcsMTYwLDIwMiwyMjEsMjYxLDI3MCwyOTUsMzI3LDM0MSwzNDUsMzUxLDM1MywzNjAsMzYxLDM5Myw0MjUsNDM3LDQ0OSw0NjEsNDgwLDQ4NSw1MTcsNTI1LDUzMSw1MzMsNTcwLDU4Miw1ODUsNTk2LDYwMyw2MTQsNjIyLDY1Niw2NjUsNjc3LDcwMyw5NDddXSwiQVpsWkUwRHFvWm1LakI4UjJDOThJeV9nMEZ2NFlxaVB2T0g0SXd6VThRQWJHMnZTVG1najMteHo0QUZpM0NCU1Q4QUprT2RTdEl0VzhHWUlpOHEzUmUtSjU2c3h5YWk2X3FFQk5OSXo5NHltNVFjeXg2TU00UGF5MkZwYlFuZm50Q3Z5NTBYQi1VMmY2cU1OdG9jSVNjM1ZqYWZHVjFnWXNzeG12N0FLODhMb01nRVRJMzdSbjZRSUpFRnNkMDAxQlljZ0thU3JMN0tYZWVSLUdaRVFyMExIemc0WjFNUmdJbUlsazFoNmdlNjQ3WTliZEZjTE92cDVKcUNYekp2aTZjdyJd

Looks like you are running in a read-only mode and not read-write?
