### ISSUE TITLE
Problem with site-cloner not matching all form-tags

### ISSUE THREAD

**Issue by swk1986** [trustedsec/social-engineer-toolkit#121]
Hi there, i've problems with cloning the page of an embedded device. it seems like the following form-tag is not matched:  

<form ENCTYPE="application/x-www-form-urlencoded" ACTION="/FormLogin" METHOD="POST" id="Login_Area_Form" Name="LoginForm">

(we removed the enctype for test-purposes and lowered all text -  it worked)

**Comment by trustedsec** [comment]
Do you have the website in question that you can share or post the form fields that SET wasn't catching?

Thanks!

**Comment by trustedsec** [comment]
Haven't had a response, closing this thread.

**Comment by swk1986** [comment]
Hi, it is the web-interface für a S7-300/S7-1200 component. We are using it inside a private network. Can u do anything with a copy of the page?
