### ISSUE TITLE
Credential harvester not redirecting

### ISSUE THREAD

**Issue by thelocotauren** [trustedsec/social-engineer-toolkit#122]
Hi guys, i'm having an issue with the Setoolkit, specifically with the credential harvester. I've used it in the past, and if i'm not mistaken, it ussually logged the users credentials, and then it redirected you to the true website WITH those same credentials in the login fields. However, when i try to use it now (with facebook, on a local network for testing purposes), it just redirects back to the facebook login, without the credentials. Is this an expected behaviour? I have the AUTO_REDIRECT=ON flag on the config file, and it does redirect correctly, just without the credentials the user first used. 

Thanks!

**Comment by trustedsec** [comment]
Greetings thelocotaruen, it does not actually log the victim into the site, just redirects them to the original site. Would require a significant amount of coding and handling to have that be accomplished and not something that I'm looking to add in the near future. Thanks for the report, closing this ticket :-)
