### ISSUE TITLE
Chrome detecting credential harvester

### ISSUE THREAD

**Issue by thelocotauren** [trustedsec/social-engineer-toolkit#123]
Hi guys, i have one more problem with the credential harvester. Im testing it with facebook for the company i work at, and firefox/Iceweasel doesn't detect anything, but chrome detects it after a few minutes. I've read that this is a built in function, its not due to a blacklisted url. Does anybody know how to bypass this phishing alert? The message doesn't come up when it's hosted on a lan ip, but it does when its hosted on a public web hosting provider. I've tried obfuscating the html code and that didin't work out.
 
Thanks!

**Comment by trustedsec** [comment]
I'm running Chrome myself and cred harvester doesn't pick it up. Only thing I can say is check the IP and ensure that its not a known phishing website/IP address..
