### ISSUE TITLE
move config files to sysconfig directory (/etc)

### ISSUE THREAD

**Issue by ZeroChaos-** [trustedsec/social-engineer-toolkit#126]
It would be nice if the config file was in the actual config directory so debsums does fail to validate the checksum.  debsums automatically ignores config files in the proper directory, but it cannot ignore randomly placed files failing checksums.

#debsums set
<trimmed>
/usr/share/set/config/mailing_list.txt                                        OK
/usr/share/set/config/set_config                                            FAILED
/usr/share/set/config/set_config.py                                       FAILED
/usr/share/set/config/slim_set.py                                             OK
<trimmed>

Would it be possible to put the config files in /etc/se-toolkit or something?

**Comment by trustedsec** [comment]
I'll add this as a milestone - shifting to a different directory set isn't a bad idea.. Shouldn't be a big deal to add.

**Comment by ZeroChaos-** [comment]
Why close a ticket tracking a current issue before the task is done?

**Comment by trustedsec** [comment]
Because this isn't an issue it's a request and I've added it to my list to incorporate into future releases.

**Comment by ZeroChaos-** [comment]
debsums saying your files are corrupt sure seems like an issue to me...  but I'm sure that's standard and shouldn't expect checksums to match.

**Comment by trustedsec** [comment]
Note that this has been addressed in version 6.4, the config/ directory has been deleted and structurally moved to /etc/setoolkit/. 6.4 should be released within the next week or so.

**Comment by ZeroChaos-** [comment]
<3 thanks
