### ISSUE TITLE
Problems with the way the kali-bleeding-edge repository is enabled

### ISSUE THREAD

**Issue by rhertzog** [trustedsec/social-engineer-toolkit#130]
Hello,

I notice that SET offers a way to enable the kali-bleeding-edge repository. That's nice but there are a few problems:
1/ it should add "deb http://http.kali.org kali-bleeding-edge main contrib non-free" and it should never point any end-user to repo.kali.org (internal server), http.kali.org will redirect the user to a mirror close to him (it would be nice if you could fix that up automatically on upgrades)
2/ it should not replace /etc/apt/sources.list at all, the good way to enable a supplementary repository is to add a file in /etc/apt/sources.list.d/ ... that way you can just add the kali-bleeding-edge repo and don't need to add the default kali repositories (that the user already has via its /etc/apt/sources.list) and that way you also don't remove other repositories that the user might have already added.
3/ if you want the user to benefit from updates via kali-bleeding-edge you must instruct him to run "apt-get install -t kali-bleeding-edge set" or possibly install a file in /etc/apt/preferences.d/ which increases the pinning of set in the kali-bleeding-edge repository to something like 500 (default pinning of packages).

--
Raphaël, a Kali Linux developer

**Comment by trustedsec** [comment]
Greetings Raphaël,

I appreciate the feedback, when bleeding edge repos first came out, the addition came directly from the Kali instruction sets. From the original blog post on offsec (https://www.kali.org/news/bleeding-edge-kali-repositories/):

echo deb http://repo.kali.org/kali kali-bleeding-edge main >> /etc/apt/sources.list
apt-get update
apt-get upgrade

Looks like those have changed a bit and I've incorporated the changes into the next release of set by adding a new bleeding.list into /etc/apt/sources.list.d.

It no longer makes modifications directly to sources.list.

Much appreciated for the enhancement and recommendations, new release should be out soon! Great work.
