### ISSUE TITLE
Error to import set_config in setoolkit v6.4

### ISSUE THREAD

**Issue by raffaele-forte** [trustedsec/social-engineer-toolkit#131]
[...]

set:webattack> Select a template:2

[*] Cloning the website: http://www.google.com
[*] This could take a little bit...

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.

[!] Something went wrong, printing the error: [Errno 2] No such file or directory: 'config/set_config'

**Comment by trustedsec** [comment]
Thanks! Just pushed an update to fix. Made a major rehaul to how config works - missed this one! Appreciate the heads up. Git pull should address it now.
