### ISSUE TITLE
Something went wrong, printing the error : name 'src' is not defined

### ISSUE THREAD

**Issue by kaliNooby** [trustedsec/social-engineer-toolkit#134]
i noticed you said that this error was fixed in the 6.3 update but my social-engineer-toolkit is on version 6.2. Ive pressed key 4 to update the tool kit but nothing happens. PLEASE HELP!!!

**Comment by trustedsec** [comment]
Type git clone https://github.com/trustedsec/social-engineer-toolkit to get the latest version.

**Comment by kaliNooby** [comment]
It says set config inside new repository? does that meen it worked

**Comment by trustedsec** [comment]
Not sure what that means. You will need to go into your new SET directory you just cloned and run ./setoolkit. You should see version 6.4.

**Comment by kaliNooby** [comment]
i recloned it. Now i go into the tool kit and type ./setoolkit.

**Comment by kaliNooby** [comment]
im really not sure what your explaining. Im fairly new to kali. Could you break it down please

**Comment by trustedsec** [comment]
This isn't the place for basic Linux commands. I would head to Kali Linux forums and doing research to learn. Basic premise is you need to git clone the latest version of SET, then run the latest version of SET.

**Comment by kaliNooby** [comment]
i open terminal and type git clone and it pulls up a variety of things. But i dont understand what you meen by run the lastest version of the set. Im aware of the commands.

**Comment by kaliNooby** [comment]
ohh, at the top it says "you must select a repository to clone"
