### ISSUE TITLE
Please create proper tags for releases

### ISSUE THREAD

**Issue by rhertzog** [trustedsec/social-engineer-toolkit#136]
Hello,

In Kali we have a system to monitor new set release and it's based on the tags appearing in https://github.com/trustedsec/social-engineer-toolkit/tags but it looks like the last release (6.4) is not there... 

Thank you

**Comment by JDogHerman** [comment]
Tags would be nice!

**Comment by trustedsec** [comment]
Updated tags to 6.4.1, will ensure they are that way moving forward. Note that 6.5 is being released soon (today or tomorrow).
