### ISSUE TITLE
Rake issue when attempting to open listener/Kali 1.1.0

### ISSUE THREAD

**Issue by ouchsj** [trustedsec/social-engineer-toolkit#137]
I am getting the rake error. 

I tried the workaround according to https://bugs.kali.org/view.php?id=2220 

However a lot of the libraries cannot be installed and bundle install fails.

[] Your attack has been created in the SET home directory folder 'autorun'
[] Note a backup copy of template.pdf is also in /root/.set/template.pdf if needed.
[-] Copy the contents of the folder to a CD/DVD/USB to autorun
[-] The payload can be found in the SET home directory.
set> Start the listener now? [yes|no]: y
[-] Please wait while the Metasploit listener is loaded...
"Could not find rake-10.4.2 in any of the sources
Run bundle install to install missing gems."

**Comment by trustedsec** [comment]
Please upgrade SET to the latest version, this was addressed a few versions ago.
