### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by MendesMontanaro** [trustedsec/social-engineer-toolkit#139]
Hello , I do not want to be annoying , but unfortunately the tool be a mistake. Today I try to use it , but unfortunately I did not succeed , I took a git clone and no work , errors were:

1 error , the tool already installed on linux kali :
Traceback (most recent call last) :
  File " ./setoolkit " , line 41 , in < module>
    FILEWRITE = file ( "src / logs / set_logfile.log " , "w" )
IOError : [ Errno 13] Permission denied : 'src / logs / set_logfile.log '

2 error after I take a git clone :
Traceback (most recent call last) :
  File " ./setoolkit " , line 24 , in < module>
    os.makedirs ("/ etc / setoolkit /")
  File " /usr/lib/python2.7/os.py " , line 157, in makedirs
    mkdir (name , mode )
OSError : [ Errno 13] Permission denied : '/ etc / setoolkit /'

**Comment by trustedsec** [comment]
You are seeing permission denied which would indicate that you have some permission issues on your operating system. SET requires root to run.

**Comment by MendesMontanaro** [comment]
Thanks! :D
Em 31/07/2015 09:35, "trustedsec" <notifications@github.com> escreveu:
