### ISSUE TITLE
Cannot choose a menu option

### ISSUE THREAD

**Issue by skvvv** [trustedsec/social-engineer-toolkit#144]
The main menu shows up, however if I type out the number for the option and hit enter, nothing happens and the terminal refreshes.
Running arch linux by the way.

**Comment by skvvv** [comment]
I did a setup.py install via the git clone, works now!

**Comment by trustedsec** [comment]
Awesome, glad to hear =)

**Comment by skvvv** [comment]
The bug is still there though, the menu refreshes, no option can actually be choosen, and only the console artwork changes, like I'm running a new setoolkit everytime I type something out.

**Comment by azerupi** [comment]
Having the same problem.. Also on Arch Linux
