### ISSUE TITLE
Check Metasploit path not working well

### ISSUE THREAD

**Issue by samiux** [trustedsec/social-engineer-toolkit#148]
The setcore.py at src/core is not working well on checking the Metasploit path.  The following is the bug fix.

http://pastebin.com/geh9U42U

**Comment by trustedsec** [comment]
Commenting out large portions of it isn't a fix - if you need to change the Metasploit path for something custom you can edit /etc/setoolkit/set.config and change the path there if it's not a non-standard one or a launcher isn't present in /usr/local/bin/msfconsole
