### ISSUE TITLE
Check Metasploit path not working well

### ISSUE THREAD

**Issue by samiux** [trustedsec/social-engineer-toolkit#150]
Hi Developer,

I have reported the same issue before but you said that "comment out a large portion of code is not a fix" as reason to close the bug report.  However, you overlooked my fix besides the comment out lines of code.

I hereby I am going to point it out.

The following is the original setcore.py portion of code -

####################################
#
# grab the metaspoit path
#
def meta_path():

    # DEFINE METASPLOIT PATH
    trigger = 0
    try:
    
                # specific for backbox linux
                if os.path.isfile("/opt/metasploit-framework/msfconsole"):
                    msf_path = "/opt/metasploit-framework/"
                    trigger = 1
.
.
.
.

    except Exception, e:
	print_status("Something went wrong. Printing error: " + str(e))

    # if all else fails then pull config path
    if trigger == 0:
	    msf_path = check_config("METASPLOIT_PATH=")
	    if msf_path.endswith("/"): pass
	    else: msf_path = msf_path + "/"

	    if not os.path.isfile(msf_path): 
		print_error("Unable to find Metasploit. Disabling Metasploit.")
		msf_path = False		

    # this is an option if we don't want to use Metasploit period
    check_metasploit = check_config("METASPLOIT_MODE=").lower()
    if check_metasploit != "on": msf_path = False
    return msf_path

###############

The following is my fix, a portion of code -

@@@@@@@@@@@@@@@@@@@@
#
# grab the metaspoit path
#
def meta_path():

    # DEFINE METASPLOIT PATH
    msf_path = check_config("METASPLOIT_PATH=")
    if msf_path.endswith("/"): pass
    else: msf_path = msf_path + "/"
    trigger = 0
    if not os.path.isdir(msf_path):
    
                # specific for backbox linux
                if os.path.isfile("/opt/metasploit-framework/msfconsole"):
                    msf_path = "/opt/metasploit-framework/"
                    trigger = 1
 .
.
.
.
#    except Exception, e:
#	print_status("Something went wrong. Printing error: " + str(e))

    # if all else fails then pull config path
#    if trigger == 0:
#	    msf_path = check_config("METASPLOIT_PATH=")
#	    if msf_path.endswith("/"): pass
#	    else: msf_path = msf_path + "/"
#
#	    if not os.path.isfile(msf_path): 
#		print_error("Unable to find Metasploit. Disabling Metasploit.")
#		msf_path = False		

    # this is an option if we don't want to use Metasploit period
    check_metasploit = check_config("METASPLOIT_MODE=").lower()
    if check_metasploit != "on": msf_path = False
    return msf_path

@@@@@@@@@@@@@@@@@@

I hope that you will find the different.  Your code has the logic problem on exceptional check.  I know that it is not a perfect code for the fix but it works for me at least.  My problem is that when I install SET on Ubuntu, even I changed the set.config, Metasploit will never detected.

**Comment by trustedsec** [comment]
Thanks for posting this, was able to test on a different system, I've made the changes and pushed a version up that addresses the config path issue.
