### ISSUE TITLE
Invalid syntax (cloner.py, line 340)

### ISSUE THREAD

**Issue by PaoloRotolo** [trustedsec/social-engineer-toolkit#152]
Hi!
It seems that commit 2183393c78bb531af996d1c76b3137f301598556 broke cloner.py.

```
set:webattack> Select a template:1
[!] Something went wrong, printing the error: invalid syntax (cloner.py, line 340)
```

All works fine with precedent commits.

**Comment by trustedsec** [comment]
On it right now, thanks for the report, checking

**Comment by trustedsec** [comment]
Fixed, I committed the wrong version on last update, just re-checked in the most recent version. Thanks for the report. Git pull should fix. Sorry about that..

**Comment by PaoloRotolo** [comment]
It works now. Thank you!

**Comment by firewormwh** [comment]
up i need this help
