### ISSUE TITLE
Can't create listener after creating payload

### ISSUE THREAD

**Issue by seanhof** [trustedsec/social-engineer-toolkit#154]
I'm now able to create the payload (thank you) but when it asks if I want to "create a listener yes|no" it won't take any keyboard input.  The only thing I can do is hit Ctrl-c and exit from the setoolkit.

**Comment by seanhof** [comment]
Hello.  It works now.  I Needed to bring up msfconsole first (To connect to the database?) then exit and run ./setoolkit from the git pull.  Thanks for the quick fix yesterday.

**Comment by seanhof** [comment]
So I guess there is still a bug.  I am able to create the payload but when it asks if I want to "create a listener now" it will sometimes let me type and sometimes not.

**Comment by saintdrug** [comment]
Yes but ofc we can create it separately but yeah doesnt do it auto

**Comment by trustedsec** [comment]
Fixed in latest version, sorry - I switched from subprocess.Popen to pexpect.
