### ISSUE TITLE
error right after generating the payload in infectious media creation

### ISSUE THREAD

**Issue by PracticasFp** [trustedsec/social-engineer-toolkit#155]
Just when it says " Payload has been exported to the default SET directory located under: /root/.set/payload.exe" the program crashes with this message:
"[!] Something went wrong, printing the error:  'module' object has no attribute 'autorun'"

**Comment by trustedsec** [comment]
Ensure you are using the latest version of SET 6.5.5 - this doesn't appear to be an issue in that version.
