### ISSUE TITLE
Can't Reply to "Start Sendmail?" After 6.5.5 Update

### ISSUE THREAD

**Issue by ColdMeth** [trustedsec/social-engineer-toolkit#157]
Hello, I installed 6.5.5 update to fix payload issue. It generates payload now. Problem is, after generating, it asks to start sendmail as usual but I can't write anything on terminal. I restarted and tried again but no luck. So, I can't reply anything to "Start Sendmail?"

**Comment by trustedsec** [comment]
Can you do me a favor and hit git pull in the SET directory, I made a couple minor changes from subprocess to pexpect that should address this issue..

**Comment by trustedsec** [comment]
Closing this ticket.
