### ISSUE TITLE
Error in windows 

### ISSUE THREAD

**Issue by Nati43** [trustedsec/social-engineer-toolkit#160]
I'm kinda new to all this and i'm facing some problems......  
its not working for me! 
i use windows, i cloned it to my desktop and ran it with cmd but none of the modules so i can't use any of the. Like for instance i tried to use the credential harvesting tool but it shows the following error 

[!] something went wrong, printing error: No module named pexpect

am i doing something wrong ???

**Comment by trustedsec** [comment]
Would recommend switching to Linux. 

Module pexpect is a python module. You need to install python-pexpect.
