### ISSUE TITLE
Problems with custom dll hijack

### ISSUE THREAD

**Issue by aaronmoore93** [trustedsec/social-engineer-toolkit#162]
I am getting the following error when creating a custom written DLL hijack attack,

cannot stat ‘src/html/msf.exe’: No such file or directory

I am currently running set 6.5.6, any assistance would be greatly appreciated.

Thanks for the awesome stuff by the way

**Comment by trustedsec** [comment]
Will take a peek tomorrow - should be fixed then :) Thanks for the report!

**Comment by trustedsec** [comment]
Fixed in 6.5.7 thanks for the report.
