### ISSUE TITLE
Empty Harvester File

### ISSUE THREAD

**Issue by Fifty5** [trustedsec/social-engineer-toolkit#164]
I use SET on Kali 2.

i do the following:
1) Social Eng. Attacks
2) Website Attack V
3) Cedentail Havester Attack Method

now, when i choose "2) Site Cloner" 
IP Adress for post... MY IP
URL to Clone: http://www.gmx.net

"All files have been copied to /var/www/html " ...

=> index.html is there.. But no more then this.. no Pictures etc..

That's why i do:

1) Social Eng. Attacks
2) Website Attack V
3) Cedentail Havester Attack Method
3) Import
IP Adress for post... MY IP
/root/GMX (index.html and a subdir "index-files" downloaded via Iceweasel (Webpage complete) )
2. Copy entire folder
URL of the website you imported:http://gmx.net
All files have been copied to /var/www/html

=> Subdir "index-files" whre not copied.. i copy the directory manual to /var/www/html

Now opening my IP on Port 80 shows the site and a harvester_DATE is created.

When i enter any Login Data and login .. the harvester_Date file stays empty..

I already tried this with several sites.. it's always the same problem

The redirect works. This is my post.php
<?php $file = '/harvester_2015-09-22 15:42:58.793143.txt';file_put_contents($file, print_r($_POST, true), FILE_APPEND);?><meta http-equiv="refresh" content="0; url=http://gmx.net" />

**Comment by Fifty5** [comment]
I solved the Problem:
It's in apache2 OOO-default.conf
DocumentRoot /var/www/html needs to be changed to /var/www

Directory html needs to be deleted in /var/www

**Comment by i3visio** [comment]
Confirmed and fixed in the same way: 
```
# modification of the DocumentRoot from /var/www/html to /var/www
sudo nano /etc/apache2/sites-available/000-default.conf
sudo rm /var/www/html -r
sudo /etc/init.d/apache2 restart
sudo setoolkit
```
However, this an issue that is going to remain active in Debian distributions as summarized in http://stackoverflow.com/questions/21660621/why-has-the-apache2-www-dir-been-moved-to-var-www-html and more deeply discussed here https://lists.debian.org/debian-devel/2012/04/msg00301.html.

**Comment by Fifty5** [comment]
Great! 
I'm happy to see that i could help.
What about The copying of 'whole' directory? Index.html & Directory 'index-files' ? Also fixed? 

Best Regards
Steffen 'Fifty5' Nowotny
