### ISSUE TITLE
set.config should provide ability to specify http-user

### ISSUE THREAD

**Issue by gaelanadams** [trustedsec/social-engineer-toolkit#167]
SET manually specifies 'www-user' in setoolkit/src/webattack/harvester/harvester.py on line 447 
however on other distributions (e.g. archlinux) do not use 'www-user', when 'chown' is executed it fails causing errors, this could be alleviated by allowing a end-user to specify which httpd user.

**Comment by trustedsec** [comment]
Pull request fixed this, thanks for the report!
