### ISSUE TITLE
Empty harvester file !!!

### ISSUE THREAD

**Issue by elsatour** [trustedsec/social-engineer-toolkit#169]
before anything I did read previous issues with harvester empty file...I read that I can disable set apache OFF and it worked but here the light goes off and I will lose the terminal data...I edited apache.conf file and the one in sites enabled to /var/www/ .
the harvester file is empty whether it's over the internet or even local. 
I read in a previous issues something about read-only mode, read and write...I didn't quietly get it though I tried to log in as a root also empty :( #100

**Comment by trustedsec** [comment]
Elsatour - can you give me a bit more details - what operating system are you doing this on? I can't reproduce unfortunately, seems to be working on all of my test scenarios. Also - what version of SET are you using?

**Comment by elsatour** [comment]
I am on Linux mint 17.
I am using 6.5.6 version.

**Comment by trustedsec** [comment]
Can you give me a output of the commands you are using?

**Comment by trustedsec** [comment]
Like 1 2, etc.

**Comment by elsatour** [comment]
1 2 3 2

**Comment by SHall14** [comment]
I have seen the simlar behaviour on Kali 2.0, SET is putting the cloned site in /var/www/html and the php script points to local dir. So I just changed the set.config to place harvester* in html dir.

**Comment by BlueH4t** [comment]
1 in the directory / usr / share / setoolkit / src / webattack / harvester
2 open the file harvester.py
3 look for the line where it says "filewrite2 = file (" src / logs / harvester.log "," a ")"
4 change to filewrite2 = file ("/ usr / share / setoolkit / src / logs / harvester.log", "a")
5 save the file
6 back to work
7 please note that this change only applies if you followed the default installation SET, if not, look for the corresonding directory
8 valid in correcting the SET 6.5.6
9 have not conhecimente in the English language, so I used the google translator

**Comment by BlueH4t** [comment]
correction logs directory

**Comment by elsatour** [comment]
still no luck at all however it works in kali sana well...

**Comment by trustedsec** [comment]
Greetings, noticed that this is an issue on Kali due to the directory change to /var/www/html. This is fixed if you edit the /etc/setoolkit/set.config and change the apache directory. I have fixed this in the most recent version without needing to change the config file. Also fixed a few other issues with harvester. Will be pushing this update out momentarily.

**Comment by faisalnisar1** [comment]
i have kali sana and when i open the cloned website using my local ip so the browser opens up the apache page not cloned site although i have set apache to off in set.config file

**Comment by amacupps** [comment]
please i need help. harvester not writing credentials into web despository. it instead gives this
credential harvester is running on port 80
information will be displayed to you as it arrives below

**Comment by kcrypt** [comment]
Hi,  I can't find the harvested credentials in the harvested.txt file located in /var/www/html directory. I'm using Kali Linux 2.0 and it automatically turns on apache2 on. Pls, how do I solve this problem

**Comment by Omegamk** [comment]
same as here , need help

**Comment by corshinelord** [comment]
it works thanks @trustedsec 
for all of u who face the same problem, here for u.
sudo caja
and go to var/www
create ur own file name html

and then go /etc/setoolkit/set.config
edit it, around line 160-165
change the directory from var/www to /var/www/html

 it works for me!!
