### ISSUE TITLE
Unable to find PEM file, check location and config again

### ISSUE THREAD

**Issue by kevinclaassens** [trustedsec/social-engineer-toolkit#170]
I have been trying the credential harvester for a few days and cannot for the life of my get it right. I keep getting error "Unable to find PEM file, check location and config again". What should I do?

I'm using Kali 2.0 in virtualbox

**Comment by trustedsec** [comment]
In /etc/setoolkit/set.config - change the PEM_CLIENT and PEM_SERVER locations to point to your client cert and your server cert.

**Comment by Kaliuser99** [comment]
there are no .pem files anywhere

**Comment by Kaliuser99** [comment]
what should i do now?
