### ISSUE TITLE
Social-engineer-toolkit

### ISSUE THREAD

**Issue by anuragpy** [trustedsec/social-engineer-toolkit#171]
i have seen all the posts regarding "Empty harvester file" and tried every actions to rectify the problem.
Yet I'm getting an "Empty Harvester File'
Im using Kali linux 2.0 running on vmware.
SET-6.5.6
Now,im getting errors:"404 NOT FOUND"

Also i checked with the ports opened through command "nmap IP address"
it says ALL 1000 PORTS are closed
please help

**Comment by trustedsec** [comment]
When using the credential harvester it sounds like you are using a NAT in place and not having your system directly connected to the Internet. You will need to use port forwarding on your router or firewall and point it to the Kali Linux box's internal IP address. This is basic networking stuff unless you place your system directly on the Internet. Additionally, when using SET and the credential harvester you will need to ensure that you put the EXTERNAL IP address - not your internally NATed when prompted for the IP address for Harvester. Harvester needs to know what your external IP address is in order for it to work properly.
