### ISSUE TITLE
Exception happened during processing of request from

### ISSUE THREAD

**Issue by aditya3693** [trustedsec/social-engineer-toolkit#173]
after getting updated to new ver. of SET i am getting error on Credential Harvester Attack Method...
##
The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:
ip add - - [29/Oct/2015 18:55:49] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('ip add', 45206)
----------------------------------------
Exception happened during processing of request from ('ip add', 45207)
----------------------------------------
Exception happened during processing of request from ('ip add', 45208)
----------------------------------------
Exception happened during processing of request from ('ip add', 45209)
----------------------------------------
Exception happened during processing of request from ('ip add', 45211)

plz help me to fix this..
or plz tell me how to downgrade to old version .......

**Comment by trustedsec** [comment]
I can confirm this is an issue, temporarily, you can edit /etc/setoolkit/set.config and turn apache_server to ON and in the apache directory you'll have a results file there with the creds. I'll investigate tonight and look for a fix. Not sure what would cause that as of yet.

**Comment by aditya3693** [comment]
i have tried this  apache_server to ON but nothing works the new update
4.6.8 doesn't works ! how to downgrade to 4.6.6/7 version ??????????????
plz HELP ME

**Comment by trustedsec** [comment]
Fixed in 6.5.9

**Comment by aditya3693** [comment]
6.5.9 is released ???? can i update it ????

**Comment by trustedsec** [comment]
Yep..git pull

**Comment by L1ghtn1ng** [comment]
Or if you are on kali you will want to update your system

**Comment by yashgaikwad002** [comment]
I'm still facing this issue on 8.0.3

**Comment by JMPascarella** [comment]
> 
> 
> I'm still facing this issue on 8.0.3

Same thing with me

**Comment by 3ill** [comment]
same thing with me

**Comment by jhfmiguel** [comment]
Change the option `APACHE_SERVER=OFF` to `APACHE_SERVER=ON` in the file **/etc/setoolkit/set.config**
