### ISSUE TITLE
credential harvester attack method

### ISSUE THREAD

**Issue by honoraops** [trustedsec/social-engineer-toolkit#177]
hello there, 

when i use setoolkit,
version 6.5.9
to clone a website using the "credential harvester attack method"
it creates the html file + the post.php + harvester_date_time_.txt file in  "/var/www/html"
thats good right?
 i use it on my local ip 10.0.0.4, when i go to the url "10.0.0.4" it loads the webpage right, but when i type in the username and the password to test, it redirects to 10.0.0.4/post.php with the error "405 not allowed" please help me out, i used setoolkit a few months ago with the older version from the few months ago and worked fine.

i use it on "kali linux 2.0 sena"

thankyou!!

**Comment by honoraops** [comment]
*btw i had to create the html folder by myself.

**Comment by honoraops** [comment]
The /var/www/html <---- else it didn't store anything, sorry for typing this much i tought maybe this information could help you.

**Comment by trustedsec** [comment]
Doesn't appear to be a Kali or SET issue - by using the default Kali 2.0 install, downloading the latest version of SET and using the credential harvester, you specify the website to clone and clone it. It generates a txt document under /var/www/html (/var/www/html was there by default, didn't need to create it in Kali 2.0). Once you do that, you are able to see the files there, browse the website, enter credentials in and its successful in recording and redirecting:

root@kali:/var/www/html# cat harvester_2015-11-13\ 13\:57\:32.313471.txt 
Array
(
    [GALX] => x-04CA-1p1E
    [continue] => https://accounts.google.com/ManageAccount
    [followup] => https://accounts.google.com/ManageAccount
    [_utf8] => ☃
    [bgresponse] => !p6RCS5P7cLukhVlE5ETpzYh140oPAAMWBjsqA6jkuo8yvmEcN0YNmjg3wBtMhyrHaZG_IMoxBkYjwiB-7VY_eBDzub2m-NyHbciMgzgqGqV7110WQNXmarikzzwKVHzhY7-p1Mw76A5wnfDJ-VqqrKedR03s6jjLGyAIX2sLbfZyFLhZa_qxDKbMmvxIQ9yKq2kqoOl7utl9NMsZHaDy9TjQNmveB4LjaYOw4gYrnbqV4ShusYKjiNc3vyC6sHhdmd91qiiYRuLZ-SL_BLus_VAOzuVFXCLq7YHv0qtZD6PIY_5j49mkldfvBKRphm-sTeWWgrsj_ykzuhAIpxqbcRrJgm6B5x7iPOPJ3-jpjqt3Q7MRuMejTzVN29kbukT24staKjX6eXPDFSPpQuT9ucowKH96hB12AjIu03KwkABmUsFr7Fiqen1bxaPygs3YS23AJB-sHTitEfIeX-4HW0EAKmXY_aRY9m1KrOnkkdqBp0U5G5oQtaDhIzmeXFaOBb_f-fuTFz48IgNyO8s4QvYPj2UZUzu-tFNUVp3Nmqw5tkJq4zSZgODKtDKN3vCQNHG42hBGZuE31pFty6qilZT6yaX2WLnIkBbD8Sbq_cCi06rgTa0qWgSFAgpQzm2DA0Ha8EGsKtqvBcO0JKX3GNVKL3epCENTSUqIvwO0Cc6hUfyId7eqweg6X5L4oQAvzyt6Pf3F6p47OYOeOl9yvmsN6PZDiTQAYPua9ZCOt9D3WI2KFWvXAe4cfyGT3RBKLeNgNKzt8Dp2gxFTwn2AfxZNZU_aCOOiDI4H7jZAV5oaGskkprlR1JGNAl2e2ojD8-QRdbT-KipJYtNXhRb_AKIRFXm_O3D1FidmeCvKBEKg6gBCjAa3XIESLoMnYmukqUXtc8VQaKHnQBjdU6Jz9r88m_akfha778DyvVWKUFHeJztDjxvVK9VcxANXd850HWdZFDmDheagqcQ7m7Ia4f2Y5SB0NhQlpm4dSmNVxTlsvAyV_JcVsykUq2SyvaczZP_6mRDi0lwAZ6rsHa1_M55_GS2LjmeN_cHIFbENNyBIAwnz-UJX9k8sHQmCATEOYBGX56utOasfGb4w2Ll8ftjK0l3TB9LqBbsKLegFFVSgmQlHr25ToH30-a-a2YXq25DK-17Ld2rFsZWMR0hsTUW1elgPjiVtUHTYsITzCNtSbRIvnrROVzxK06NyuQlOIBtATW4omzjEWy8nRotsGqhS8OB0Je8GdzBgC_BPLQOlMs3riqmzImSlMVKyRMxiu9yiyWk
    [pstMsg] => 1
    [dnConn] => 
    [checkConnection] => 
    [checkedDomains] => youtube
    [Email] => testing
    [Passwd] => testing
    [signIn] => Sign in
    [PersistentCookie] => yes
    [rmShown] => 1
)

**Comment by honoraops** [comment]
heey! i finaly found the solution, it has to do with the nginx.conf in /etc/nginx/nginx.conf

i've added this,

error_page 405 =200 @405;
location @405 {
    root /;
    proxy_pass http://localhost:8080;
}

and it worked perfectly!

**Comment by honoraops** [comment]
So for the next people who got this 405 not allowed, error, aka security option,
This could help them out, i've searched for 5 days to fix this, thankyou anywAy!

**Comment by corshinelord** [comment]
where to add it
this is mine: 

user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
