### ISSUE TITLE
 Kali bleeding edge was not detected to be on

### ISSUE THREAD

**Issue by aditya3693** [trustedsec/social-engineer-toolkit#178]
when i open setoolkit...then
[*] Kali bleeding edge was not detected to be on...
[*] Kali install detected." Note that if you are not using bleeding edge repositories, your version of SET will be roughly 4 months behind".
[*] It is recommended to switch to bleeding-edge repos to ensure you are running the latest version of SET and other tools.
Press [enter] to accept that SET is several months out of date and probably contains bugs and issues.

i have tried bleeding edge to ON in config.baseline but still am getting this...

**Comment by trustedsec** [comment]
Did you edit the config under /etc/setoolkit/set.config?

If you turn bleeding_edge to on you'll see this:

root@kali:/usr/share/set# ./setoolkit 
[*] Checking to see if bleeding-edge repos are active.
[*] Bleeding edge already active..Moving on..
[-] New set.config.py file generated on: 2015-11-13 13:55:42.984057
[-] Verifying configuration update...
[*] Update verified, config timestamp is: 2015-11-13 13:55:42.984057
[*] SET is using the new config, no need to restart

Doesn't prompt. Also what version are you using? I'm testing from 6.5.9

**Comment by aditya3693** [comment]
6.5.8 thanks it worked for me...
