### ISSUE TITLE
Issue with cloner and custom provided applet

### ISSUE THREAD

**Issue by amarin-it-uc3m-es** [trustedsec/social-engineer-toolkit#180]
First of all, thanks for this great effort! It is very instructive for me and my students.
I have a configuration to use the basic SET java attack method, providing my own signed jar in the modality web template. I always end up with the default signed jar instead of mine. I find that 
webattack/web_clone/cloner.py doesn't take care about existence of Signed_Update.jar.orig in my setdor.
I backup the original py file and change it to copy it into setdir and setdir/web_clone to avoid further issues with spawn.py. It is running now. diff output is:

[diff_output.txt](https://github.com/trustedsec/social-engineer-toolkit/files/41678/diff_output.txt)

**Comment by trustedsec** [comment]
Thanks a ton and for going through this. Will take a peek at the diff tonight and see if I cant work a fix in. Thanks again!

**Comment by abdowifa** [comment]
salut s'il vous plait j ai installer set ms j'ai pas trouver set config
