### ISSUE TITLE
Broken modules on OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by brianlechthaler** [trustedsec/social-engineer-toolkit#184]
First of all, before I go into broken modules, here's the error I get right after starting up SET.

`[REDACTED]@[REDACTED]:~/git/social-engineer-toolkit`
`% sudo ./setoolkit`                                                                                                                                                          
`Password:`
`[!] Metasploit path not found. These payloads will be disabled.`

`[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.`

`[!] Not running a Debian variant..`

`[-] New set.config.py file generated on: 2015-11-28 10:42:14.697099`

`[-] Verifying configuration update...`

`[*] Update verified, config timestamp is: 2015-11-28 10:42:14.697099`

`[*] SET is using the new config, no need to restart`

### Now, here's the broken modules:

* `1) Social-Engineering Attacks` -> `1) Spear-Phishing Attack Vectors` gives the following error:

`[!] Sorry. This feature is not yet supported in Windows 		or 	Metasploit was not found.`

`Press <return> to continue`

* `1) Social-Engineering Attacks` -> `3) Infectious Media Generator` gives the following error:

`[!] Sorry. This feature is not yet supported in Windows 		or 	Metasploit was not found.`

`Press <return> to continue`

# I'll add more as I run into them

**Comment by trustedsec** [comment]
Need to point the Metasploit path where msfconsole is at otherwise it will disable all of these. The rest work if Metasploit isn't found. Just tested on OSX - all seems well when pointed to Metasploit.

**Comment by tingusbangus** [comment]
I updated the path to the msfconsole on mac os "/opt/metasploit-framework/bin/msfconsole" and I keep getting that SET is not recognizing it, please reply asap

(https://cloud.githubusercontent.com/assets/23368641/20158818/c95fd8d8-a6aa-11e6-854a-9fb174747f14.png)

**Comment by TheEndgam3r** [comment]
@tingusbangus I'm having the same issue, how did you get to that config folder in your screenshot?

**Comment by SuperSuperSenpai** [comment]
Can someone help in pointing Metasploit path where msfconsole is? Please.

**Comment by FU51ON** [comment]
@SuperSuperSenpai Running Mac OS Sierra here
the path is = METASPLOIT_PATH=/opt/metasploit-framework/bin/
make sure to include the last "/"

**Comment by iiewad** [comment]
edit /etc/setoolkit/set.config

```
### This path is error for me, So I changed it! Sorry about my Englist!
#METASPLOIT_PATH=/opt/metasploit/apps/pro/msf3
METASPLOIT_PATH=/opt/metasploit-framework/bin/
```

**Comment by PatRacco84** [comment]
I think for Mojave should be 
`METASPLOIT_PATH=/opt/metasploit/docker/bin/`
This is what I used and it worked.
Please correct me if I'm wrong.
