### ISSUE TITLE
Web site cloner doesn't work

### ISSUE THREAD

**Issue by anuclear** [trustedsec/social-engineer-toolkit#186]
![Uploading wfl.PNG…]()
Dear trustedsec team,
During practicing some labs on SET encountered that site cloned doesn't work. Instead of displaying requested(for cloning) we site browser displays cloned Wifi-lock.com web page

Is there any workaround to fix that?

Regards

**Comment by trustedsec** [comment]
You can manually save the web page and use the "import the website" and correct as needed. The cloner works on almost all websites.
