### ISSUE TITLE
Credential harvester

### ISSUE THREAD

**Issue by D347HGUN** [trustedsec/social-engineer-toolkit#187]
First of all, Thanks for this amazing free toolkit, Now for the issue, I noticed that when you use the Credential harvester module it clones the website, But when i access it and put a password they dont get saved in the harvest.txt file and i also noticed that the file is not in the same folder as the index and post.php files, even when i tried moving the file with the other files it didn't work, Please fix the issue

Am using kali 2.0

**Comment by D347HGUN** [comment]
Ok so i managed to get it working by changing the harverst file location to var/www/html in the config file

**Comment by trustedsec** [comment]
What version of SET are you using? I fixed this awhile back..Current version is 6.5.9

**Comment by D347HGUN** [comment]
Am using the latest version, anyways as i said i fixed it, can't wait for
new updates and new features....
