### ISSUE TITLE
POST data not being saved to harvester log file

### ISSUE THREAD

**Issue by gettingstarted247** [trustedsec/social-engineer-toolkit#189]
Running Kali2, latest updates, bleeding edge repository.  SET is at latest version, 6.5.9.  Using Credential Harvester Attack Method, all three options (Web Templates, Site Cloner, and Custom Import), I can visit the page located in my apache directory (/var/www/html) although the POST data being returned to the server is not being placed into the harvester log file.  I am testing on a LAN, have tried multiple browsers, have tried public sites, as well as creating my own (via using wget -p on a public site, and using the custom import).  Utilizing wireshark from the "victim" machine on my LAN, I can see the POST data being sent to the SET system.  Any clue?  If more info is needed, please let me know.  Thanks.

**Comment by trustedsec** [comment]
No clue unfortunately.. I just booted up a brand new version of Kali 2, upgraded everything git pulled the latest version of SET (6.5.9) - did a clone of https://gmail.com as an example and everything worked as expected and captured everything appropriately.

   [Email] => testing
    [Passwd] => testing
    [signIn] => Sign in
    [PersistentCookie] => yes
    [rmShown] => 1
)
root@kali:/var/www/html# cat harvester_2015-12-31\ 18\:16\:57.330652.txt
