### ISSUE TITLE
harvester attack!

### ISSUE THREAD

**Issue by faisalnisar1** [trustedsec/social-engineer-toolkit#190]
i have kali sana and when i open the cloned website using my local ip so the browser opens up the apache page not cloned site although i have set apache to off in set.config file,What to do?

**Comment by trustedsec** [comment]
This was resolved a number of months ago, please ensure you are using the latest version of SET. 6.5.9 is the latest and works out of the box with Kai Sana.

   [Email] => testing
    [Passwd] => testing
    [signIn] => Sign in
    [PersistentCookie] => yes
    [rmShown] => 1
)
root@kali:/var/www/html# cat harvester_2015-12-31\ 18\:16\:57.330652.txt
