### ISSUE TITLE
SET should call python2 directly

### ISSUE THREAD

**Issue by keeperofdakeys** [trustedsec/social-engineer-toolkit#195]
SET uses "/usr/bin/env python" in its scripts, however this is incompatible with systems that use python3 as their default python, as python3 gets selected instead of python2. This should be changed to "/usr/bin/env python2" so the correct python version is selected.

**Comment by trustedsec** [comment]
Version 7 is slated for release in next few weeks which is a rewrite for both Python 2 and 3 - should resolve this issue. Much appreciated for the report !
