### ISSUE TITLE
Website cloner doesn't seems to be working.

### ISSUE THREAD

**Issue by frostshawn28** [trustedsec/social-engineer-toolkit#198]
Hello.I'm newbie for Social Engineering Toolkit.When I clone a website it gets cloned.But after opening cloned website i.e. my ip adress it shows 
'404 not found The requested URL / was not found on this server.
Apache/2.4.10 (Debian) Server at 192.168.1.8 Port 80'
Please help me.Thanks in advanced.Sorry for bad english.

**Comment by trustedsec** [comment]
Please update to the latest version of SET.
