### ISSUE TITLE
bleeding edge check in set

### ISSUE THREAD

**Issue by L1ghtn1ng** [trustedsec/social-engineer-toolkit#202]
Creating this issue to create discussion about the check for bleeding edge repo. As Kali has gone officially now to rolling release, set is always the latest version provided that you always create a git tag when releasing a new version. So I think we should remove this check as it is now redundant.

I can create a PR if you agree it can be removed

**Comment by trustedsec** [comment]
Sounds good to me and agree... If you have time for sure.. Otherwise will hit it up this week

**Comment by L1ghtn1ng** [comment]
@trustedsec will do also I would suggest a point release for the typo that got fixed the other day as to get it pulled in to kali quickly to stop reports coming in.

**Comment by trustedsec** [comment]
Yeah I'll push an incremental release after I work the Kali stuff

**Comment by trustedsec** [comment]
Closing this out - thanks for the PR!
