### ISSUE TITLE
sendmail didn't work!

### ISSUE THREAD

**Issue by jj4st13** [trustedsec/social-engineer-toolkit#204]
after upgrade set 7.x
E-mail feature does not work in SET.
when sending mail from Mass Mailer Attack and Spear-Phishing attack module, the contents of messages written to the error press ctrl + z.

**Comment by trustedsec** [comment]
I'm unable to reproduce this - can you place an output of the log here?

**Comment by jj4st13** [comment]
i try Mass Mailer Attack
but didn't work....

Select from the menu:

   1) Spear-Phishing Attack Vectors
   2) Website Attack Vectors
   3) Infectious Media Generator
   4) Create a Payload and Listener
   5) Mass Mailer Attack
   6) Arduino-Based Attack Vector
   7) Wireless Access Point Attack Vector
   8) QRCode Generator Attack Vector
   9) Powershell Attack Vectors
  10) Third Party Modules

  99) Return back to the main menu.

set> 5
[-] Sendmail is a Linux based SMTP Server, this can be used to spoof email addresses.
[-] Sendmail can take up to three minutes to start
[*] Sendmail is set to ON
set:phishing> Start Sendmail? [yes|no]:yes
[-] Sendmail can take up to 3-5 minutes to start
[ ok ] Starting sendmail (via systemctl): sendmail.service.

   Social Engineer Toolkit Mass E-Mailer

   There are two options on the mass e-mailer, the first would
   be to send an email to one individual person. The second option
   will allow you to import a list and send it to as many people as
   you want within that list.

   What do you want to do:

    1.  E-Mail Attack Single Email Address
    2.  E-Mail Attack Mass Mailer

    99. Return to main menu.
   
set:mailer>1
set:phishing> Send email to:jj4st13@naver.com

  1. Use a gmail Account for your email attack.
  2. Use your own server or open relay

set:phishing>2
set:phishing> From address (ex: moo@example.com):afasdf@dsafasdf.com
set:phishing> The FROM NAME the user will see:asdf
set:phishing> Flag this message/s as high priority? [yes|no]:y
set:phishing> Email subject:test
set:phishing> Send the message as html or plain? 'h' or 'p' [p]:p
[!] IMPORTANT: When finished, type END (all capital) then hit {return} on a new line.
set:phishing> Enter the body of the message, type END (capitals) when finished:
Next line of the body: test
Next line of the body: test
Next line of the body: ^C[!] **Something went wrong.. Try again**

**Comment by xaitax** [comment]
Same issue here with last git version.
**[!] Something went wrong.. Try again** and SET crashes.

**Comment by laykatz** [comment]
Encountered the same issue, with Cloning

**Comment by trustedsec** [comment]
@laykatz - can you be more specific on cloning? I'm unable to reproduce that on the cloning functionality.

**Comment by trustedsec** [comment]
I've pushed an update now that addresses this, it was due to StringIO being used differently in python2 vs python3 - I've added a handle to check that in if needed. Should be resolved now, thanks for the report!

**Comment by Andrewluck248** [comment]
This issue has returned

**Comment by warlockinit** [comment]
big time mine was saying unable to connect to mail server try again (internet connected?)

**Comment by fadzb** [comment]
Same issue, tried different mail accounts (yahoo and gmail) with and without sendmail to spoof address. Any fix available?

**Comment by Affus** [comment]
i try spear phishing attack. i select 1 and when i reach at does your server support TLS and i chose yes then it tell me unable to connect to server try again ( internet issues )
