### ISSUE TITLE
Failed to find '/etc/setoolkit/set.config' on first installation

### ISSUE THREAD

**Issue by sbrun** [trustedsec/social-engineer-toolkit#207]
I packaged version 7.0.3.3 for kali. When launching setoolkit after first installation, I have the error message:
```
Traceback (most recent call last):
  File "./setoolkit", line 4, in <module>
    from src.core.menu import text
  File "/usr/share/set/src/core/menu/text.py", line 16, in <module>
    msf_path = meta_path()
  File "/usr/share/set/src/core/setcore.py", line 378, in meta_path
    check_metasploit = check_config("METASPLOIT_MODE=").lower()
  File "/usr/share/set/src/core/setcore.py", line 1264, in check_config
    fileopen = open("/etc/setoolkit/set.config", "r")
IOError: [Errno 2] No such file or directory: '/etc/setoolkit/set.config'
```

Of course if older version of set is already installed and if I update the package, there is no problem.

For kali package,  I moved the 3 following lines around line 40 (where they were before commit  f619a78c77722c0194029b5e0e80706acd7c6d07) in file setoolkit:
```
from src.core.setcore import *
from src.core.menu import text
from src.core.update_config import update_config
```

**Comment by trustedsec** [comment]
Thanks for submitting this! I've gone through and pushed an update and updated the retrospective tags. Should be in rolling soon.

**Comment by L1ghtn1ng** [comment]
There is a typo in the changes file

**Comment by trustedsec** [comment]
Not sure what that means or where the typo is :-)

**Comment by L1ghtn1ng** [comment]
https://github.com/trustedsec/social-engineer-toolkit/blob/master/readme/CHANGES the notes for version 7.0.3 its meant to say kali correct?

**Comment by trustedsec** [comment]
Naw - tail... def tail() function in core.

**Comment by L1ghtn1ng** [comment]
Ah okay thanks for clarifying
