### ISSUE TITLE
Repo errors

### ISSUE THREAD

**Issue by ci9her** [trustedsec/social-engineer-toolkit#213]
I found these two problems.
1) Adding kali bleeding edge repo still cannot update setoolkit.
2)Adding kali rolling repo(the latest one), it says 404 not  found.

**Comment by trustedsec** [comment]
I would open this up on the Kali Linux forums - we don't troubleshoot Kali stuff here such as rolling updates. Rolling is the recommended approach to this. 

Here's a tutorial on how to add them:

https://www.kali.org/news/kali-linux-rolling-edition-2016-1/
