### ISSUE TITLE
Credential Harvester

### ISSUE THREAD

**Issue by andranik24** [trustedsec/social-engineer-toolkit#215]
The Credential Harvester -> Site Cloner is having some issues. I'm on the latest version of Kali Linux and fully updated SET. The site is cloned and works, but the post output does not show up in the output file located in /var/www/html.

**Comment by trustedsec** [comment]
What version is the "latest" for you ? I fixed a similar issue several releases ago...

**Comment by andranik24** [comment]
7.0.3 on Kali Rolling 2016.1

Andranik Sahakyan

**Comment by JBel38** [comment]
Idk if this helps, but i found it works with the default install of apache on Kali, but when i attempted to host it in another apache server elsewhere it didn't work.

**Comment by andranik24** [comment]
I am using the default install of Apache, thank you.

**Comment by andranik24** [comment]
<img width="1280" alt="screen shot 2016-03-23 at 5 16 51 pm" src="https://cloud.githubusercontent.com/assets/8908029/14004979/a10e0e80-f11b-11e5-9047-2569d8247208.png">

This is what the screen looks like after setting up the credential harvester. This is my first time having this issue, this has always worked for me, so I don't know why the post results aren't being added into the log file.

**Comment by trustedsec** [comment]
Looking at the site you were trying to clone (instagram) - they don't publish the post parameters within the site itself - so SET can't rewrite the post parameters. You'll need to use a different website or use the import feature and go to instagram, save the page and rewrite the login fields to be standard post parameters.

**Comment by andranik24** [comment]
I see, its mainly gmail’s login page. They changed the layout so I see why it wasn’t posting. Thank you for the help.

**Comment by anonmanx** [comment]
@trustedsec but can you please help me how to rewrite the login field as standard post parameters? 
I saved the instagram login page as a html file and now where do I need to change? Can you please help me?
