### ISSUE TITLE
Site cloner issue

### ISSUE THREAD

**Issue by Bry-fi** [trustedsec/social-engineer-toolkit#222]
Have been having some issues with the web attack vectors in version <=7.0.3
The cloning function does not seem to work as the program does not download the html file to the /var/www directory. It seems that some websites cannot be cloned when most could in past versions.
Also some features like the such as the metasploit browser does not even create a file.

**Comment by trustedsec** [comment]
Closing this issue as it provides no details to how to reproduce the issue and provides vague details.
