### ISSUE TITLE
Issue with 7.0.6 and Kali Linux

### ISSUE THREAD

**Issue by Jeremy-Faircloth** [trustedsec/social-engineer-toolkit#224]
New install of Kali Linux, apt-get update, apt-get upgrade to upgrade all packages. Execute setoolkit, Option 1, Option 1, Option 1, Option 1, 192.168.1.1, Option 1, 443, Option 1. Error: "[1] Something went wrong, printing the error: [Errno 2] No such file or directory: '/root/.setsrc/webattack/dll_hijacking/repository'

If I clone the repository and copy the src directory to /root/.setsrc/, the issue appears to be resolved.

**Comment by trustedsec** [comment]
Thanks for the report! Can confirm this is an issue and fixed in 7.1 which should be hitting in the next few days. Thanks for the report and appreciate it.
