### ISSUE TITLE
Credential Harvester attack gives me empty files!

### ISSUE THREAD

**Issue by alph22** [trustedsec/social-engineer-toolkit#230]
hello everybody! I've tried to practice with credential harvester attack, and when I tried to clone the site and get the data, I just open the harvester** text files on /var/www/html/ **and there is just a** empty harvester file**, is there a problem with my **post.php**?    
(:

**Comment by trustedsec** [comment]
Upgrade to the latest version of SET.

**Comment by alph22** [comment]
I've the last version of set, Im usinh Kbuntu 16 xenial, and I use php, apache2 etc
