### ISSUE TITLE
External IP Problem. 

### ISSUE THREAD

**Issue by DanielstarLie** [trustedsec/social-engineer-toolkit#234]
When I try to clone a website with SET...When I use my inet addr (eth0) to do it, it opens up a well cloned log in site when I search my inet ip in my adress bar on iceweasel. But won't open anything when using an external broswer not in virtualbox. It doesn't open up anything on my computer's google chrome broswer..meaning it only opens the cloned login within my kali linux which is totally useless cos I will need to have everyone oustide the network use my link..And when I use my external ip(which I learnt is available for all users oustide to connect) it doesnt even connect or open up the cloned site in my kali browser(iceweasel), much more of my main PC broswer.... Pls help.

**Comment by L1ghtn1ng** [comment]
You need need to set up bridged networking on virtualbox for that VM

**Comment by DanielstarLie** [comment]
And pls how do I do that?

**Comment by L1ghtn1ng** [comment]
https://www.virtualbox.org/manual/ch06.html
Also you will need to setup port forwarding on your router as well

**Comment by DanielstarLie** [comment]
I don't use a router....I've tried that before but no success...And when I try to search for my router ip using cmd...in gateway address I see 0.0.0.0 meaning=no router

**Comment by nmapgithub** [comment]
after setting up bridge . still the traffic from internet cant access the virtual host. after post forwarding on tcp/udp/http and switching off firewall still traffic cant access phished pages uploaded on apace in set tool kit #externaltrafficproblem..
