### ISSUE TITLE
Integration with Metasploit Community on Ubuntu

### ISSUE THREAD

**Issue by jdalllasjordan** [trustedsec/social-engineer-toolkit#235]
I've tried updating the METASPLOIT_PATH with every path to msfconsole I can find but SET never recognizes it as being installed.  Is there a trick to getting SET to recognize the Metasploit community version?  This is on Ubuntu 16.04.  I installed metasploit from the installer from Rapid7 and SET from the zip at github.  Thanks!

**Comment by trustedsec** [comment]
What version of SET are you using? 

SET looks specifically for msfconsole and the config file is under /etc/setoolkit/set.config

Default value:

METASPLOIT_PATH=/opt/metasploit/apps/pro/msf3

If I change the path:

METASPLOIT_PATH=/root/test/   <-- msfconsole is in that directory

It picks it up and uses that as the path perfectly. 

Are you putting _PATH=path_to_msf/msfconsole ? You just need the directory path.

**Comment by sshamuel** [comment]
I have the same problem. I  installed the metasploit from binary version and SET from git.
I used the "/opt/metasploit" argument in set.config file and updated the configuration in setoolkit menu option 5.
```

## CONFIG_VERSION=7.3.9                                                                                                             ##
##                                                                                                                              ##
##################################################################################################
##################################################################################################
#
### Define the path to Metasploit. For example: /opt/metasploit/apps/pro/msf3
METASPLOIT_PATH=/opt/metasploit

```


```
setoolkit 
[!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.

```

Is there any workaround to solve this problem? Thanks!

**Comment by m0be1** [comment]
The problem I see above is your not pointing to the (abosolute path) /msf location. I have installed the same on my system and I am unable to locate the dir /msf which is what SET is looking for. I suspect its hidden in another Dir somewhere but have been unable to find it.  
fix: METASPLOIT_PATH=/opt/metasploit/dir-to-/msf  
if you find the dir its located in point to that absolute path.

**Comment by misiyu** [comment]
cd /opt/metasploit
sudo find -name msfconsole

then you will get several paths. try to use one of them to replace the default path in set.config.
there must be one path can solve this problem.

**Comment by 0x0V** [comment]
For Ubuntu 16.04 installation of Metasploit, in /etc/setoolkit/set.config:

METASPLOIT_PATH=/opt/metasploit/app

**Comment by Emmaka9** [comment]
bro......I'm having this problem either, [!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.

as u said I copied and pasted this line in terminal (METASPLOIT_PATH=/opt/metasploit/app) but still I'm having this problem

**Comment by m0be1** [comment]
I was able to resolve it by adding the path to my config but I had installed it in a quirky location and had to set that location in my path... I installed set in /root/Document/settoolkit rather than default path /opt/metasploit/ .

**Comment by byan21** [comment]
Install Metasploit before and change path 
METASPLOIT_PATH=/opt/metasploit/app
It worked on Ubuntu 14.04

**Comment by Cooller0** [comment]
Obrigado @byan21
