### ISSUE TITLE
Site Cloner Caught By Sophos

### ISSUE THREAD

**Issue by eapolsniper** [trustedsec/social-engineer-toolkit#238]
Sophos is catching site cloner when cloning sites like OWA. It shows as a mal/phish-a. The cause of this is linked resources. If you grab all resources such as gif, CSS, png, etc from the cloned site and do a wget, then link them locally, Sophos is unable to differentiate. This would be a valuable code fix.

**Comment by trustedsec** [comment]
Interesting, will take a peek and see what we can do. As an alternative instead of using site cloner, you can just clown your own and use the import site functionality. This will take everything from a folder.

**Comment by trustedsec** [comment]
OK - I've added this option to version 7.2.. when its released (this week) - if you edit /etc/setoolkit/set.config and turn WGET_DEEP to ON it will allow you to clone it all in one directory.
