### ISSUE TITLE
mailer 

### ISSUE THREAD

**Issue by Doktor28** [trustedsec/social-engineer-toolkit#239]
when i send to hotlmail with set in the past was work normly i show the msg inbox 
but now i don't shop never no junk no inbox 
i try many times and many email gmail 
please help me what the problem

**Comment by darker0n** [comment]
@Doktor28 yes, i have the same problem. SET says that everything is good, but i don't receive letters. Can anybody help?

**Comment by Doktor28** [comment]
i think the problem from gmail he do not work for this method

**Comment by trustedsec** [comment]
Gmail works if you are using an application specific password. I will address this one in version 7.2 Thanks for the report!

**Comment by Doktor28** [comment]
how i use an application specific password
