### ISSUE TITLE
Enhancement Suggestion

### ISSUE THREAD

**Issue by rschwass** [trustedsec/social-engineer-toolkit#241]
I have taken the client_smtp.py script and made changes to it for my own purposes. I like the mass mailer and how easy it is to configure for gmail, hotmail, etc. But I wanted to be able to use my own attachment that I created outside of SET.

so I took all this code:
PDF Previous
if os.path.isfile(setdir + "/template.pdf"):
    if os.path.isfile(setdir + "/template.rar"):
        if os.path.isfile(setdir + "/template.zip"):
            print_warning("Multiple payloads were detected:")
            print ("1. PDF Payload\n2. VBS Payload\n3. Zipfile Payload\n\n")
            choose_payload = input(setprompt("0", ""))
            if choose_payload == '1':
                file_format = (setdir + "/template.pdf")
            if choose_payload == '2':
                file_format = (setdir + "/template.rar")
            if choose_payload == '3':
                file_format = (setdir + "/template.zip")
            counter = 1

			
if counter == 0:
    if os.path.isfile(setdir + "/template.pdf"):
        file_format = (setdir + "/template.pdf")
    if os.path.isfile(setdir + "/template.rar"):
        file_format = (setdir + "/template.rar")
    if os.path.isfile(setdir + "/template.zip"):
        file_format = (setdir + "/template.zip")
    if os.path.isfile(setdir + "/template.doc"):
        file_format = (setdir + "/template.doc")
    if os.path.isfile(setdir + "/template.rtf"):
        file_format = (setdir + "/template.rtf")
    if os.path.isfile(setdir + "/template.mov"):
        file_format = (setdir + "/template.mov")

if not os.path.isfile(file_format):
    exit_set()

 
And Replaced it with this:
Load Attachment

file_format = input("path to attachment:")
print (file_format)

if not os.path.isfile(file_format):
    exit_set()

I'm sure that this can be added to the platform to allow me to simply specify a file to use as an attachment for the spearphising attacks.

Thanks

**Comment by rschwass** [comment]
Looking at this more I may be able to just add it to the file format payload section. So then I can just choose a prebuilt file to add as the attachment.

V/R
rschwass

**Comment by trustedsec** [comment]
I've gone through and added the ability to add attachments to the mass mailer so you can attach anything you want to know. That should resolve this one fully. Thanks for the idea!
