### ISSUE TITLE
setup.py Error

### ISSUE THREAD

**Issue by G3nG4r** [trustedsec/social-engineer-toolkit#244]
hi! i got this issue during the "setup.py" but i don't understand how to fix it.
i have openssl installed.
i have metasploit installed correctly.

issue:
build/temp.macosx-10.6-intel-2.7/_openssl.c:429:10: fatal error:
      'openssl/opensslv.h' file not found

i had other issues during the setup.py

but this was "fatal error".

Thanks for helping me.

**Comment by G3nG4r** [comment]
solved

**Comment by Cabalist** [comment]
How did you solve it?

**Comment by trustedsec** [comment]
Any more detail would be great on this one - will close in a week if I don't hear anything.

**Comment by Cabalist** [comment]
Alright I solved my issue by switching back to Python from PyPy.  I had the same error as @G3nG4r and making that change fixed it.  The `cryptography` python package doesn't currently compile with pypy.

**Comment by trustedsec** [comment]
I'll consider this one closed as its not specific to the setup for SET. I'll add some wording here, thanks for reporting back @Cabalist

**Comment by Cabalist** [comment]
I ran into this issue again and was able to quickly fix it by updating `pip`

```bash
pip install --upgrade pip
```
