### ISSUE TITLE
Broken Setup.py

### ISSUE THREAD

**Issue by Sebass404** [trustedsec/social-engineer-toolkit#247]
I ran the installation on a Ubuntu 14.04 VPS. However, every time I run set it prints out the code to a file. Of which file, I don't know.

**Comment by trustedsec** [comment]
What version of SET are you using? In 14.04 I an run it fine and generates below:

root@stronghold:/home/relik/Desktop/git/social-engineer-toolkit# python setup.py install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
git is already the newest version (1:2.7.4-0ubuntu1).
libapache2-mod-php is already the newest version (1:7.0+35ubuntu6).
python-crypto is already the newest version (2.6.1-6build1).
python-openssl is already the newest version (0.15.1-2build1).
python-requests is already the newest version (2.9.1-3).
python-pefile is already the newest version (1.2.10.139-2).
python-pexpect is already the newest version (4.0.1-1).
python-pymssql is already the newest version (1.0.2+dfsg-2).
apache2 is already the newest version (2.4.18-2ubuntu3.1).
0 upgraded, 0 newly installed, 0 to remove and 166 not upgraded.
[*] Copying SET into the /usr/share/ directory...
[*] Installing setoolkit installer to /usr/bin/setoolkit...

[*] Once downloaded, tar -zxvf impacket*, go to the directory and run python setup.py install.
[*] We are now finished! To run SET, type setoolkit...
