### ISSUE TITLE
Credential Harvester no POST data

### ISSUE THREAD

**Issue by Bry-fi** [trustedsec/social-engineer-toolkit#248]
SET Version: 7.2.3
I setup the SET credential harvester. I go to the website on my local server and I see the login fields like the original website. When I go to enter my fake details, the listener catches no POST data and the harvester.txt has nothing contained in it.

**Comment by jasonpsyc** [comment]
try: apt-get install libapache2-mod-php5

**Comment by trustedsec** [comment]
As a workaround you can edit /etc/setoolkit/set.config and turn apache mode to off and it will use the built in vs. apache.. 

libapache2-mod-php5 is correct
