### ISSUE TITLE
Question about Java Obfuscation commits

### ISSUE THREAD

**Issue by Cabalist** [trustedsec/social-engineer-toolkit#252]
Hey!

Friendly question: I am seeing a lot of these Java Obfuscation commits in the history and the git pull is really large from all the binary diffs.  I am curious about the motivation behind that and if there are some other options (like a git submodule) you would be willing to consider.  The messages make it very hard to track commits because the signal to noise ratio is so heavy.

What is this code doing and why?

Would creating a separate repo that hosted these changes be considered?  Without knowing the purpose of these files I think that a Git Submodule would be a nice fit.  Basically when you pull this repo down you would automatically fetch the latest version of the other repo.  The other repo would hold the constantly chasing Java file and only that.  You can read more [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules) or the quick version [here](https://chrisjean.com/git-submodules-adding-using-removing-and-updating/)

**Comment by trustedsec** [comment]
Hey there - this was done in order to send obfuscated java applets that were getting picked up by AV. It's updated every so often in order to ensure it stays that way. Worked for several years :-) I've increased the interval so it isn't as much since I doubt sigs are being written that often.
