### ISSUE TITLE
Error messages displayed off screen

### ISSUE THREAD

**Issue by jaredhaight** [trustedsec/social-engineer-toolkit#253]
Because the menu is reprinted after an error, any error messages that were sent back are displayed off screen. This can create some confusion for users, especially when it's 6 in the morning and they're trying to play with the newest version of SET. :smile:

I'll dig into the code and see if I can get a PR in for this, but thought I'd submit an issue in case you all have an easy fix up your sleeve.

Example of scrolling up to see an error:
![set_error](https://cloud.githubusercontent.com/assets/1220886/17172576/bf311190-53c3-11e6-8609-20d2c5d94b5a.png)

**Comment by trustedsec** [comment]
Thanks! Put a press return to continue and updated. Just git pull and should be there.
