### ISSUE TITLE
Missing src/sms/protectedapi.py file

### ISSUE THREAD

**Issue by sbrun** [trustedsec/social-engineer-toolkit#254]
Hi,
I was trying to update the Kali package to the latest version and I noticed that there is no src/sms/protectedapi.py , only the .pyc file. It would be great to have the source code.
Moreover the packaging tools don't handle very well when there is only a .pyc (it's automatically removed).
Thanks

**Comment by trustedsec** [comment]
This is intentional - please check the comments under SMS:

        # note that the function for this is in a compiled python file with no source - this was done at the request of the third party we use since the API is not documented. I hand wrote the code and can validate its authenticity - it imports python requests and json and uses that to interact with the API. From a security standpoint if you are uncomfortable using this - feel free to ping me and I can walk you through what I do without giving away the API from the third party.

**Comment by trustedsec** [comment]
If there's anything you need from me to help on this let me know - as of right now, the APIs are closed on behalf of spoofmytextmessage - will try to get permission to open them up (already working on that). I wrote the API code myself, but can't publish it.
