### ISSUE TITLE
NameError: name 'log' is not defined

### ISSUE THREAD

**Issue by marcusguita** [trustedsec/social-engineer-toolkit#256]
Hi,

I have error on SET, after sequence: 1 2 3 1

set:webattack> Select a template:1
Traceback (most recent call last):
  File "setoolkit", line 276, in <module>
    log(error)
NameError: name 'log' is not defined

I am use  SET version: 7.3.1, and Linux ubuntulinux 3.19.0-65-generic #73~14.04.1-Ubuntu

**Comment by trustedsec** [comment]
Looks like your setoolkit didn't get updated somehow in 7.3.1 - do a gitpull and try this one again, I can't reproduce but looks to be fixed.

**Comment by marcusguita** [comment]
Thanks! Updated to version 7.3.2 and the error disapears.

**Comment by marcusguita** [comment]
I tried to install this version 7.3.2 in ubuntu 12, 14, 15 and debian 7 and 8 (by windows azure) and received same error. This is bug? I need to open a new issue? Thanks!
