### ISSUE TITLE
SMS 'no module called requests'

### ISSUE THREAD

**Issue by 25zerotwo** [trustedsec/social-engineer-toolkit#257]
When running the "Social-engineering attacks - SMS Spoofing Attack Vector" I received the 'no module called REQUESTS before SET quits out (sorry had fixed and lost terminal message prior to raising).

Running apt-get install python-requests fixes issue, however the aforementioned error is not what was desired judging by the error message in the sms.py file.

Cheers, Chris

**Comment by trustedsec** [comment]
hrm, thanks for the report - thought i handled that appropriately, I'll take a peek and fix, much appreciated :)

**Comment by trustedsec** [comment]
fixed in 7.3.2, thanks!
