### ISSUE TITLE
SMS-Spoofing

### ISSUE THREAD

**Issue by x0dus35** [trustedsec/social-engineer-toolkit#259]
I updated SEToolkit to version: 7.3.2 and now it has a new sms spoofing option www.spoofmytextmessage.com . the problem is I used to pay with sending an sms in the omd smsgang service that was included in SET, now i can't do that and i don't have a paypal account nor bitcoin. Can you bring back SMSGang option in a future update?

**Comment by trustedsec** [comment]
Unfortunately the SMSGang folks wouldn't fix their stuff and the SMS spoofing was no longer working. I can add it back in but the actual source spoof number will not work.
