### ISSUE TITLE
SMS Spoofing Error

### ISSUE THREAD

**Issue by jaredhaight** [trustedsec/social-engineer-toolkit#261]
When I try to use the SMS Spoofing vector, it errors out. I've confirmed that the username/password that I'm entering is correct, I have credits on the account and internet access works on the VM I'm running this in.

Wonder if it's because of the plus sign in the email?

Example (redacted) output:
```
[*] Okay! Moving on - SET needs some information from you in order to spoof the message.
set:sms> Enter your email address for the spoofmytextmessage.com account:jared+spoofsms@[DOMAIN]
set:sms> Enter your password for the spoofmytextmessage.com account:[REDACTED]
[*] The next section requires a country code, this is the code you would use to dial to the specific country, for example if I was sending a message to 555-555-5555 to the United States (or from) you would enter +1 below.
set:sms> Enter the country code for the number you are sending TO (for example U.S would be '+1')[+1]:
set:sms> Enter the country code for the number you are sending FROM (for example U.S. would be '+1')[+1]:
set:sms> Enter the number to send the SMS TO - be sure to include country code (example: +15551234567):+1##########
set:sms> Enter the number you want to come FROM - be sure to include country code (example: +15551234567):+1##########
set:sms> Enter the message you want to send via the text message:test
[*] Grabbing initial ID from spoofmytextmessage.com...
[!] Unable to authenticate and pull down from the site. Check your settings and try again.
Press {return} to return to the previous menu.

```

**Comment by trustedsec** [comment]
The + shouldn't have an issue with it. I'll push an update that prints out the error message from the API and see if its more descriptive.

**Comment by trustedsec** [comment]
Try running it again with the latest version, pushed an error message so it'll show the response back from the site..

**Comment by trustedsec** [comment]
Here's my output, works good:

set:sms> Enter the message you want to send via the text message:this is a test
[*] Grabbing initial ID from spoofmytextmessage.com...
[*] Pulling unique identifier for SMS codes to send from spoofmytextmessage.com...
[*] Crafting the SMS message and sending through spoofmytextmessage.com...
[*] You have successfully sent your text message.
Press {return} to return the previous menu.

**Comment by jaredhaight** [comment]
Here's the error message that I'm getting:

```
Do you accept these terms (yes or no): yes
[*] Okay! Moving on - SET needs some information from you in order to spoof the message.
set:sms> Enter your email address for the spoofmytextmessage.com account:jared+spoofsms@[DOMAIN]
set:sms> Enter your password for the spoofmytextmessage.com account: [REDACTED]
[*] The next section requires a country code, this is the code you would use to dial to the specific country, for example if I was sending a message to 555-555-5555 to the United States (or from) you would enter +1 below.
set:sms> Enter the country code for the number you are sending TO (for example U.S would be '+1')[+1]:+1
set:sms> Enter the country code for the number you are sending FROM (for example U.S. would be '+1')[+1]:+1          
set:sms> Enter the number to send the SMS TO - be sure to include country code (example: +15551234567):+1XXXXXXXXXXX
set:sms> Enter the number you want to come FROM - be sure to include country code (example: +15551234567):+1XXXXXXXXXX
set:sms> Enter the message you want to send via the text message:test
[*] Grabbing initial ID from spoofmytextmessage.com...
[!] Unable to authenticate and pull down from the site. Check your settings and try again.
[!] Printing error message: list index out of range
```

**Comment by trustedsec** [comment]
Pushed another update to pull the data field for grabbing initial ID, let me know what the JSON value is, be sure to remove your token codes and replace with like XXXX

**Comment by jaredhaight** [comment]
Hrm, stilling getting the same `list index out of range` error with no further details. Triple checked to make sure that I was in sync with master.

Thanks for all the help with this by the way, it's super appreciated. :smile:

**Comment by L1ghtn1ng** [comment]
Dave try using the enumerate method that is built into python and that should help

**Comment by trustedsec** [comment]
Git pull again, you should see this now:

[*] Grabbing initial ID from spoofmytextmessage.com...
[!] Unable to authenticate and pull down from the site. Check your settings and try again.
[!] Printing response from spoofmytextmessage.com: [{u'status': u'error', u'count': 1, u'ts': 1470096999}, {u'messages': [u'You login is incorrect, please try again']}]

Let me know what the error message is..

**Comment by jaredhaight** [comment]
Hahaha, I feel like every user I dealt with back in my sysadmin days. I **swear** I'm typing the right password. :smile: 

I'm copying pasting everything out of my password manager. Password is alphanumeric, no special chars. Confirmed that the same info works to log into the webpage.

```
[*] Okay! Moving on - SET needs some information from you in order to spoof the message.
set:sms> Enter your email address for the spoofmytextmessage.com account:jared+spoofsms@[DOMAIN]
set:sms> Enter your password for the spoofmytextmessage.com account:[REDACTED]
[*] The next section requires a country code, this is the code you would use to dial to the specific country, for example if I was sending a message to 555-555-5555 to the United States (or from) you would enter +1 below.
set:sms> Enter the country code for the number you are sending TO (for example U.S would be '+1')[+1]:+1 
set:sms> Enter the country code for the number you are sending FROM (for example U.S. would be '+1')[+1]:+1
set:sms> Enter the number to send the SMS TO - be sure to include country code (example: +15551234567):+1XXXXXXXXXX
set:sms> Enter the number you want to come FROM - be sure to include country code (example: +15551234567):+1XXXXXXXXXX
set:sms> Enter the message you want to send via the text message:test
[*] Grabbing initial ID from spoofmytextmessage.com...
[!] Unable to authenticate and pull down from the site. Check your settings and try again.
[!] Printing response from spoofmytextmessage.com: [{u'status': u'error', u'count': 1, u'ts': 1470097871}, {u'messages': [u'You login is incorrect, please try again']}]
```

**Comment by trustedsec** [comment]
Might be a problem with their API - let me email them and ask... I believe ya:-)

**Comment by trustedsec** [comment]
Definitely an API issue with spoofmytextmessage.com - if there is a plus sign in either the username or password field it throws invalid login. I shot it out to them, they are usually pretty quick to fix.

**Comment by trustedsec** [comment]
Grab the latest - see if its resolved. I have a test account with +'s now and seems to work..

**Comment by jaredhaight** [comment]
So it looks like it worked.. and then didn't. No text message sent, no codes used according to the dashboard at spoofmytextmessage.

```
set:sms> Enter your email address for the spoofmytextmessage.com account:jared+spoofsms@[DOMAIN]
[*] Note that the password below will be masked and you will not see the output.
set:sms> Enter your password for the spoofmytextmessage.com account:
[*] The next section requires a country code, this is the code you would use to dial to the specific country, for example if I was sending a message to 555-555-5555 to the United States (or from) you would enter +1 below.
set:sms> Enter the country code for the number you are sending TO (for example U.S would be '+1')[+1]:+1
set:sms> Enter the country code for the number you are sending FROM (for example U.S. would be '+1')[+1]:+1
set:sms> Enter the number to send the SMS TO - be sure to include country code (example: +15551234567):+1XXXXXXXXXXX
set:sms> Enter the number you want to come FROM - be sure to include country code (example: +15551234567):+1XXXXXXXXXXX
set:sms> Enter the message you want to send via the text message:Test
[*] Grabbing initial ID from spoofmytextmessage.com...
[*] Pulling unique identifier for SMS codes to send from spoofmytextmessage.com...
[*] Received valid response codes from spoofmytextmessage.com.
[!] Unable to authenticate and pull down from the site. Check your settings and try again.
[!] Printing response from spoofmytextmessage.com: [{u'status': u'success', u'count': 0, u'ts': 1470259933}, {u'messages': None}]
```

**Comment by trustedsec** [comment]
Really strange, here's my output with a plus sign in it and works:

[*] Okay! Moving on - SET needs some information from you in order to spoof the message.
set:sms> Enter your email address for the spoofmytextmessage.com account:XXXXXXX
[*] Note that the password below will be masked and you will not see the output.
set:sms> Enter your password for the spoofmytextmessage.com account:
[*] The next section requires a country code, this is the code you would use to dial to the specific country, for example if I was sending a message to 555-555-5555 to the United States (or from) you would enter +1 below.
set:sms> Enter the country code for the number you are sending TO (for example U.S would be '+1')[+1]:
set:sms> Enter the country code for the number you are sending FROM (for example U.S. would be '+1')[+1]:
set:sms> Enter the number to send the SMS TO - be sure to include country code (example: +15551234567):+1XXXXXXXXXX
set:sms> Enter the number you want to come FROM - be sure to include country code (example: +15551234567):+1XXXXXXXXXX
set:sms> Enter the message you want to send via the text message:testing1
[*] Grabbing initial ID from spoofmytextmessage.com...
[*] Pulling unique identifier for SMS codes to send from spoofmytextmessage.com...
[*] Received valid response codes from spoofmytextmessage.com.
[*] Crafting the SMS message and sending through spoofmytextmessage.com...
[*] You have successfully sent your text message.
Press {return} to return the previous menu.



Investigating some more

**Comment by trustedsec** [comment]
Are you sure you have valid SMS spoofing credits? When I pull mine from the API it shows a ton of codes. Notice my count is 31, your count is 0.

[{u'status': u'success', u'count': 31, u'ts': XXXXXXXX}, {u'messages': [u'XXXXXXX', u'XXXXXX', u'XXXXXX']}]

**Comment by jaredhaight** [comment]
That is super weird. I have 9 codes available.

![codes](https://cloud.githubusercontent.com/assets/1220886/17385233/67d2db12-59af-11e6-8813-c3e81b92de67.png)

**Comment by trustedsec** [comment]
Weird, I'll spend time this week debugging more.

**Comment by trustedsec** [comment]
You have an email I can reach you at by any chance?

**Comment by trustedsec** [comment]
Can ping me davek at derbycon dot com

**Comment by Forpost24** [comment]
[!] Unable to authenticate and pull down from the site. Check your settings and try again.
[!] Printing response from spoofmytextmessage.com: [{u'status': u'error', u'count': 1, u'ts': 1487760335}, {u'messages': [u'You login is incorrect, please try again']}]



I have the same here, anyone who can help ?

**Comment by Forpost24** [comment]
[*] Grabbing initial ID from spoofmytextmessage.com...
[*] Pulling unique identifier for SMS codes to send from spoofmytextmessage.com...
[*] Received valid response codes from spoofmytextmessage.com.
 what is the problem of this ???
