### ISSUE TITLE
Harvester Output 

### ISSUE THREAD

**Issue by KaliSentinelX** [trustedsec/social-engineer-toolkit#263]
Version of SET 7.3.4
OS Kali Linux 4.6.4
Accessing local host through- Mozilla Firefox 47.0.1
Using SET server instead if Apache2 since apache2 was not even giving me an output at all.
So I'm trying to set up a harvester on my local-host and once it is set up this is what I get when I input user-name and password into the fields. Now I did ran it twice just in case it was something I did wrong and the second part of the output was what I got instead of the longer log.
Correct me if am wrong but is it not supposed to output the credentials that were inputed into the fields not just __user=0. I searched for a fix for this and honestly have not found anything useful. 
If anyone has an answer to this issue or I'm just being dumb let me know.
v/r
Sentinel X

[*] WE GOT A HIT! Printing the output:
PARAM: __a=1
PARAM: __be=-1
PARAM: __dyn=7xeUmGdwgrgfodpbG4oy4S-C11xG12xybxu13wm8gxZ3ocU9UKaxe4Ea8uwh9UcU88lwIwHwJDwnUO6Egx60yo
PARAM: __pc=PHASED:DEFAULT
PARAM: __req=1
PARAM: __rev=2475792
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: lsd=AVojcvCK
PARAM: ph=V3
POSSIBLE USERNAME FIELD FOUND: q=[{"user":"0","page_id":"z8f005","posts":[["script_path_change",{"source_path":"/login.php","source_token":"ad976420","dest_path":"/login.php","dest_token":"ad976420","impression_id":"9fbb33a6","cause":"load","source_restored":true},1470006139969,0],["scuba_sample",{"int":{"clientWidth":1906,"clientHeight":945},"normal":{"view":"normal"},"_ds":"www_tinyview_port","_options":{"addBrowserFields":true}},1470006140024,0],["time_spent_bit_array",{"tos_id":"z8f005","start_time":1470006139,"tos_array":[255,0],"tos_len":9,"tos_seq":0,"tos_cum":8},1470006147967,0],["ods:ms.time_spent.qa.www",{"time_spent.bits.js_initialized":[1]},1470006147969,0],["scuba_sample",{"int":{"navigationStart":1470006135829,"fetchStart":1470006139691,"domainLookupStart":1470006139691,"domainLookupEnd":1470006139691,"connectStart":1470006139691,"connectEnd":1470006139691,"requestStart":1470006139691,"responseStart":1470006139691,"responseEnd":1470006139711,"domLoading":1470006135837,"domInteractive":1470006135871,"domContentLoadedEventStart":1470006135874,"domContentLoadedEventEnd":1470006135874,"domComplete":1470006139985,"loadEventStart":1470006139985,"loadEventEnd":1470006139991},"normal":{"protocol":"http","domain":"127.0.0.1","port":8080,"path":"/"},"_ds":"navigation_timing","_options":{"addBrowserFields":true,"addGeoFields":true,"addPredictedGeographyFields":true,"addMobileDeviceFields":true}},1470006147975,0]],"trigger":"ods:ms.time_spent.qa.www"},{"user":"0","page_id":"ux3jd","posts":[["time_spent_bit_array",{"tos_id":"ux3jd","start_time":1470003544,"tos_array":[1,0],"tos_len":2,"tos_seq":2,"tos_cum":15},1470003545299,0]]},{"user":"0","page_id":"9mh0k7","posts":[["time_spent_bit_array",{"tos_id":"9mh0k7","start_time":1470003626,"tos_array":[269,0],"tos_len":9,"tos_seq":0,"tos_cum":4},1470003634608,0],["time_spent_bit_array",{"tos_id":"9mh0k7","start_time":1470003635,"tos_array":[1965819,0],"tos_len":21,"tos_seq":1,"tos_cum":22},1470003655529,0]]},{"user":"0","page_id":"cjpjr3","posts":[["time_spent_bit_array",{"tos_id":"cjpjr3","start_time":1470003815,"tos_array":[79,0],"tos_len":9,"tos_seq":0,"tos_cum":5},1470003823732,0],["time_spent_bit_array",{"tos_id":"cjpjr3","start_time":1470003825,"tos_array":[264273999,0],"tos_len":28,"tos_seq":1,"tos_cum":17},1470003852983,0]]},{"user":"0","page_id":"oshiob","posts":[["time_spent_bit_array",{"tos_id":"oshiob","start_time":1470006122,"tos_array":[373,0],"tos_len":9,"tos_seq":0,"tos_cum":6},1470006130997,0],["time_spent_bit_array",{"tos_id":"oshiob","start_time":1470006132,"tos_array":[15,0],"tos_len":4,"tos_seq":1,"tos_cum":10},1470006135840,0],["script_path_change",{"source_path":"/login.php","source_token":"ad976420","dest_path":null,"dest_token":null,"cause":"unload"},1470006135841,0]]}]
PARAM: ts=1470006147984

[*] WE GOT A HIT! Printing the output:
PARAM: __a=1
PARAM: __be=-1
PARAM: __dyn=7xeUmGdwgrgfodpbG4oy4S-C11xG12xybxu13wm8gxZ3ocU9UKaxe4Ea8uwh9UcU88lwIwHwJDwnUO6Egx60yo
PARAM: __pc=PHASED:DEFAULT
PARAM: __req=2
PARAM: __rev=2475792
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: lsd=AVojcvCK
PARAM: ph=V3
POSSIBLE USERNAME FIELD FOUND: q=[{"user":"0","page_id":"z8f005","posts":[["time_spent_bit_array",{"tos_id":"z8f005","start_time":1470006160,"tos_array":[5,0],"tos_len":64,"tos_seq":1,"tos_cum":10},1470006224991,0]],"trigger":"time_spent_bit_array"}]
PARAM: ts=1470006357981
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

127.0.0.1 - - [31/Jul/2016 18:06:01] "GET / HTTP/1.1" 200 -
[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: __a=1
PARAM: __dyn=7xeUmGdwgrgfodpbG4oy4S-C11xG12xybxu13wm8gxZ3ocU9UKaxe4Ea8uwh9UcU88lwIwHwJDwnUO6Egx60yo
PARAM: __req=1
PARAM: __be=-1
PARAM: __pc=PHASED:DEFAULT
PARAM: lsd=AVojcvCK
PARAM: __rev=2475792
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

**Comment by trustedsec** [comment]
This would be based on whatever website you are cloning and the POST parameters that are specified. If the website is funky, you may need to change the post parameters and its location/address. If you open up the index.html file, you can change them in there.

**Comment by KaliSentinelX** [comment]
Thank you for the advice, I was trying to do a FB clone and got that error but it works fine with other sites. Keep up the hard work you rock!
