### ISSUE TITLE
set apache to off but still saying its on?

### ISSUE THREAD

**Issue by thejbruu** [trustedsec/social-engineer-toolkit#264]
i set apache server to off but for some reason whenever i start set it still says its on and outputs everything in apache.

**Comment by KaliSentinelX** [comment]
you turned Apache2 off in the config files?

it should look like this-
### Use Apache instead of the standard Python web server. This will increase the speed
### of the attack vector.
APACHE_SERVER=OFF

**Comment by trustedsec** [comment]
If Apache is turned off, it doesn't launch that it uses the Python web server.. You will need to manually turn off Apache if its running - service apache2 stop
