### ISSUE TITLE
apache IS set to off but still on

### ISSUE THREAD

**Issue by thejbruu** [trustedsec/social-engineer-toolkit#265]
sorry i couldnt reply in time but yes i know to turn off apache lol i did but it still says its on?? this is in config.baseline im not sure if theres anywhere else i need to set it to off? used to be just one config file 

### of the attack vector.
APACHE_SERVER=OFF
#
### Path to the Apache web root.
APACHE_DIRECTORY=/var/www

**Comment by trustedsec** [comment]
When you do a netstat -antp | grep 80 what is running there? When I do my test it works fine and apache is shut off.

**Comment by thejbruu** [comment]
tcp6       0      0 :::80                   :::*                    LISTEN      12670/apache2       
tcp6       0      0 ::1:80                  ::1:48338               TIME_WAIT   -                   
tcp6       0      0 ::1:80                  ::1:48339               TIME_WAIT   -

**Comment by trustedsec** [comment]
Not sure what to tell you:

Config option:

### Use Apache instead of the standard Python web server. This will increase the speed
### of the attack vector.
APACHE_SERVER=OFF

Launch cred harvvester:

tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      12680/python   

Works as advertised.

**Comment by thejbruu** [comment]
should i be editing anything else besides config.baseline in core?

**Comment by trustedsec** [comment]
You shouldn't be editing the config.baseline at all, you need to edit the /etc/setoolkit/set.config - that is where SET pulls. config.baseline is only used if there is an update needed from updates. You shouldn't be touching that one.

**Comment by thejbruu** [comment]
i dont have a set.config? should i just reinstall set?

**Comment by trustedsec** [comment]
If you don't have a set.config that means you didn't run python setup.py install.
