### ISSUE TITLE
Unused code.

### ISSUE THREAD

**Issue by Cabalist** [trustedsec/social-engineer-toolkit#266]
There are some vestiges of code for windows environments detection but on a whole this codebase is not windows compliant.  At all. 

Any thoughts/discussion on removing code related to executing on a windows machine?  It would simplify the code in places quite a bit.

**Comment by trustedsec** [comment]
absolutely - can totally remove windows references, it was compliant with windows awhile back - no longer need or supported

**Comment by Cabalist** [comment]
Goody!
