### ISSUE TITLE
Metasploit path not found / OS X 

### ISSUE THREAD

**Issue by Bastyl** [trustedsec/social-engineer-toolkit#269]
Hi
I'm having problems with metasploit's path. ¿what file I must modify, in os x ?
I'm reviewing the files but not find the path /etc/setoolkit/set.config

this is what i get:
[!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.

**Comment by trustedsec** [comment]
Did you run python setup.py install first?

**Comment by krisk1712** [comment]
Yes I have ran it but still it shows the same thing
