### ISSUE TITLE
Mac OSX Error

### ISSUE THREAD

**Issue by retriple333** [trustedsec/social-engineer-toolkit#272]
After installing everything I need, I run the toolkit and I get this:

**Traceback (most recent call last):
  File "./setoolkit", line 34, in <module>
    os.makedirs("/etc/setoolkit/")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/etc/setoolkit/'**

Any Reason for this?

(I have ran the setup too, and its been done.)

Thanks

**Comment by trustedsec** [comment]
Run SET with sudo or root priv.
