### ISSUE TITLE
MacOSX Problem, Internet Connection?

### ISSUE THREAD

**Issue by retriple333** [trustedsec/social-engineer-toolkit#273]
I am currently attempting to build a fake website for the phishing.

However...

I have two issues

1. How can I find apache, to see the logs, 

2, When I type in the IP provided, I get nothing??

OSX El Captain

**Comment by trustedsec** [comment]
Found an issue where OSX would not have wget installed (first preference) then falls back to urllib which is only in python3. I've added urllib2 as a fallback for python2.7, when I push this update, that should be resolved. Thanks for the report! Should have this version out shortly.
