### ISSUE TITLE
php5 error

### ISSUE THREAD

**Issue by g33xter** [trustedsec/social-engineer-toolkit#274]
Hi, I was running setoolkit and got this below error
**_/* If you are just seeing plain text you need to install php5 for apache apt-get install libapache2-mod-php5 */_**
I do have updated php7.0 installed on Kali Linux Rolling. So, the question is, setoolkit support php7.0 or just php5?

**Comment by trustedsec** [comment]
That means that you are seeing plain-text and Apache isn't rendering PHP code. PHP5 or 7 isn't a difference. You would need to run apt-get install libapache2-mod-php or libapache2-mod-php7.0. Not a SET issue =)
