### ISSUE TITLE
QRCode Generator Attack vector error

### ISSUE THREAD

**Issue by Kaicastledine** [trustedsec/social-engineer-toolkit#277]
Hello

When trying to use this module I get the following error.

![image](https://cloud.githubusercontent.com/assets/11678433/17885562/a4938400-6915-11e6-8fc6-5e71249c1e32.png)

However python-imaging is already installed (Kali 2VM) and the URL seems to be broken with a 404.

Is there an updated or another guide on how to get this resolved ?
Might be worth replacing the current URL when found/made.

Many thanks

**Comment by Kaicastledine** [comment]
Pip install pil results as follows
![image](https://cloud.githubusercontent.com/assets/11678433/17886467/c6fe3a22-6919-11e6-97dd-dc32dceedcde.png)

**Comment by L1ghtn1ng** [comment]
You need to be using kali rolling not kali 2 that is your issue.

**Comment by Kaicastledine** [comment]
Hello,
I am on rolling sorry for the mix up.
![image](https://cloud.githubusercontent.com/assets/11678433/17890296/f6fb4554-692c-11e6-8a65-b441afacdf6a.png)

**Comment by L1ghtn1ng** [comment]
You do not need to have the bleeding edge repo now that kali is a rolling release, but please check your repos are correct http://docs.kali.org/general-use/kali-linux-sources-list-repositories

**Comment by Kaicastledine** [comment]
Thanks I've removed the unnecessary repo's 
Any idea how to resolve the PIL issue ?

**Comment by L1ghtn1ng** [comment]
Try installing python3-imaging and see if that does it. If not then we will need to wait for Dave to chip in

**Comment by L1ghtn1ng** [comment]
Also what would be interesting to see if this happens on a new instance of kali rolling

**Comment by Kaicastledine** [comment]
Can't install  it with apt-get due to it being obsolete. 
Can Always test it on a new VM however I would need it working on this one ideally.

**Comment by Kaicastledine** [comment]
Tried installing python3-pil and got the following response 
![image](https://cloud.githubusercontent.com/assets/11678433/17898713/b53363b2-6950-11e6-8229-b301d22259d8.png)

**Comment by Ododo** [comment]
Try installing Pillow and not Pil with pip install Pillow

**Comment by Kaicastledine** [comment]
Interestingly I get this error.... However I've never had an issue installing anything with pip before
![image](https://cloud.githubusercontent.com/assets/11678433/17961657/f0c58ffe-6aa4-11e6-932b-96def12267e2.png)

**Comment by Kaicastledine** [comment]
Ah Think I've run out of space ! Let me sort it and I'll try it again and get back to you.
Seems some jobs left running have created an unexpected amount of logs.

**Comment by Kaicastledine** [comment]
Pillow seems to be already installed
![image](https://cloud.githubusercontent.com/assets/11678433/17971606/6d55ae9a-6ad3-11e6-83b1-ebf6130c9811.png)

**Comment by Ododo** [comment]
Also check for Pillow for python3 ( apt-get install python3-pip && pip3 install Pillow)

**Comment by Kaicastledine** [comment]
![image](https://cloud.githubusercontent.com/assets/11678433/18086244/d3403bc2-6ea6-11e6-8674-ead98d5b71b7.png)
 Just ran that and here's the response.

**Comment by Kaicastledine** [comment]
Is it possible to get this reopened please ?

**Comment by Kaicastledine** [comment]
@Ododo Is it possible to get this reopened please ?

**Comment by pavlukivan** [comment]
@Kaicastledine install also qrcode via pip3

**Comment by GeneralBison** [comment]
I'm also getting this issue.
Running on Ubuntu 16.10, tried installing Pillow and qrcode through both pip and pip3.
Any advice?
