### ISSUE TITLE
Custom Written DLL Hijacking Attack Vector issue

### ISSUE THREAD

**Issue by superfoil123** [trustedsec/social-engineer-toolkit#279]
Greetings, I'm currently running into an issue with the Custom Written DLL Hijacking Attack Vector module. 

This is the error I'm currently receiving: 

Enter the number for the payload [meterpreter_reverse_https]:1
[*] Prepping pyInjector for delivery..

 The DLL Hijacker vulnerability will allow normal file extenstions to
 call local (or remote) .dll files that can then call your payload or
 executable. In this scenario it will compact the attack in a zip file
 and when the user opens the file extension, will trigger the dll then
 ultimately our payload. During the time of this release, all of these
 file extensions were tested and appear to work and are not patched. This
 will continiously be updated as time goes on.

[!] Something went wrong, printing the error: [Errno 2] No such file or directory: '/root/.set//src/webattack/dll_hijacking/repository'

I'm on version 7.3.12, any ideas? Thanks.

**Comment by trustedsec** [comment]
That should be fixed now, let me know if you run into any other issues, thanks!
