### ISSUE TITLE
Trying To run seautomate

### ISSUE THREAD

**Issue by rschwass** [trustedsec/social-engineer-toolkit#282]
I am having an issue with seautomate. 

This is my script i'm running it against:
::::::::beginscript::::::
1
5
2
/home/user/list.txt
2
user@domain
MSUpdates
user@domain
P@ssw0rd
outlook.office365.com
587
no
n
Critical System Updated
h
<html><p>test</p></html>
END

::::::::END:::::::

It keeps stopping asking me for the open relay password, but I am specifying it in the script.
Any help would be appreciated.

**Comment by rschwass** [comment]
Ok. I look at the code and I'm guessing it has something to do with the this:

match1 = re.search("OMGPASSWORDHERE", line)
                if match1:
                    line = line.replace("OMGPASSWORDHERE", "")
                    password = True

I am assuming that I need to put the OMGPASSWORDHERE string in where my password is in my answer file. 

Please let me know.

**Comment by rschwass** [comment]
No help?
Bump

**Comment by trustedsec** [comment]
Busy running a conference at the moment, will fix when I can but you can also troubleshoot. The code is open source :)

**Comment by rschwass** [comment]
Touché . No hurry. I'll look into it as well. I had other problems with the PTF build, so let me try it on the Kali build.

**Comment by trustedsec** [comment]
This issue was primarily due to no delay prior to launching seautomate and some of the commands didn't work. I've since fixed this and is now working. I'll be submitting the commit here in about an hour after I finish with other bugs.
