### ISSUE TITLE
Issue setting up Wireless AP

### ISSUE THREAD

**Issue by 1thatonedude1** [trustedsec/social-engineer-toolkit#286]
As i was setting up an AP, i got this error:

[!] Something went wrong, printing the error: name 'wlan0' is not defined

I was able to fix it by changing input() to raw_input(), however the wireless AP never came up

Also, when selecting to stop the AP, the processes it tried to stop were never started

**Comment by trustedsec** [comment]
Give it a shot now, think I fixed that.

**Comment by 1thatonedude1** [comment]
Thank you!
