### ISSUE TITLE
Can't send email to SMTPS server

### ISSUE THREAD

**Issue by zsaile** [trustedsec/social-engineer-toolkit#288]
I have tried to use the SET mass mailer feature to send out an email to using using an authenticated 3rd party mail server. I am not able to establish a connection to the server as the server only support TLS/SSL email connection. 

When i test with my own server which support STARTTLS it works, however this other server i try is explicitly configured for TLS, and i cannot get SET to connect to it. It just times out after the remote server rejects the connection since no TLS session is started after syn/ack. 

You can test this with setting the mail server to mail.privateemail.com port 465

Steps: 

> Launch SET
> Choose 1)
> Choose 5)
> Choose 1.
> Enter to: details
> Choose 2. use your own server
> fill in other details, and in the SMTP email server enter: mail.privateemail.com port 465

After some time the message will fail, and if i do a wireshark i can see the session send back a reset as my side did not open a TLS session.

**Comment by trustedsec** [comment]
Thanks for the report, I've addressed this in the latest version. Should be released in the next week.
