### ISSUE TITLE
Error while using website cloning tool

### ISSUE THREAD

**Issue by codejunkes** [trustedsec/social-engineer-toolkit#289]
Error message: 

Something went wrong, printing the error: zipimporter() argument 1 must be string, not function

Actions taken: setoolkit >  Social-Engineering Attacks > Website Attack Vectors > Credential Harvester Attack Method > Web Template or Site Cloner .... gives this error

OS: Kali Linux 2.0 : kernel: 4.6.0-kali1-amd64 

Python3 version: Python 3.5.2+
Python version: Python 2.7.12+

**Comment by L1ghtn1ng** [comment]
It looks like you are not using kali rolling, please make sure you are and have an up to date system and see if you get the same issue

**Comment by codejunkes** [comment]
Yes I am using kali rolling  i.e.  "deb http://http.kali.org/kali kali-rolling main contrib non-free"

I also git clone and install social-engineer-toolkit, but still the problem exist. 

I think it is a problem with "en_US.UTF-8" encoding.

**Comment by userdsp** [comment]
Same here! Everything ots up to date!

[*] This could take a little bit...
[!] Something went wrong, printing the error: zipimporter() argument 1 must be string, not function

**Comment by gearcapitan** [comment]
how to fix this error?????

**Comment by cicadian314** [comment]
Same problem, with a fresh installation on Debian stretch

[*] This could take a little bit...
[!] Something went wrong, printing the error: zipimporter() argument 1 must be string, not function

**Comment by blackace306** [comment]
I have the same issue. Kali live is fine. And it works on a fresh install up until I run apt-get upgrade. Any ideas?

**Comment by gearcapitan** [comment]
may not be setoolkit problem should be an update as such linux affecting the operation. and try to copy the archvios the set kali kali live my usual but neither works, nor reinstall is dristro problem as such

**Comment by blackace306** [comment]
I think it might be a problem with a new python update. I noticed a lot of python apps being upgraded when I run the upgrade. I think python updated its language and setoolkit has yet to catch up. I'm just not gonna run the upgrade until I find another solution.

**Comment by blackace306** [comment]
It seems to be a fairly new issue as I cannot find anything else on it.

**Comment by gearcapitan** [comment]
¬¬ error and has over 4 days and still not resolved

**Comment by blackace306** [comment]
All I can think of is I just reinstalled Kali and will try to exclude all Python upgrades if I run the upgrade at all. Any other ideas are greatly appreciated though.

**Comment by hasrants** [comment]
same issue here. running kali full on rasbery pi 3. was working fine up until i tried using setoolkit again a few days ago. I normally do update/upgrade/dis-upgrade daily to keep kali current.

**Comment by CamelToeJoe** [comment]
Same issue here on my laptop and Raspi.   Just upgraded both.

**Comment by gearcapitan** [comment]
![996a28823cb906784cfa3c12889d72f5](https://cloud.githubusercontent.com/assets/13740942/18525227/356a714c-7a81-11e6-9c85-aa44b426a80a.jpg)
please!!! any solution?

**Comment by trustedsec** [comment]
What version of SET is this? Unfortunately, this may be a Kali specific issue (still investigating) as it works fine on Ubuntu and Debian.
<img width="1138" alt="screen shot 2016-09-14 at 3 28 29 pm" src="https://cloud.githubusercontent.com/assets/3160808/18526784/f912d022-7a8f-11e6-82fb-820a63fd8485.png">
.

**Comment by trustedsec** [comment]
I don't even use zipimporter for anything....

**Comment by trustedsec** [comment]
If someone can go and edit setoolkit and turn off error handling so I can see which line might be flagging, that would be super helpful.

In Kali, I think SET is located under /etc/setoolkit or /etc/set.

Go to that, 

vi or nano setoolkit

On the very last lines where it has except Exception, comment all of that out like this:

# handle exceptions
##except Exception as error:
 #   core.log(error)
 #   print("\n\n[!] Something went wrong, printing the error: " + str(error))

Save and exit, then re-run and give me the full error message.

**Comment by gearcapitan** [comment]
![ff37b80d21b352b3d7c967dbc14f8401](https://cloud.githubusercontent.com/assets/13740942/18526857/d76c7d40-7a87-11e6-9706-ea407d93c11d.png)
╭──[root Hacked by Gear in ~ process!]
╰──○ uname -a
Linux Gear 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux


how to delete zipimporter o how to fix? :'(

**Comment by CamelToeJoe** [comment]
Traceback (most recent call last):
  File "./setoolkit", line 243, in <module>
    import src.core.set
  File "/usr/share/set/src/core/set.py", line 473, in <module>
    import harvester
  File "/usr/share/set/src/webattack/harvester/harvester.py", line 47, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2976, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2962, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2989, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws = cls()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1931, in find_distributions
    importer = get_importer(path_item)
  File "/usr/lib/python2.7/pkgutil.py", line 384, in get_importer
    importer = path_hook(path_item)
TypeError: zipimporter() argument 1 must be string, not function

**Comment by trustedsec** [comment]
Thanks, can you edit line 46 under src/webattack/harvester/harvester.py and comment out:

# detect openssl module
#try:
#    from OpenSSL import SSL
# handle import error that openssl is not there
#except ImportError:
#    print("Python OpenSSL wasn't detected, note that SSL compatibility is now turned off")

**Comment by gearcapitan** [comment]
![kali 2016-2016-09-14-15-02-44](https://cloud.githubusercontent.com/assets/13740942/18527917/5942c654-7a8c-11e6-8ccf-700bfe0915aa.png)

:'(

**Comment by CamelToeJoe** [comment]
Working now... will this get updated or will I need to go through all my machines and manually comment out the lines?

**Comment by Andimaxgt** [comment]
Btw ,which scripting software are you using ,@gearcaptain ?looks nice

**Comment by PandoraSec** [comment]
![screenshot from 2016-09-14 14-23-10](https://cloud.githubusercontent.com/assets/22203976/18528635/7c1e96e6-7a8f-11e6-9463-7d13dcc29b27.png)
i comment out the line and works for me, thanks :dancer:

**Comment by trustedsec** [comment]
okay, sec I'll get it pushed - looks like maybe a bug in the openssl version in Kali, but I can handle the errors better.

**Comment by trustedsec** [comment]
Please note that I've pushed 7.3.13 to address this issue and is tagged. It should be picked up by Kali rolling updates shortly. In the meantime if you are using the git repositories its immediately available.

Thanks for the assistance folks.

**Comment by cicadian314** [comment]
Solved on Debian stretch commenting those lines

**Comment by aneopsy** [comment]
Great Captain

**Comment by berryrare** [comment]
Commenting out those lines worked for me too.. Thank you trustedsec

**Comment by himshukla007** [comment]
[!] Something went wrong, printing the error: zipimporter() argument 1 must be string, not function
 plz give solution Version: 7.3.12

**Comment by L1ghtn1ng** [comment]
You need to update set as this is a very old version and this has already been fixed

Sent from phone


________________________________

**Comment by xDef4ult** [comment]
I had the same Problem, solved with the command:
apt-get install set
Right L1ghtn1ng, enough upgrade setoolkit

**Comment by saichand1716** [comment]
I've tried everything but at last, i'm ending with the same issue.
hope someone gives a solution.
thank you.

**Comment by himshukla007** [comment]
i have nely kali linux version...not getting this problem..it already
installed
thank you

**Comment by miao-o** [comment]
I have the same problem in the new kali linux, how to fix it

**Comment by himshukla007** [comment]
upgrade your kali linux

**Comment by vipkiyo** [comment]
![screenshot from 2017-04-15 02-29-53](https://cloud.githubusercontent.com/assets/27511962/25052293/b1d95492-2183-11e7-8d53-a99966717727.png)
![screenshot from 2017-04-15 02-31-33](https://cloud.githubusercontent.com/assets/27511962/25052294/b235498c-2183-11e7-832f-c4ce349f4fb0.png)

i commented out the 2 "print" after the line of "except"

did this solve the problem or it just ommitted the lines that we should see during the attack?

Newbie here. please respect.

**Comment by gashonie** [comment]
Same problem here, any solutions for this ?

**Comment by sieunhando** [comment]
![image](https://cloud.githubusercontent.com/assets/25194841/25609395/460f3640-2f49-11e7-9a7d-9b4fdc6d4634.png)
I tried but cant solve this problem. Anyone help me. This error happen on all Kali linux 2017.1 version.

**Comment by Eyegabry99** [comment]
i have the same problem and comment the line doesn't work on me. Please someone can help me?

**Comment by arismelachroinos** [comment]
me too

**Comment by Kaliuser99** [comment]
I found that there arent any .pem files in my files...nothing..any solution?

**Comment by Kaliuser99** [comment]
The solution would be having those .pem  files...i tried searching the set.config for pem and the location mentioned in it doesnt contain any pem files....maybe try changing location

**Comment by ATOPJC** [comment]
Try updating it  with PTF (pentesters framework) if there is a new version available

**Comment by Kaliuser99** [comment]
Nope i tried with everything ..ptf..a new version from github..nothing
works..see if you guys have any .pem files for setoolkit..i dont seem tp
find any

**Comment by mrmurtaza** [comment]
try it mine fixed.....
https://youtu.be/azG3pzNDSog

**Comment by sriniv398** [comment]
i tired to throu wan credential harvest when cloning website result error:501 not implemented. but lan its works. pls help me

**Comment by sriniv398** [comment]
kali linux 2017.1 social engineering toolkit credential harvester not working in wan "error:501 not implemented" pls help me

**Comment by Kaliuser99** [comment]
Did you try all the steps as above?..

**Comment by sriniv398** [comment]
yeah i tried all steps above but no use pls help me bro

**Comment by sriniv398** [comment]
When i cloning result is below:

[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: __a=1
PARAM: __dyn=7AzHK4GgO649UrJxm2q3miWGey8jrWo466EeVE98nwgUb8aUgxebmEy3eF98qDKaxeUW2y7E4ium2S4o98b8uz8bo5S9J0Px61Bxqq2l0WwCw9a0FopCK6oc9oy6o5-fwByUa8lUoK1fze6E-3C78-5E-dg
PARAM: __af=h0
PARAM: __req=1
PARAM: __be=-1
PARAM: __pc=PHASED:DEFAULT
PARAM: __rev=3314701
PARAM: lsd=AVrr17tz
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

**Comment by himuura** [comment]
i don't know if it is related but i'm having a few issues with the cloner as well...whenever the site i'm cloning has special characters like " Ç " or " ó " the cloned result does not replicate those characters, they instead appear as % ou ~ . Anyone knows how to configure the correct charset?

**Comment by 1598w** [comment]
so when apache is on on set.config that s what i get

- [*] Cloning the website: https://login.........................

[*] This could take a little bit...
The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] Apache is set to ON - everything will be placed in your web root directory of apache.
[*] Files will be written out to the root directory of apache.
[*] ALL files are within your Apache directory since you specified it to ON.
Apache webserver is set to ON. Copying over PHP file to the website.
Please note that all output from the harvester will be found under apache_dir/harvester_date.txt
Feel free to customize post.php in the /var/www/html directory
[*] All files have been copied to /var/www/html
[*] SET is now listening for incoming credentials. You can control-c out of this and completely exit SET at anytime and still keep the attack going.
[*] All files are located under the Apache web root directory: /var/www/html
[*] All fields captures will be displayed below.
[Credential Harvester is now listening below...]
and when i am trying to put somme username and password i dont receivet and the harvester file is Empty

and when apache is off on set.config that s what i get

- [*] Cloning the website: https://login........................................

[*] This could take a little bit...
The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:
[*] Looks like the web_server can't bind to 80. Are you running Apache or NGINX?
Do you want to attempt to disable Apache? [y/n]:
how can i solve this probléme ?????????????????????

**Comment by lucky798a** [comment]
setoolkit

You may need to copy /var/www/* into /var/www/html depending on where your directory structure is. Press {return} if you understand what we're saying here.

honesytly dont understand this. can anyone help me with this pls respect

**Comment by YaroslavBF** [comment]
all have problem with clone website! why author don't fix it?

**Comment by YaroslavBF** [comment]
1>2>3>2 :
[-] Credential harvester will allow you to utilize the clone capabilities within SET
[-] to harvest credentials or parameters from a website as well as place them into a report


[!] Something went wrong, printing the error: [Errno 2] No such file or directory: '/etc/setoolkit/set.config'

**Comment by mehdimers** [comment]
setoolkit

You may need to copy /var/www/* into /var/www/html depending on where your directory structure is. Press {return} if you understand what we're saying here.

**Comment by zly-123** [comment]
为什么我连var/www都没有

**Comment by zly-123** [comment]
![image](https://user-images.githubusercontent.com/59759062/72201159-335cb180-348c-11ea-87be-ca59f69fe833.png)
为什么我的不显示密码和账号只有数据

**Comment by UNKNOWNADWAITH** [comment]
I have another problem please help me in this I can't install SEToolkitls in termux it shows error while installing requirements.txt![Screenshot_2022-04-17-08-52-13-104_com.termux.jpg](https://user-images.githubusercontent.com/99338662/163698968-5adc9b34-e3e7-4996-8b84-512fc3b5b9d3.jpg)

**Comment by ohhlogical** [comment]
> 为什么我的不显示密码和账号只有数据

Any fix to this ?
