### ISSUE TITLE
SET generating payload STUCK !

### ISSUE THREAD

**Issue by xw0Lf** [trustedsec/social-engineer-toolkit#292]
Hey everyone
     I'm facing a problem while creating a payload with SET it just keep telling me ;
          [*] Waiting for payload generation to complete (be patient, takes a bit)...
-----
i already looked up around but none of the comments helped me so i hope anyone of you have a solution for this here
NB!: i alrdy have kali linux updated 
-
root@x******:~# uname -a
Linux ****** 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
-
Thank you

**Comment by trustedsec** [comment]
Your still using an old version. Using bleeding edge repos or something.

**Comment by xw0Lf** [comment]
old version of SET ? or shall i just use bleeding edge over rolling kali ?
