### ISSUE TITLE
Site Clone Issue

### ISSUE THREAD

**Issue by Andimaxgt** [trustedsec/social-engineer-toolkit#293]
The error states as such, "Something went wrong, printing the error: zipimporter() argument 1 must be a string, not function" I get the error while trying to use the site cloner option and custom import option.

**Comment by userdsp** [comment]
@Andimaxgt why close this issue?

**Comment by Andimaxgt** [comment]
I Will reopen It but i thought there is already another thread on this

**Comment by trustedsec** [comment]
Because it was a duplicate.
