### ISSUE TITLE
[!] Update failed? Timestamp on config file is: 2016-09-22 20:38:29.351850

### ISSUE THREAD

**Issue by ashishbishnoi** [trustedsec/social-engineer-toolkit#294]
Can't update SET to latest version i.e 7.3.14. please help

**Comment by trustedsec** [comment]
Would recommend re-trying to check it out. Works fine updating on this end.

**Comment by ashishbishnoi** [comment]
Thanks

**Comment by ware-wolf** [comment]
not able to update
[!] Update failed? Timestamp on config file is: 2017-07-11 16:39:07.216673

**Comment by ware-wolf** [comment]
not able to update'
[!] Update failed? Timestamp on config file is: 2017-07-11 16:39:07.216673
