### ISSUE TITLE
metasploit folder missing

### ISSUE THREAD

**Issue by tonytfng** [trustedsec/social-engineer-toolkit#304]
I've just installed it on ubuntu 16.04, after running python3 setup.py install for installation, I can't find any folder under /opt. 

Locating metasploit and msfconsole returns nothing as well.

Please help, thank you.

**Comment by L1ghtn1ng** [comment]
Have you installed metasploit?

**Comment by pavlukivan** [comment]
setup.py won't install metasploit. You should install it manually via apt-get install metasploit or use the following guide: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
