### ISSUE TITLE
"Unable to clone the specific site. Check for network connection"

### ISSUE THREAD

**Issue by chengteck** [trustedsec/social-engineer-toolkit#307]
Hi there,

I got this error "Unable to clone the specific site. Check for network connection" when I tried cloning a targeted site.

Other sites like Facebook.com works.

Any idea on what could be the issue?

Thank you.

**Comment by trustedsec** [comment]
Works fine for me, I would recommend ensuring you aren't going through a proxy, if you are use set-proxy.

**Comment by netrosec** [comment]
Hello..
I am having the same issue where set says "Error. Unable to clone this specific site. Check your internet connection." i updated my setoolkit yet i get the same error. I need help here.

**Comment by OliverChao** [comment]
Hello guys...
I met this problem just now, and SET said **"[*] You may need to copy /var/www/* into /var/www/html depending on where your directory structure is."** 

Then ,I closed SET and used command "rm -rf  /var/www/html" to remove the directory . Open SET again ,and  that work....

**Comment by luscff99** [comment]
![Screenshot_20200910-032113](https://user-images.githubusercontent.com/70997343/92689480-76ba3900-f315-11ea-9bae-3015c9c140fb.png)
Meu erro é esse aí e não consigo resolver, alguém me ajuda

**Comment by beanc904** [comment]
<img width="484" alt="截屏2021-02-19 上午7 17 25" src="https://user-images.githubusercontent.com/76858940/108434384-88b7e480-7282-11eb-948a-904c6ae684b7.png">
同样遇到此问题！！！求解！！！

**Comment by cinemasforever** [comment]
> Works fine for me, I would recommend ensuring you aren't going through a proxy, if you are use set-proxy.

Are you kidding me you did nothing to help or explain and you just let it be. Tell us how to fix it seirously. "works fine for me dont do through a proxy" doesnt help the actual issue.

**Comment by jamsphotovideography-alt** [comment]
i got this error and cant find a usefull information can sombody pleas help me out

**Comment by lexmark6667-svg** [comment]
here i come with same issue in 2026, pls as anybody come up with any solution with this problem yet?
