### ISSUE TITLE
Spear-Phishing Attack

### ISSUE THREAD

**Issue by zurekx** [trustedsec/social-engineer-toolkit#309]
The Adobe PDF Embedded EXE Social Engineering (NOJS) is not working correctly on the client site it's after the pdf reader (FoxitReader) open cmd the error is displayed that can't find mdf.exe on C:/..../TEMP.
On the Adobe Reader 9 is doesnt show any error but it also does not work 

PDF generated from msfconsole usign  Adobe PDF Embedded EXE Social Engineering (NOJS) works corectly so this is not FoxitReader problem

**Comment by trustedsec** [comment]
I've fixed this in the latest version, should work fine now. Will be updating shortly.
