### ISSUE TITLE
Setting up set

### ISSUE THREAD

**Issue by Hannibalony** [trustedsec/social-engineer-toolkit#310]
i got this error 

> [!] Metasploit payloads are not currently supported. This is coming soon.
[!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.
[-] New set.config.py file generated on: 2016-10-10 21:10:49.004000
[-] Verifying configuration update...
[*] Update verified, config timestamp is: 2016-10-10 21:10:49.004000
[*] SET is using the new config, no need to restart
Traceback (most recent call last):
  File "setoolkit", line 157, in <module>
    with open(os.path.join(core.setdir, "/set.options"), "w") as filewrite:
IOError: [Errno 13] Permission denied: '/set.options'

**Comment by pavlukivan** [comment]
Maybe run it as root?

**Comment by Hannibalony** [comment]
Im also on windows,  wha do you mean by running it as root?

**Comment by pavlukivan** [comment]
#313

**Comment by trustedsec** [comment]
SET isn't supported on windows.

**Comment by Hannibalony** [comment]
So those tuts online are fraud?

**Comment by pavlukivan** [comment]
No, there aren't, but SET community won't support you in running it on windows. And its features will be very limited unless you'll rewrite some code
