### ISSUE TITLE
Starting SET

### ISSUE THREAD

**Issue by Hannibalony** [trustedsec/social-engineer-toolkit#313]
Got the following errors 

> Can't pickle <function pull_version at 0x0000000002A47C88>: it's not found as src.core.setcore.pull_version
 Select from the menu:

>   1) Social-Engineering Attacks
   2) Penetration Testing (Fast-Track)
   3) Third Party Modules
   4) Update the Social-Engineer Toolkit
   5) Update SET configuration
   6) Help, Credits, and About

>  99) Exit the Social-Engineer Toolkit

> set> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Python27\lib\multiprocessing\forking.py", line 346, in main
    prepare(preparation_data)
  File "c:\Python27\lib\multiprocessing\forking.py", line 455, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
> ImportError: No module named setoolkit

**Comment by ProgrammerAndAHalf** [comment]
same proplem here :(

**Comment by pavlukivan** [comment]
If you're running it like that: "python C:\path\to\setoolkit\setoolkit", try "cd C:\path\to\setoolkit" and "python setoolkit". Anyway, set is not officially supported on windows.

**Comment by trustedsec** [comment]
SET isn't supported on Windows.
