### ISSUE TITLE
SET SMS SPOOF

### ISSUE THREAD

**Issue by TWIISTED-SHOPS** [trustedsec/social-engineer-toolkit#316]
when i try to send the message i am getting you dont have python requests installed but i have done apt-get install python-requests and im still having the issue

**Comment by EchoUnderscoreNine** [comment]
try .. pip install requests

**Comment by TWIISTED-SHOPS** [comment]
I have tried that and still says need the python requests but when I check I'm already update with newest ones

Get Outlook for Android<https://aka.ms/ghei36>



On Sun, Oct 16, 2016 at 7:01 AM +0100, "Echo_9" <notifications@github.com<mailto:notifications@github.com>> wrote:


try .. pip install requests

-

**Comment by L1ghtn1ng** [comment]
Try installing requests for python3 so it will be pip3 install requests

**Comment by trustedsec** [comment]
Is this on OS X? If so - it has to do with outdated Python on OS X and would follow @L1ghtn1ng suggestion there.

**Comment by TWIISTED-SHOPS** [comment]
no its on kali linux


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by TWIISTED-SHOPS** [comment]
I have tried all them and it's still now working still saying I don't have it installed but when I go to install it it says it's up to day. I think it could be to do with the set having it already inside the toolkit and it's confusing it with mine.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Oct 18, 2016 at 12:35 AM +0100, "trustedsec" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this on OS X? If so - it has to do with outdated Python on OS X and would follow @L1ghtn1ng<https://github.com/L1ghtn1ng> suggestion there.

-

**Comment by TWIISTED-SHOPS** [comment]
I have fixed the issue I did rm -rf setoolkit then cloned the set off GitHub and ran python setup.py install again and that has fixed it so it was something that was inside the setup original file that's caused the problems

**Comment by nicksedz** [comment]
@TWIISTED-SHOPS what did you use to install the setup.py?

**Comment by TWIISTED-SHOPS** [comment]
@nicksedz I used the terminal to install it

**Comment by skorpy** [comment]
hey, may you explain me how exactly to do that , mean to say the order of commands in terminal. will be your thankful

**Comment by nicksedz** [comment]
@skorpy open terminal. Type in setoolkit. select the number for the attack you want to perform. for me, i type in 1. then i type 10

**Comment by skorpy** [comment]
thanks but its not that what i've asked , i am getting error:

[!] Looks like you dont have python-requests installed. Please install (apt-get install python-requests) and try again.

although i am already have latest.

i've done with couple of things e.g.
pip install requests --upgarde pip
apt-get install python-requests

but nothing gets work may you please explain me what am i suppose to be doing wrong  or what i should do to fix it thanks.

**Comment by Hkr-Doppelganger** [comment]
same error.............Twisted shops please explain

**Comment by JayeshThakkar** [comment]
here is option press return key to continue... so which key to press on for retun
