### ISSUE TITLE
Python OpenSSL error

### ISSUE THREAD

**Issue by TheMightyTaDachs** [trustedsec/social-engineer-toolkit#318]
Error when using Web Jacking Attack Method: Python OpenSSL wasn't detected or has an installation issue, note that SSL compatibility is now turned off

Python OpenSSL is installed.
OS is Arch Linux, SET-version is 7.4.1

**Comment by Magnificgr** [comment]
Same problem

**Comment by kbeflo** [comment]
Hope this helps.

`apt-get install python-pip python-dev python3-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev`

`easy_install pip`

`pip install -r requirements.txt`

**Comment by TheMightyTaDachs** [comment]
ty but i run archlinux so its a different repository and the packages are already installed

**Comment by NoBloodyABCorD** [comment]
Same here, running on nethunter.  I've installed the full kali tools, verified python-openssl is installed and downloaded setoolkit from git.  Still getting an SSL issue

**Comment by jeretc** [comment]
same error " Python OpenSSL wasn't detected or has an installation issue, note that SSL compatibility is now turned off"
pyopenssl already installed.

**Comment by iamtrying-127times** [comment]
Same here.
"http://" works fine. But when I try to spoof an "https://" it don't work.
I am searching if it's about ettercap insue...

**Comment by trustedsec** [comment]
This seems to be a Kali issue with PyOpenSSL. Wouldn't be a SET issue, what you can do is git clone python-openssl and python setup.py install to manually install and address your issue.

You can test this by making a .py file:

# detect openssl module
try:
    from OpenSSL import SSL
# handle import error that openssl is not there
except Exception:
    print("Python OpenSSL wasn't detected or has an installation issue, note that SSL compatibility is now turned off")

Works fine on Ubuntu.

**Comment by jeretc** [comment]
same issue with ParrotSec ..
