### ISSUE TITLE
Sms Spoofing Python Problem even though I've installed python requests.

### ISSUE THREAD

**Issue by maiksir** [trustedsec/social-engineer-toolkit#319]
Hello Guys,

I tried mess around with setoolkit today and while completing the requirements for SMS Spoofing Attack Vectors, After providing with all the information it needs to sent that SMS, like numbers and country codes and all that, This pops up in the terminal.

[!] Looks like you dont have python-requests installed. Please install (apt-get install python-requests) and try again.

The thing is that I did (apt-get install python-requests) and there are no errors or anything. But in Setoolkit it still says the same notification when I try again.

Please advise.

Thanks again!

**Comment by richvincent** [comment]
I just installed Kali Linux as well and I'm experiencing the same issue.

**Comment by pavlukivan** [comment]
Maybe try pip or easy_install?

**Comment by trustedsec** [comment]
Not sure what to say there - I do a standard import on this.  Works fine on me. I would try pip install requests to update it. Sounds like a bad package?

**Comment by nicksedz** [comment]
hey guys.. same problem. I got close with installing a setoolkit python file. Found on this youtube link:https://www.youtube.com/watch?v=UUaOuwZs__I

Still having issues though. Let me know if anyone gets it.

**Comment by skorpy** [comment]
iem getting an issue whenever i try to run sms spoofing in setoolkit it returns an annoying error of 

[!] Looks like you dont have python-requests installed. Please install (apt-get install python-requests) and try again.

**Comment by ncm1** [comment]
Still getting [!] Looks like you dont have python-requests installed. Please install (apt-get install python-requests) and try again.
