### ISSUE TITLE
smtp_client.py sending 2 emails per target

### ISSUE THREAD

**Issue by hertzl** [trustedsec/social-engineer-toolkit#321]
When doing the following with current bleeding edge install and using a local smtp server it seems sendmail is called twice per target address.  Using sendmail at the command line works fine...my comments in bold below are debug print statements.
"mailing next" is above line 414 in current file
"mailing again?" is above line 438 in current file

Also, when looping through input file of multiple addresses the mail function as called asks if using TLS for the server for each address in the input file.  Example output for this in second batch below (again with my comments from debugging dup send).

Hertzl

[-] Sendmail is a Linux based SMTP Server, this can be used to spoof email addresses.
[-] Sendmail can take up to three minutes to start FYI.
[*] Sendmail is set to ON
set:phishing> Start Sendmail? [yes|no]:yes
[-] NOTE: Sendmail can take 3-5 minutes to start.
 * Starting Mail Transport Agent (MTA) sendmail                                                                                                                                                  * MTA is already running.
[-] As an added bonus, use the file-format creator in SET to create your attachment.

   Right now the attachment will be imported with filename of 'template.whatever'

   Do you want to rename the file?

   example Enter the new filename: moo.pdf

    1. Keep the filename, I don't care.
    2. Rename the file, I want to be cool.

set:phishing>1
[*] Keeping the filename and moving on.

   Social Engineer Toolkit Mass E-Mailer

   There are two options on the mass e-mailer, the first would
   be to send an email to one individual person. The second option
   will allow you to import a list and send it to as many people as
   you want within that list.

   What do you want to do:

   1.  E-Mail Attack Single Email Address
   2.  E-Mail Attack Mass Mailer

   99. Return to main menu.

set:phishing>1

   Do you want to use a predefined template or craft
   a one time email template.

   1. Pre-Defined Template
   2. One-Time Use Email Template

set:phishing>1
[-] Available templates:
1: Dan Brown's Angels & Demons
2: Strange internet usage from your computer
3: WOAAAA!!!!!!!!!! This is crazy...
4: Have you seen this?
5: Order Confirmation
6: How long has it been?
7: New Update
8: Status Report
9: Baby Pics
10: Computer Issue
set:phishing>1
set:phishing> Send email to: mytargetaddr@here.com

  1. Use a gmail Account for your email attack.
  2. Use your own server or open relay

set:phishing>2
set:phishing> From address (ex: moo@example.com):moo@example.com
set:phishing> The FROM NAME user will see:moo
set:phishing> Flag this message/s as high priority? [yes|no]:no
**in mail function**
set:phishing> Does your server support TLS? [yes|no]:no
**at counter 0
mailing next
mail again?**
[*] SET has finished delivering the emails

----------------------------------------------------------------------------------

set:phishing>2
set:phishing> From address (ex: moo@example.com):moo@norco.com
set:phishing> The FROM NAME user will see:moo
set:phishing> Flag this message/s as high priority? [yes|no]:no
**in mail function**
set:phishing> Does your server support TLS? [yes|no]:no
**at counter 0
mailing next
mail again?**
   Sent e-mail number: 1
**in mail function**
set:phishing> Does your server support TLS? [yes|no]:no
**at counter 0
mailing next
mail again?**
   Sent e-mail number: 2
**in mail function**
set:phishing> Does your server support TLS? [yes|no]:no
**at counter 0
mailing next
mail again?**
   Sent e-mail number: 3
[*] SET has finished delivering the emails

**Comment by trustedsec** [comment]
I believe I have addressed this in 7.4.2.
