### ISSUE TITLE
zipimporter () 1

### ISSUE THREAD

**Issue by xZeususx** [trustedsec/social-engineer-toolkit#322]
Hello,

here is my issue after hours of googling:

I am using Kali Linux as VMWare on my Win10 notebook and i want to use the site cloner feature from the "setoolkit".
However, it will always throw out the error "zipimporter () argument 1 must be a string, not function"

Some additional information: I want to clone facebook.com. (if this is of any means)

Any suggestions?
Thanks!

**Comment by trustedsec** [comment]
You are using an old version of SET - this was fixed in 7.3.13.

**Comment by rindster** [comment]
i have the same issue using set version 7.6.2
i did apt update and upgrade nothing works

ython OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.
[*] Printing error: zipimporter() argument 1 must be string, not function

plz h
