### ISSUE TITLE
How to Fix my Problem? 

### ISSUE THREAD

**Issue by MrEgaGilbert** [trustedsec/social-engineer-toolkit#325]
[!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.

**Comment by Bry-fi** [comment]
Try locating your metasploit path and defining it in the /etc/setoolkit/set.config file

**Comment by trustedsec** [comment]
^^ what Bry-fi mentioned. If you are using a non standard path - edit the /etc/setoolkit/set.config to point it in the right direction.
