### ISSUE TITLE
Powershell alphanumeric payload now giving only core commands

### ISSUE THREAD

**Issue by Bry-fi** [trustedsec/social-engineer-toolkit#326]
This payload that I have been using for a very long time has suddenly stopped loading all the meterpreter commands and loads just the core commands. There's no cd, pwd, mkdir etc commands just core commands.

**Comment by trustedsec** [comment]
This can sometimes happen when the shell loads and the rest of the metasploit modules dont - you can do this by:

use stdapi
use priv

Going to close this one as it's not a SET issue.
