### ISSUE TITLE
./setoolkit errors

### ISSUE THREAD

**Issue by Newcool1230** [trustedsec/social-engineer-toolkit#329]
Traceback (most recent call last):
File "./setoolkit", line 34, in <module>
os.makedirs("/etc/setoolkit/")
File "/usr/lib/python2.7/os.py, line 157, in makedirs
mkdir(name,mode)

**Comment by retriple333** [comment]
Depending on what OS you are on, (Mac or Linux)

Do 
`cd social-enginner-toolkit-master
sudo ./setoolkit`

Respond back if you get another error.

**Comment by retriple333** [comment]
By the way, don't do those all together,

cd first.

Then sudo.

**Comment by Newcool1230** [comment]
omg it works !!! thanks

**Comment by Newcool1230** [comment]
but now i have a metasploit problem even tho i installed it

https://gyazo.com/874a2811d9dca4ff2e19ac59041ebf2e

and i cant find set.config

**Comment by retriple333** [comment]
Ok.

On Mac:

When on Desktop, go up to "Go"

Then, to "Go To Folder"

Then type in 

/etc/setoolkit/

There it is.

**Comment by retriple333** [comment]
For Linux:

Do the command

`cd /etc/setoolkit`
Then 
`ls`
That should be where the set.config is. 

Then do 
`vi set.config`

You should be able to change the metasploit path.

Do some reading in there.

**Comment by Newcool1230** [comment]
https://gyazo.com/df333eff90f5ff7bca8a161310012031

but i still get
https://gyazo.com/65fed21317b65b0bc8d165b35cd958ba

metasploit is here https://gyazo.com/09027f82840d90799eb6a5389a35e361
