### ISSUE TITLE
during spear phish, no defined file path leads to kick out of SET

### ISSUE THREAD

**Issue by ghctim** [trustedsec/social-engineer-toolkit#33]
When you are doing a social engineering attack of spear phishing with a pdf, if you don't specify the file path 2 times it quits set.  I think it would be better to kick you back to the main menu.

**Comment by setoolkit** [comment]
hello!
can i ask you "how do you solve the problem 'No previous payload created' finally"?

**Comment by setoolkit** [comment]
i also meet the same proplem!

**Comment by firozmahamud29** [comment]
Hi,
I've created a PDF file and close the Terminal. now I want to check is there any victim how can I check it?
