### ISSUE TITLE
Setoolkit Error on Final Version 7.4.2

### ISSUE THREAD

**Issue by arsencenko** [trustedsec/social-engineer-toolkit#331]
Im getting errors on 2 tools im trying to use on my backbox. First is on SMPspoofing, im getting this error:
[!] Something went wrong while attempting to locate the site. Will print the error message below in a second.
[!] If you are getting an SSL23_GET_SERVER_HELLO:tlsv1 alert internal error, this is likely caused by an out of date version of pyopenssl.
[!] Recommend apt-get remove python-openssl, and run pip install pyopenssl to resolve this issue.
[!] Printing the error: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

i did installet pyopenssl and still geting the error.

And second is Spear-Phishing Attack Vectors when i try to render dhe payload stucks on
 [*] Waiting for payload generation to complete (be patient, takes a bit)...

Thanks!

**Comment by hackrush01** [comment]
Try running apt-get install python3-openssl or pip3 install pyopenssl, reboot.  
Then check.

**Comment by trustedsec** [comment]
Duplicate issue and not something that is SET centric. Package for python-openssl looks to be not working appropriately in Kali but works fine in Ubuntu/Debian/Fedora.
