### ISSUE TITLE
Metasploit Path Not found

### ISSUE THREAD

**Issue by retriple333** [trustedsec/social-engineer-toolkit#334]
System Info:
MacOS Sirrea
8GB Memory.

Problem:
I have gone into the config file, with nano,
and edited the file to:

`
### Define the path to Metasploit. For example: /opt/metasploit/apps/pro/msf3
METASPLOIT_PATH=/opt/metasploit-framework
`
That is where my framework is located.

It is still saying it cannot find it.

??

**Comment by trustedsec** [comment]
You need to give it the path of where msfconsole is located, /opt/metasploit-framework wouldn't have msfconsole in it.
