### ISSUE TITLE
OpenSSL not working.

### ISSUE THREAD

**Issue by hackrush01** [trustedsec/social-engineer-toolkit#336]
Installed both python3 openssl and python2 openssl, but still it gives error.
Upon checking, by making this file
```
try:
    from OpenSSL import SSL
except Exception:
    print("Python OpenSSL wasn't detected or has an installation issue, note that SSL compatibility is now turned off")
```

and running it via terminal, no error is received.

**Comment by trustedsec** [comment]
What OS? If this is Kali - looks like package is borked. Works fine on Ubuntu/Debian/Fedora/etc. Wouldn't be an issue here unfortunately.

**Comment by jeretc** [comment]
same issue with ParrotSec
