### ISSUE TITLE
Inquiry on using setoolkit credential harvester with dnsmasq

### ISSUE THREAD

**Issue by mofn** [trustedsec/social-engineer-toolkit#337]
I have custom imported a webpage from m.facebook.com and configured dnsmasq to point at my web server. Credential harvester working well. But all other domain points to the web server except when I enter facbook.com.

**Comment by trustedsec** [comment]
Not sure - this wouldn't necessarily be a SET issue - you would need to ensure dnsmasq is pointing to the web application and heads to the SET webpage in order to hijack DNS and point there.
