### ISSUE TITLE
SMS SPOOF ERROR

### ISSUE THREAD

**Issue by Gwood88** [trustedsec/social-engineer-toolkit#342]
when i try to send the message i am getting you dont have python requests installed but i have done apt-get install python-requests and im still having the issue.. I saw another thread with the same issue but I couldnt understand their fix//Can anyone help me out//step by step

**Comment by trustedsec** [comment]
This is usually due to an invalid python-requests install. You can test this yourself by making a file and type import requests.

I've added some additional logging though to hopefully help you out in the future.
