### ISSUE TITLE
Gmail.com Phising attack doesn't return the post data.

### ISSUE THREAD

**Issue by 0xyg3n** [trustedsec/social-engineer-toolkit#343]
hello , 
i always liked the work you did guys i tested the tool and i used the phising attack , i tried to clone gmail.com , it works , but the post data doesn't return the output , like email password , it doesn't return anything actually.
I saw the source code which was located to /var/www/html/index.html it looks right but it seems it doesn't work. :)

**Comment by hannay1** [comment]
I too have this same problem after updating to SET version 7.4.3 yesterday. SET was working (showing POST requests) before this.
When I attempt to update SET configuration from the main menu, SET reports:
Update failed? Timestamp on config file is: 2016-12-15 14:55:03.959230
apache2 seems to be updated and working.

**Comment by 0xyg3n** [comment]
Well i tried to work arround with some other websites , facebook and twitter works like a charm :D

**Comment by hannay1** [comment]
That's odd,  Facebook (or any other site) does not work for me. 
May I please ask for the output of ". /setup.py install" in your /usr/share/setoolkit directory? So I can know the versions of your relevant packages? Thank you

**Comment by canrosss** [comment]
I have similar problem, can you share your solution?

**Comment by canrosss** [comment]
If i go directly to the post.php i get 
('Array\n',)
('(\n',)
(')\n',)

An empty array, i think is some between the form and the post.php i have to fix the code :(

**Comment by hannay1** [comment]
I fixed my issue, my particular issue was solved like this:

1. disable php5 for apache2: sudo a2dismod php5
2. enable php7: sudo a2enmod php7.0
