### ISSUE TITLE
Clone Site Gmail wont work

### ISSUE THREAD

**Issue by whoiskali** [trustedsec/social-engineer-toolkit#348]
Facebook is working but when I try gmail it doesnt harvest anything :( Please help

**Comment by bennelson1234** [comment]
Can confirm cloning of Gmail/Google Accounts login portal doesn't return the HTTP POST data for me either (cloned: https://accounts.google.com/ServiceLogin#identifier).
Can confirm cloned https://www.facebook.com works correctly and the correct POST data is received.

I have tried the fix suggested from a similar previously closed issue #343 (https://github.com/trustedsec/social-engineer-toolkit/issues/343), but this has not resolved the issue.

@whoiskali Could you try the suggested fix from closed issue #343 and report back?

**Comment by ph0t0n1c** [comment]
I can confirm I'm having this same issue as @whoiskali  and have tried fix from  #343  to no avail.

**Comment by trustedsec** [comment]
Give it a shot now. Released in 7.5.
