### ISSUE TITLE
SET

### ISSUE THREAD

**Issue by AleOrcia** [trustedsec/social-engineer-toolkit#350]
I'm new
When I start SET it say that I have an old version. When I press 4 for the update, it say that I'm running Kali Linux which maintains SET update.
Sorry for my English. Please reply soon. Thanks in advance!

**Comment by mikecjudge** [comment]
Kali includes SET in its own repositories so will often be slightly behind the official version.
As there maybe other dependencies on libraries etc that SET requires which may restrict upgrading to the latest version.
Have you tried upgrading the Kali distribution using 'dist-upgrade' ?

**Comment by mikecjudge** [comment]
Sorry should have been 'apt-get dist-upgrade'

**Comment by AleOrcia** [comment]
Thanks for the help but I upgraded SET with PTF ;-)
Bye
