### ISSUE TITLE
Update for fasttrack wordlist.txt

### ISSUE THREAD

**Issue by Green-Wolf** [trustedsec/social-engineer-toolkit#351]
Hi,

The fasttrack wordlist ends up being used by lots of people using kali linux. Its got a little section of it where the words are <season><year> but it is a bit dated now. I updated the wordlist for myself and thought it would be helpful to update the main one.

[fasttrack.txt](https://github.com/trustedsec/social-engineer-toolkit/files/698569/fasttrack.txt)

Here is the new part(Just to change the year to the last 5 instead of 2008-2013):
Spring2017
Spring2016
Spring2015
Spring2014
Spring2013
spring2017
spring2016
spring2015
spring2014
spring2013
Summer2017
Summer2016
Summer2015
Summer2014
Summer2013
summer2017
summer2016
summer2015
summer2014
summer2013
Autumn2017
Autumn2016
Autumn2015
Autumn2014
Autumn2013
autumn2017
autumn2016
autumn2015
autumn2014
autumn2013
Winter2017
Winter2016
Winter2015
Winter2014
Winter2013
winter2017
winter2016
winter2015
winter2014
winter2013

**Comment by trustedsec** [comment]
Great suggestion - updated the wordlist, thanks!

**Comment by rusti4** [comment]
> Great suggestion - updated the wordlist, thanks!

Hi, I feel this is now outdated again being 2022? Should the wordlist be updated again?
