### ISSUE TITLE
SyntaxError: invalid syntax in src/teensy/binary2teensy.py

### ISSUE THREAD

**Issue by sbrun** [trustedsec/social-engineer-toolkit#352]
Hello,
When trying to update the Kali Linux package to the latest release, I got a error message:
```
File "/usr/share/set/src/teensy/binary2teensy.py", line 110
    ********************************************************************
     ^
SyntaxError: invalid syntax
```

Many lines of code have been inserted into a print command in this commit:
https://github.com/trustedsec/social-engineer-toolkit/commit/e629d658c05776d8e1424d4a4e797725d5beeae9

**Comment by JacobVegas** [comment]
In Python 3 **print** is a function not a statement attched is the updated code valid for Python 3.   The file type  to .txt in this port as  it will not accept .py  files.
[binary2teensy.txt](https://github.com/trustedsec/social-engineer-toolkit/files/713383/binary2teensy.txt)

**Comment by sbrun** [comment]
Thanks for the new code.
But in commit e629d65 the code was inserted into the old code and I think the new code should have completely replaced the old code. We find the same code twice in the file (for example: #!/usr/bin/python and the import lines).

**Comment by mikecjudge** [comment]
Pull request #354 submitted to correct copy paste error in binary2teensy.py
Thanks for highlighting the error and apologies for any confusion.

**Comment by trustedsec** [comment]
Thanks for the fix, all set.
