### ISSUE TITLE
SMS-spoofing

### ISSUE THREAD

**Issue by matthewsmith665** [trustedsec/social-engineer-toolkit#353]
This has been driving me crazy! I've been trying to use the sms-spoofing tool, and at first I kept getting something about installing python requests. I did all that but it still kept popping up right after the part where it prompts you to type in the text you want to put in the message. So I updated everything with PTF, everything went smoothly and then... at the same exact spot it's now saying "[!] Something went wrong, printing the error: name 'print_error' is not defined" ... I signed up on spoofmytextmessages.com and got the codes and all that. You can spoof them directly from their app, but I want to do it from the terminal! Just more fun that way. I guess I'll take a look at the code, but I'm pretty sure this is way beyond my coding abilities. Anyway, if anybody else has any ideas or info, let me know.

**Comment by matthewsmith665** [comment]
Using my extremely limited debugging skills, I think the error i'm getting is occuring at the very end of execution in "sms.py" ... i see some commenting about only using SMSGang... i got my codes from spoofmytextmessage.com. i don't believe i'm ever reaching "spoofapi.py" where most of the communication with spoofmytextmessage.com occurs. i could do more but i don't have anywhere near an advanced knowledge of python. at the very bottom of sms.py is the error function, the error is outputted in my terminal, but it's like an error within an error, it can't tell me the error because the function print_error is not defined... i could be way off track here not sure. it would be a great exercise for me to try to fix, if i'm even close at all and someone could guide me a little.

**Comment by trustedsec** [comment]
Before I start to debug this - just wanted to confirm you are using the latest version of SET?

**Comment by matthewsmith665** [comment]
I just double-checked, I'm using 7.4.5 ... I just tried it again, after I put the country codes and set the phone numbers (with country codes again, so it asks for country codes twice, not sure if that was intended design or not) and I still got this:
[!] Something went wrong, printing the error: name 'print_error' is not defined
That happens right when I hit enter after typing in what i want the message to say.
The spoofing works when I do it from the spoofmytextmessage.com website,
just can't get it to happen with SET.

**Comment by nicksedz** [comment]
@matthewsmith665 Having the same issue. Ill let you know if I can solve this.

**Comment by dmcxbluecoder** [comment]
Same problem here, the moment i finish my sms it says :  'Something went wrong, printing the error: name 'print_error' is not defined' hope it can get solved, Thanks for the great tool

**Comment by trustedsec** [comment]
This should be resolved, not sure why it would happen (and doesn't on mine) but I import differently now so this shouldn't be an issue in 7.5 which was just released..

**Comment by matthewsmith665** [comment]
@trustedsec Awesome, thank you and thank you for the time you guys put into this, it has really inspired me to get into security.

**Comment by nicksedz** [comment]
@trustedsec ^ What he said! Thanks!

**Comment by matthewsmith665** [comment]
@nicksedz it's working great for me now,  even automatically inputs your purchased codes so you don't have to mess with that. Occasionally the spoofing doesn't work, like it will just be some random number instead of the # u wanted it to be from. But that's  "spoofmytextmessage.com"'s fault, it doesn't have anything to do with the SET source code.

**Comment by nicksedz** [comment]
@matthewsmith665 glad to hear you got it going. did you just update SET?

**Comment by nicksedz** [comment]
Anyone here get their messages sent from a different number then the one you put it? Im exploring what the route numbers do but not sure. thanks!

**Comment by cyk-psych** [comment]
it says  This module is currently disabled as spoofmytextmessage.com is currently experiencing issues. As soon as it is working again or I can rework the module, this will remain disabled.
