### ISSUE TITLE
Print_Error for SMS Spoofing Attack

### ISSUE THREAD

**Issue by nicksedz** [trustedsec/social-engineer-toolkit#356]
Hey all,

Im trying to run a SMS Spoof, and has a setoolkit error with a python file, but fixed that, and now I get a "print_error" after inputting the phone number and message.

Anything help would be amazing! Thanks!

**Comment by trustedsec** [comment]
It would appear your using an old version of SET - can you confirm which version?

**Comment by nicksedz** [comment]
Thanks for your comment. I will check when I get home. I believe 7.4.5. I was on an older version prior, and had a python file error and believe I updated to 7.4.5 correctly. Which is why im surprised im getting this print error. But will check when i get home. Thanks!

**Comment by trustedsec** [comment]
Please note that this module is getting disabled for now in the next release. Spoofmytextmessages is having issues with the routes. I'm working with the dev to hopefully resolve.

**Comment by nicksedz** [comment]
ok, do you have an alternative recommendation for sms spoofing?

**Comment by trustedsec** [comment]
Give it a shot with the latest release, I added routes which should help. Also should have addressed any of the print errors which are weird.
