### ISSUE TITLE
SMS spoofing route selection

### ISSUE THREAD

**Issue by eskim86** [trustedsec/social-engineer-toolkit#358]
Hi, 

I would like to thank you for all your effort on making this amazing tool.

I have tested SMS spoofing and noticed that your source code does not suppot the SMS spoof route changing functionality provided by the website, so I was wondering whether you could walk me through on how to use source code to apply this functionality?

The reason behind this request is that the phone numbers I am trying to use can receive text messages using different spoof routes, such as SMS SPOOF Route1 or 2.

Thanks in advance,

Eunsoo Kim

**Comment by trustedsec** [comment]
Added to 7.5. Enjoy!

**Comment by eskim86** [comment]
Hello,

I was going to tell you that I had managed to get the parameter for the
payload for injecting the spoofing route using Burp Suite, however, I thank
you for all your effort in reflecting my request on your latest version of
the toolkit.

Best regards,

Eunsoo Kim

2017-02-07 1:32 GMT+09:00 trustedsec <notifications@github.com>:

**Comment by devrajashwin** [comment]
does the  10) SMS Spoofing Attack Vector is working ,
if yes plz tell me ,
because when i use the this attack it takes me back to the main options............
i kindly request u to plz help me out for the situations............
THANKS...............................(its great tool to came back for kail rollinng)

**Comment by eskim86** [comment]
For me it works fine.

Are you using the latest bersion of the tool?

The reason wht i am tellimg you this is because the prevous version had a
different name for the api it is calling. The proper name should be
spoofapi as you can guess from the .py files in the sms folder.

I had the similar experience as you are having right now, so please check
in the source code whethe the right name of the api is called. Otherwise, i
would require more information such as your environment settings and error
messages.

Regards,

Eunsoo
2017년 2월 19일 (일) 오전 12:18, devrajashwin <notifications@github.com>님이 작성:

**Comment by devrajashwin** [comment]
yes sir iam running the latest verion eskim86

**Comment by eskim86** [comment]
Hm.. if that is the case..

Try running the sms.py from the cloned folder instead of using setoolkit
dirtectly coming fromthe usr/sharedsetoolkit

If you had cloned the setoolkit, it will be some where in your
home/(usr)/setoolkit/src/sms.py

Have you check the source code?

Without more information, there isnt much i can do for you.

Regards,

Eunsoo.



2017년 2월 19일 (일) 오후 8:43, devrajashwin <notifications@github.com>님이 작성:
