### ISSUE TITLE
Setoolkit doesn't use the apache folder

### ISSUE THREAD

**Issue by PandoraSec** [trustedsec/social-engineer-toolkit#359]
the set isn't using the usual folder to keep the index, how can i modyfy various index if this is happening?
greetings =), (i use kali linux rolling, full update)
![screenshot from 2017-02-08 17-12-14](https://cloud.githubusercontent.com/assets/22203976/22763450/ffb87048-ee21-11e6-8d5c-c859c3dfd482.png)

**Comment by saintdrug** [comment]
type locate set.config
nano the location u found, set.config

edit the location var/apache/html or link it to "html"

and thats the place where everything is stored with apache
