### ISSUE TITLE
Metasploit Path Revisited

### ISSUE THREAD

**Issue by H011YxW00D** [trustedsec/social-engineer-toolkit#360]
See issue #315. This is still a problem and should not have been closed.

So in setcore.py starting on line 313 there are hard coded entries that is SET is searching for for MSF. Since I am using Kubuntu Linux as well as the binary installed version from rapid 7 I edited the backbox entry to look like this:

if os.path.isfile("/opt/metasploit-framework/app/msfconsole"):
msf_path = "/opt/metasploit-framework/"
trigger = 1

Then I edited my set.config to point to /opt/metasploit-framework and it fired up without issue. Like others have said it seems to just want to know where the msfconsole binary is. I also experimented with copying the msfconsole link under /opt/metasploit-framework/app to /opt/metasploit-framework/ and that worked as well.

**Comment by trustedsec** [comment]
Yeah, it should have been closed as putting it in the config worked perfectly fine. There would be cases where if Metasploit was installed in two locations or two paths with msfconsole, it would override the config as the config option is checked last only if trigger was still set to 0. I've changed this in the latest version as it's a possible edge case that could happen. But issue #315 was properly closed as it was addressed.

**Comment by H011YxW00D** [comment]
(Not trying to be a troll) So are you saying that the set.config would only be read if the hard-coded values (triggers) in the setcore.py were set to zero? Sorry Just trying to understand how it works cuz I spent like an hour trying to get it working LOL and I saw that others were still having similar problems if they had installed MSF from the Rapid7 binary.
