### ISSUE TITLE
Can't find msf4 directory

### ISSUE THREAD

**Issue by MelonMania** [trustedsec/social-engineer-toolkit#362]
[!] Please exit out of SET and type 'msfconsole' from the command prompt and launch SET again. Can't find the msf4 directory. 
I was given this error. so i type msfconsole in terminal
but this error is kept going
i don't know which is the problem(metasploit or social-engineer-toolkit)
how can i do?

ps. . : sorry for my English

**Comment by trustedsec** [comment]
Need to make sure Metasploit is installed. This also looks like a very old version of SET. I would recommend updating to the latest.

**Comment by loks10** [comment]
> Need to make sure Metasploit is installed. This also looks like a very old version of SET. I would recommend updating to the latest.

How to update?
