### ISSUE TITLE
site cloner works, but /var/www/html looks empty

### ISSUE THREAD

**Issue by kraniasorestis** [trustedsec/social-engineer-toolkit#364]
After googling, I have found nothing on this one: I'm trying to clone a site (say facebook) and indeed, apache2 runs the cloned site, and even the harvested credentials appear *within* the terminal in which SET is running.

BUT, the directory /var/www/html looks empty. Nothing at all inside. It used to be the case that a few months ago, when I last used SET, everything was working perfectly, but now this. I have always been running SET on kali and currently am in kali 2.0 rolling. 

Were the files moved to a different directory for some reason? Are they there but kali doesn't actually see them? I mean they *have* to be somewhere since the whole site-cloning attack is working. 

I need to locate the php script to manipulate the redirection site for a more effective social engineering attack.

**Comment by mosoltan** [comment]
@ahmedkamal00

**Comment by trustedsec** [comment]
This is due to SET having APACHE_SERVER=OFF which uses the builtin default webserver. If you want to keep them under /var/www/html/ and use Apache instead, edit /etc/setoolkit/set.config and turn APACHE_SERVER to ON.

**Comment by hamzashaukatali** [comment]
you may need to copy /var/www/* into /var/www/html depending on where your directory structure is... I want to resolve this issue while cloning the facebook site... Please answer me
