### ISSUE TITLE
"AttributeError: 'module' object has no attribute 'geteuid' " this massage is showing 

### ISSUE THREAD

**Issue by prime97** [trustedsec/social-engineer-toolkit#365]
setoolkit
[-] New set.config.py file generated on: 2017-02-16 23:26:07.652157
[-] Verifying configuration update...
[*] Update verified, config timestamp is: 2017-02-16 23:26:07.652157
[*] SET is using the new config, no need to restart
Traceback (most recent call last):
  File "./setoolkit", line 144, in <module>
    if os.geteuid() != 0:
AttributeError: 'module' object has no attribute 'geteuid'

this massage i'm getting when i run setoolkit..please help me out...!

**Comment by trustedsec** [comment]
What version of SET are you using? I can't seem to reproduce this one. 

os.geteuid is a valid Python module.  Are you trying to run this on Windows? SET is only designed for Linux.

**Comment by prime97** [comment]
No I'm using 'kali-linux 2.0' . I recently installed it! And whenever I try
to start this tool from terminal , it's showing this error massage! Now
what can i do to overcome this situation?

**Comment by L1ghtn1ng** [comment]
You need to be using Kali rolling, then make sure you have updated your system and then see if you get this error


________________________________

**Comment by trustedsec** [comment]
Dang, you beat me to it.

**Comment by trustedsec** [comment]
Appreciate it :)

**Comment by L1ghtn1ng** [comment]
No problem, expect a pr from me soon to take care of issues like this when it comes to bug reports

________________________________

**Comment by prime97** [comment]
I've updated my system...but still I'm having this problem...!

**Comment by trustedsec** [comment]
I'm highly doubting it. You need to be using Kali rolling.

I have Kali with rolling and this works fine.

**Comment by L1ghtn1ng** [comment]
Please see this
Kali rolling upgrade<https://www.kali.org/news/kali-linux-rolling-edition-2016-1/>

________________________________

**Comment by prime97** [comment]
I'm using kali GNU/Linux Rolling 64-bit

On Feb 22, 2017 8:32 AM, "J.Townsend" <notifications@github.com> wrote:

Please see this
Kali rolling upgrade<https://www.kali.org/news/kali-linux-rolling-
edition-2016-1/>

________________________________

**Comment by trustedsec** [comment]
You messed something up - possibly Python? On Kali Rolling 64bit:

root@kali:~# setoolkit 
[-] New set.config.py file generated on: 2017-02-21 21:40:04.206050
[-] Verifying configuration update...
[*] Update verified, config timestamp is: 2017-02-21 21:40:04.206050
[*] SET is using the new config, no need to restart
[---]        The Social-Engineer Toolkit (SET)         [---]
[---]        Created by: David Kennedy (ReL1K)         [---]
                       Version: 7.5.1
                     Codename: 'Ghost'
[---]        Follow us on Twitter: @TrustedSec         [---]
[---]        Follow me on Twitter: @HackingDave        [---]
[---]       Homepage: https://www.trustedsec.com       [---]

        Welcome to the Social-Engineer Toolkit (SET).
         The one stop shop for all of your SE needs.

     Join us on irc.freenode.net in channel #setoolkit

   The Social-Engineer Toolkit is a product of TrustedSec.

           Visit: https://www.trustedsec.com

   It's easy to update using the PenTesters Framework! (PTF)
Visit https://github.com/trustedsec/ptf to update all your tools!


 Select from the menu:

   1) Social-Engineering Attacks
   2) Penetration Testing (Fast-Track)
   3) Third Party Modules
   4) Update the Social-Engineer Toolkit
   5) Update SET configuration
   6) Help, Credits, and About

  99) Exit the Social-Engineer Toolkit

set>

**Comment by prime97** [comment]
I don't know that even i did something or not...! But i need a solution...
Please help me out of this situation!

**Comment by prime97** [comment]
Do u have no idea about how to help me??
