### ISSUE TITLE
Credential Harvester Attack: Facebook template problem

### ISSUE THREAD

**Issue by D4rkX0** [trustedsec/social-engineer-toolkit#366]
Hi,
i tried to make a facebook clone page but after generating the index file & gone to check how is the clone looks,  i got just the html text with no logo no css, a white page with text only.
i tried with google & works good. the problem is only with facebook

**Comment by trustedsec** [comment]
I would recommend using the site import functionality - you can save facebook through your browser, then instead of using site cloner, use the import. Site cloning isn't a exact science.

**Comment by D4rkX0** [comment]
it's work, thanks.
just a note if u choose the second option ( copy all the content of folder ), it copy just the index file not all the files.
