### ISSUE TITLE
site cloner redirection works only within LAN

### ISSUE THREAD

**Issue by kraniasorestis** [trustedsec/social-engineer-toolkit#367]
As the title suggests, site cloner phishing attack works as expected, as long as the victim is within the local network. 

Now, I have configured the router with the required port forwarding, for the attack to work from the outside, but whenever someone tries to connect to the router through its public ip, while he *does* get forwarded correctly to the phishing site, everything stops the moment he presses the login button,  -> the credentials I enter don't get written to the log file (or presented in the terminal emulator running the SET), and the redirection never happens. The browser seems to just ....enter an endless loading state? what would cause this? I know this used to work in the past without problems.

**Comment by trustedsec** [comment]
Need to ensure that port forwarding is appropriately setup and when you do the clone, when it asks for the IP address you need to put the PUBLIC ip address, not the NATed one.
