### ISSUE TITLE
QR Code error save() got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by XexarCol** [trustedsec/social-engineer-toolkit#368]
Hi, my friend. This error Something went wrong, printing the error: save() got an unexpected keyword argument 'format' is appearing with option 1 and then 8. What would be my problem? Regards

**Comment by trustedsec** [comment]
Do you know what version of SET you are using? Works for me:

set> 8

The QRCode Attack Vector will create a QRCode for you with whatever URL you want.

When you have the QRCode Generated, select an additional attack vector within SET and
deploy the QRCode to your victim. For example, generate a QRCode of the SET Java Applet
and send the QRCode via a mailer.

Enter the URL you want the QRCode to go to (99 to exit): https://www.google.com
[*] QRCode has been generated under /root/.set/reports/qrcode_attack.png

      Press <return> to continue

**Comment by XexarCol** [comment]
Hi
I am running on Linux KaliKali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

There is a new version of SET available.
                     Your version: 7.5
                  Current version: 7.5.1

**Comment by trustedsec** [comment]
Try running python -m pip install qrcode

**Comment by robinmav** [comment]
I this is my problem: 
root@kali:~# "git clone https://github.com/trustedsec/social-engineer-toolkit/ social-engineer-toolkit/" end ok 100% 
root@kali: "ls"
root@kali:~# cd social-engineer-toolkit/
root@kali:~/social-engineer-toolkit# python setup.py install
end Error "libapache2-mod-php5" not version or obsolete 
[!] SET is already installed in /usr/share/setoolkit. Remove and start again 
halp me please (sorry for English) but I'm Italian 

(https://cloud.githubusercontent.com/assets/25972730/23246331/046941ea-f993-11e6-862c-92e50333296f.png)

**Comment by XexarCol** [comment]
trustedsec, the issue is still. 
python -m pip install qrcode
Requirement already satisfied: qrcode in /usr/lib/python2.7/dist-packages
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from qrcode)
The cause could to be the java version or what else?

Regards

Regards
