### ISSUE TITLE
Problems in Java Applet attack vector

### ISSUE THREAD

**Issue by SecurityLover** [trustedsec/social-engineer-toolkit#371]
Hi there,

i've tried Java Applet attack vector many times without success. I can't get the connection back from victim's machine to attacking machine. I used SET 7.5 installed in Kali 2, and XP with Java 6.

I followed exact instructions like Run Java Applet in victim's machine, but i still can't get back sessions in SET interface. Any advices are appreciated, dears??

**Comment by trustedsec** [comment]
I renewed the latest jar, it was expired. Will be introduced into new version, thanks for the report!
