### ISSUE TITLE
It stop and didn't create harvester.txt 

### ISSUE THREAD

**Issue by JieJhih** [trustedsec/social-engineer-toolkit#372]
![root kali _002](https://cloud.githubusercontent.com/assets/25479061/23331722/642d3e96-fba6-11e6-8246-8b52a37ac713.png)

**Comment by kn0wledge** [comment]
Same issue. I think it is created , but in a different location for some reason

**Comment by trustedsec** [comment]
By default SET will use the built in harvester which is Python based. If you are looking for it to be generated and sent to Apache you need to edit /etc/setoolkit/set.config and turn APACHE_SERVER from OFF to ON. This will move things under /var/www/?html?.
