### ISSUE TITLE
cant run airbase-ng in modern systems

### ISSUE THREAD

**Issue by wifislax-ng** [trustedsec/social-engineer-toolkit#374]
Cause the binary is compiled with openssl-0.9.8 , cant run the executable in systems with openssl-1.x

Why setup.py not compile airbase-ng in the system ?
Better than "static" ,executable.
Upgrade the binary airbase-ng with one compiled in openssl-1.x ?

Thanks !

**Comment by trustedsec** [comment]
Thanks for the bug report. I've added the latest version of airbase-ng and will be releasing a new version of SET shortly.
