### ISSUE TITLE
Sms attack python error 

### ISSUE THREAD

**Issue by AhmedGuest** [trustedsec/social-engineer-toolkit#375]
What should I do sir ?!
![received_652185118301952](https://cloud.githubusercontent.com/assets/26166761/23558985/559b3f1c-003e-11e7-804f-e5057d72cdb3.png)

**Comment by L1ghtn1ng** [comment]
Please update your entire system, as you have over 1700 packages that need updating which will more than likely include SET and restart your PC then see if you have the issue.

Sent from phone


________________________________

**Comment by AhmedGuest** [comment]
Thank you sir ... but I don't know how I do that ?! ... sorry I'm bagainer of kali linux

**Comment by L1ghtn1ng** [comment]
Do CTRL+T which will open the terminal, then you want to do run the following command

apt update && apt dist-upgrade -y

Once it returns back to the prompt type reboot then enter then you should have the latest Set version and you should not have this issue after that

Sent from phone


________________________________

**Comment by AhmedGuest** [comment]
I really don't know how to thank you .. I will try and will reply

**Comment by AhmedGuest** [comment]
I done all what you say and kali download all packets but se toolkit don't update :'(

**Comment by AhmedGuest** [comment]
It's solved ... thank you for your help ... but is it necessary to buy account in spoofmytextmessage.com to do set sms attack ?!

**Comment by L1ghtn1ng** [comment]
Yes as it uses there APIs

Sent from phone


________________________________
