### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by jsampson80** [trustedsec/social-engineer-toolkit#380]
I got bored and started putting SET on an old JB iPhone 4S after a lot of googling errors  and ending up at old threads which don't help. I got an SSL error which I used "GIT_SSL_NO_VERIFY=true git clone"to finally get it to download. Now when I try and install I getting a syntax error. 

File "setup.py", line 10
    with open(os.path.join(os.path.dirname(__file__),
'pexpect' ,

**Comment by jsampson80** [comment]
Sorry hit publish by accident error below

File "setup.py", line 10
    with open(os.path.join(os.path.dirname(__file__), 'pexpect', '__init__.py'), 'r') as f:
                 ^
SyntaxError: invalid syntax

**Comment by pavlukivan** [comment]
Your Python, Setoolkit, OS version?

**Comment by jsampson80** [comment]
I was running python 2.5/the latest version of setoolkit from github/ iOS 8.4

I thought maybe it was my python so I updated it to 2.7 then I got this error.

"bad cpu type in executable" so I'm assuming I having an issue because the 4s is only a 32bit?

**Comment by pavlukivan** [comment]
4s is arm, i guess, so it won't support x86 python. Use appropriate python version, i guess you can use https://github.com/pybee/Python-Apple-support
