### ISSUE TITLE
SET SMS SPOOF

### ISSUE THREAD

**Issue by Rieskone** [trustedsec/social-engineer-toolkit#381]
in kali linux, sms spoofing attack vector says me "Spoofmytextmessages.com no longer works and spoof messages. until this is fixed, this module is disabled." what i have to do for this module works? or i have to wait trustedsec fix it?

**Comment by aneopsy** [comment]
Sms spoof is no longer available.

**Comment by Axmedjees** [comment]
HOW TO FIX THIS ISSUE MY BRO
