### ISSUE TITLE
name 'print_status' is not defined

### ISSUE THREAD

**Issue by bigmouthstrks** [trustedsec/social-engineer-toolkit#382]
# Hello everyone im new at GitHub and kind of new using 'SET'.
Anyway, SET gives me this error: 
**_Python OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.
[!] Something went wrong, printing the error: name 'print_status' is not defined_**

IAbout my operating system specs: 

Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
I'm running XFCE desktop enviroment.
And i can't understand it, i have searched but i couldn't find an answer, please help a newbie, thanks.

![set](https://cloud.githubusercontent.com/assets/26700995/24339112/27344782-1280-11e7-8d67-73ed80edcfe4.png)

**Comment by trustedsec** [comment]
What version of SET are you using?

**Comment by pavlukivan** [comment]
Well, maybe its a dump question, but have you installed pyssl?

**Comment by lawliet-29** [comment]
i have the same thing, help me plz..!

**Comment by projectFRiNK** [comment]
Same issue here. I am using SET 7.6 on Kali Linux, I just installed it today. :(

**Comment by trustedsec** [comment]
You could have fixed this by installing pyopenssl, but it still is a bug. I've fixed this in 7.6.2 should be released shortly. Thanks for the report!
