### ISSUE TITLE
index.html and php.txt not showing up on var/www

### ISSUE THREAD

**Issue by math400** [trustedsec/social-engineer-toolkit#385]
Hi am running setoolkit 7.6 on Kali linux Rolling (Updated), After clowning site there is not files create on 
VAR/WWW
Please help resolve issue .
thanks

**Comment by Rajmeet** [comment]
I am also having this problem please help

**Comment by math400** [comment]
A working i find INDEX.html in SET directory  Root/.set//index.html

**Comment by necony286** [comment]
yea i have the same problem but when i find it it there and copy it over it still dosent work
