### ISSUE TITLE
Credential harvesator not working

### ISSUE THREAD

**Issue by iamalsaher** [trustedsec/social-engineer-toolkit#391]
Whenever I try to run credential harvester on the following websites, few errors come up. 

1. https://www.instagram.com (I see the name and favicon of the website but other than that the page is completely blank.)
2. https://www.inbox.google.com (I enter my username and the website seems to freeze. Apparently it return the information after that and says password field might be empty, whereas as you know the page to input password is still to come)

Can you suggest something

**Comment by SecurityLover** [comment]
Also I have problems in Credential Harvester Attack and Web Jacking Attack. They CAN NOT LOG victims IN the legitimate website (facebook, yahoo, or gmail).  They only redirect them to default web page without logging in. 

Any suggests?

**Comment by trustedsec** [comment]
You can save page as for these and then import them into the web harvester. There's an "import" function.
