### ISSUE TITLE
Payload Generation Issue

### ISSUE THREAD

**Issue by rsas503** [trustedsec/social-engineer-toolkit#392]
After creating a payload it is stored in /root/.set//payload.exe. However the generated payload is not found there. I think the reason is adding two // after .set directory. So how can I fix this issue?

**Comment by mikecjudge** [comment]
Which option did you select before you received this ?

**Comment by rsas503** [comment]
I chose the option no. 4.

**Comment by mikecjudge** [comment]
I can see where this is happening in the code and will make some changes to see if i can resolve this.

BTW - When i tested this on SET 7.6 in the rolling Kali distribution i found the payload, listener details in the /root/.set folder
