### ISSUE TITLE
program.exe does not work for Windows 10 (x64/64 bits)

### ISSUE THREAD

**Issue by SecurityLover** [trustedsec/social-engineer-toolkit#393]
Hello dears,

I tried to perform Infectious Media Generator Attack on Windows 10 (x64/64 bits), and it failed. It worked well only on Windows_x32 (32 bits)

Any suggest?

**Comment by kr4b4t** [comment]
Which payload did you use?

**Comment by trustedsec** [comment]
Please refer to kr4b4t on this one - all should work on that front.
