### ISSUE TITLE
when i use SET in MAC OSX ,here is a problem 

### ISSUE THREAD

**Issue by JcQSteven** [trustedsec/social-engineer-toolkit#394]
when i use command tools.
sudo python setoolkit
the report is following:
Traceback (most recent call last):
  File "/Users/steven/Downloads/social-engineer-toolkit-master/setoolkit", line 35, in <module>
    shutil.copyfile("src/core/config.baseline", "/etc/setoolkit/set.config")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'src/core/config.baseline'

**Comment by JcQSteven** [comment]
i 've run setup.py before

**Comment by ryman1** [comment]
I can reproduce a similar error when calling set from outside the "social-engineer-toolkit" folder. Do you have this problem if you do `sudo ./setoolkit` directly in the SET folder?

**Comment by JcQSteven** [comment]
Thanks a lot.@ryman1

**Comment by JcQSteven** [comment]
But What's the reason @ryman1

**Comment by JcQSteven** [comment]
Else,the report when i open  [!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.

**Comment by trustedsec** [comment]
The reason is because SET looks for src folder for launching SET. On the second one, you need to edit what it says - install Metasploit, and edit the set.config to point it to the msfconsole home folder.
