### ISSUE TITLE
Nexus 5x Nethunter: Setoolkit 7.6.1 - OpenSSL Error

### ISSUE THREAD

**Issue by maslovicz** [trustedsec/social-engineer-toolkit#395]
Hello,

My system is updated and when i install setoolkit with apt-get install set
On Harvester i have this error:
![screenshot_20170415-132726](https://cloud.githubusercontent.com/assets/9488878/25063259/c0f5e916-21df-11e7-9974-e57f61a0eb7f.png)

Android 7.1.2 Stock - TWRP Latest - SuperSU latest

Python-OpenSSL is installed. It's happening on HTTP and on HTTPS.

**Comment by trustedsec** [comment]
Something is messed up with Python-OpenSSL - you can test it by editing a new file and doing:

from OpenSSL import SSL
