### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by pnikolaidis** [trustedsec/social-engineer-toolkit#396]
**Expected Behaviour**

The word "you're" should appear as a contraction of "you are" in sentences. 

**Actual Behaviour**

Throughout the documentation, the word "your" appears instead. Examples:
* "_If your using BackTrack 4_" (pg. 4)
* "_Say your targeting CompanyX..._" (pg. 5)
* "_# IF YOUR USING THIS FLAG_" (pg. 6)

**Set Version**

SET User Manual  Made for SET 6.0

**Comment by trustedsec** [comment]
Feel free to submit a PR :)
