### ISSUE TITLE
Printing error: zipimporter() argument 1 must be string, not function

### ISSUE THREAD

**Issue by Mslap** [trustedsec/social-engineer-toolkit#398]
When i try to clone site , after entering my local IP and URL to clone i get error " Printing error: zipimporter() argument 1 must be string, not function "  my SET version is 7.6.1. I use Kali Linux 2 (Live) but in VMbox is the same error. I didn't find solution in closed issues so i make new.

**Comment by Jupi1989** [comment]
Complete error is : 
Python OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.
[*] Printing error: zipimporter() argument 1 must be string, not function

This is a not new bug. check other issue, he close but no solution for the moment

**Comment by Eyegabry99** [comment]
same error can someone help us pls? 
Python OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.
[*] Printing error: zipimporter() argument 1 must be string, not function

**Comment by trustedsec** [comment]
Something is messed up with the Python OpenSSL module for you. Works great on Ubuntu. It shouldn't affect your stuff if you aren't using SSL.  That's out of my control sorry since Python OpenSSL is a python package.

**Comment by sh4dyrul3zz** [comment]
/etc/setoolkit/set.config
line 95 
APACHE_SERVER=OFF
change to
APACHE_SERVER=ON

**Comment by alansenairj** [comment]
/etc/setoolkit/set.config
line 95
APACHE_SERVER=OFF
change to
APACHE_SERVER=ON

not working

**Comment by kainDirectoy** [comment]
@alansenairj 

Im sorry for you but for me is working.
I did with vim.

@sh4dyrul3zz  thanks you!

**Comment by giovane2003** [comment]
the error still exisits, anyone knows how to fix it ?

**Comment by carlosvega** [comment]
Any news on this?
