### ISSUE TITLE
Metasploit Path Not Found After Update

### ISSUE THREAD

**Issue by Astrades** [trustedsec/social-engineer-toolkit#399]
SET should be starting smoothly and running fine on startup of the script. However, whenever I start SET, it gives me the error below:

[!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.

The current path for the metasploit folder itself is /opt/metasploit. I recently updated/upgraded my copy of metasploit and the folder was renamed. Now, the path is all messed up and I'm not sure what to update the set.config metasploit path to. My current path in the config file is:

METASPLOIT_PATH=/opt/metasploit/apps/pro/msf3

(Btw, I'm running Ubuntu 16.04)

What can I do to fix this? Thanks for reading!

**Comment by trustedsec** [comment]
What version of SET are you using? It also needs to be where msfconsole is located... Just tested on 16.04 and appears to be working fine where installed...

**Comment by Astrades** [comment]
I'm using the latest version. However, I was being lazy and didn't try to
reinstall it yet. So, I'll try that right now. Sorry for the false issue.
