### ISSUE TITLE
Website blank

### ISSUE THREAD

**Issue by Bubbatron** [trustedsec/social-engineer-toolkit#401]
Hey, I'm using Parrot (fully up to date) and am trying to use SET. When I finish everything (without errors) i try to go on to the website by inputting my local ip. When it loads, it's just a blank screen however the tab is correctly named. I have tried site cloner and loading an html file.

**Comment by Bubbatron** [comment]
Okay, have been trying with Instagram and thought I could give FB a go, that works 100% fine. Not sure as Instagram is really what I need.

**Comment by Usr138214** [comment]
I have the same problem. Only, instagram has only worked once every time I reinstall my os... This time, it didn't and I want to find a solution. Like you, I tried facebook and worked perfectly... Maybe Instagram probably just doesn't work with setoolkit which kind of sucks...

**Comment by shalithavidanapathirana** [comment]
hey Usr138214 , Can I ask u a question?
You say that "I tried facebook and worked perfectly" and Is it worked in outside of your network(LAN)?

**Comment by shalithavidanapathirana** [comment]
Sir, I've got 2 bugs in SET 7.6.1 when I just updated to it
before I update Credential harvester old version worked perfectly. I've done same thing with new update but when I log into my local IP (Fake facebook login) credential harvester said that it got a hit before i enter username and password. i checed it out with the report there got nothing (PARAM: __user=0)

**Comment by trustedsec** [comment]
Sometimes cloning isn't a 100% - you can save the Instagram one as a page (file save as) and rewrite it to have the appropriate parameters then use the import method for harvester.

**Comment by Bubbatron** [comment]
You didn't solve my problem, i have no issue with parameters. You answered the guy who hijacked my post tf.

**Comment by shalithavidanapathirana** [comment]
haha I don't wanna hijack you buddy. I got it my own. don't mind

**Comment by Usr138214** [comment]
Well, how can we rewrite the page so the credentials come back to us? Any links or refrence?

**Comment by debianlu** [comment]
So cloning can't be used with instagram?
