### ISSUE TITLE
Clone Website problem

### ISSUE THREAD

**Issue by gashonie** [trustedsec/social-engineer-toolkit#403]
Python OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.

After my trying to clone website, what is solution ? Fresh install of Kali Linux and update, upgrade.

**Comment by waterlife21** [comment]
i have same issue..
How to fix it... Please help

**Comment by Bubbatron** [comment]
Have this too ^^

**Comment by sieunhando** [comment]
I have this too, this error in kali linux version 2017.1. I tried some method but couldn't fix it.
![image](https://cloud.githubusercontent.com/assets/25194841/25609395/460f3640-2f49-11e7-9a7d-9b4fdc6d4634.png)

**Comment by Eyegabry99** [comment]
same error need help

**Comment by arismelachroinos** [comment]
me too

**Comment by flipup556** [comment]
Me too !

**Comment by trustedsec** [comment]
This is just a warning when using SSL, I've suppressed the warning in a new release. Will be releasing shortly.
