### ISSUE TITLE
cant update to 7.6.2

### ISSUE THREAD

**Issue by gearcapitan** [trustedsec/social-engineer-toolkit#404]
set version
7.6.1
I tried to download again with git clone and manually install and nothing, also delete all file and set folder and reinstall with apt-get and still I continue with version 7.6.1
![kali linux-2017-04-30-21-59-43](https://cloud.githubusercontent.com/assets/13740942/25570997/557a548e-2df0-11e7-9ba4-903d4698bfe9.png)

**Comment by trustedsec** [comment]
You are most likely launching SET from the launcher located under either /usr/bin/ or /usr/local/bin setoolkit. You'll need to go into the directory and hit ./setoolkit or delete the setoolkit launcher.
