### ISSUE TITLE
Credential Harvester Posting to Local IP instead of Public IP

### ISSUE THREAD

**Issue by c15zb1** [trustedsec/social-engineer-toolkit#405]
When I run the credential harvester, input credentials, and hit submit to trigger a post request, the browser I do it from redirects me to the local IP that the harvester is running on, and obviously, as it is not on LAN, can't find that page.

So I see the initial get request, but the post request does not come through.

**Comment by trustedsec** [comment]
You need to set your NAT address to your external IP address when it asks what to post to. This is clear if you read the instructions :)
