### ISSUE TITLE
Exception happened during processing of request from ('127.0.0.1', 48268)

### ISSUE THREAD

**Issue by darkcyber** [trustedsec/social-engineer-toolkit#406]
**Expected Behaviour**

It's show credential.

**Actual Behaviour**

```
127.0.0.1 - - [07/May/2017 17:45:10] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 48268)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/share/setoolkit/src/webattack/harvester/harvester.py", line 311, in do_POST
    filewrite3 = open("%s/src/logs/harvester.log" % os.getcwd(), "w")
IOError: [Errno 2] No such file or directory: '/usr/share/setoolkit/src/logs/harvester.log'
----------------------------------------
```

**Set Version**

7.6.2

**Similar Issue**

https://github.com/trustedsec/social-engineer-toolkit/issues/173

It's say patched. But don't know why I got this.

I clone https:// website, It open normally in localhost.
I input credential, and click Login

And I got this URL 

`/authentication.do;jsessionid=mnR3ZT1b74kJ2ZnbLnvghGdYBq9SjnqQpQ38wxtFgcXGhR22s2zT!-487057767`

With message in chrome

```
This page isn’t working

localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

How to solve this issue?

Thanks in Advance.

**Comment by darkcyber** [comment]
The fix is to create `harvester.log` file in /usr/share/setoolkit/src/logs as Error hint `IOError: [Errno 2] No such file or directory: '/usr/share/setoolkit/src/logs/harvester.log'`

Is this some bug?

**Comment by trustedsec** [comment]
Fixed in 2.7.3 thanks!

**Comment by iSung951** [comment]
I'm having same problem for by using the icloud unlock tool iOS13

**Comment by Innotechugb** [comment]
> I'm having same problem for by using the icloud unlock tool iOS13

tengo el mismo error

**Comment by osirisgenius** [comment]
still happening on version 8.0.1
