### ISSUE TITLE
something went wrong printing the error no module named pexpect

### ISSUE THREAD

**Issue by Preeqo** [trustedsec/social-engineer-toolkit#408]
I've been looking for a solution for a couple of hours now and i cant find a find to help fix this error, every thing i've come across has not worked
this is what it says "something went wrong, printing the error no module named pexpect"
if anyone knows how to fix this please let me know
![something went wrong](https://cloud.githubusercontent.com/assets/28513012/25784357/571e1ea6-3363-11e7-842d-498874d1f73b.PNG)

**Comment by trustedsec** [comment]
pip install pexpect or apt-get install python-pexpect.

**Comment by Preeqo** [comment]
i have tried it but it still says it and it also says this at the top dont know if that is the problem aha
![it also says this](https://cloud.githubusercontent.com/assets/28513012/26064669/8fbf5d5c-3989-11e7-9d64-cd80ac31d9fb.PNG)

**Comment by Jubail** [comment]
i am having the same problem...
i did tried installing using apt-get install python-pexpect...however same error mesg...

**Comment by Preeqo** [comment]
yeah

**Comment by coolneb** [comment]
same
