### ISSUE TITLE
The Python-Pycrypto Python Module not installed 

### ISSUE THREAD

**Issue by Preeqo** [trustedsec/social-engineer-toolkit#410]
![it also says this](https://cloud.githubusercontent.com/assets/28513012/26071085/cff28876-399e-11e7-9eeb-05dc7607b449.PNG)

i think this problem is preventing me from using setoolkit and it is saying 'something went wrong printing the error no module named pexpect'  and i do not know what to do, i've typed it up but i cant find a solution, does anyone know how to install it, if so let me know please 
also this doesn't work as well 'pip install pexpect or apt-get install python-pexpect', to help out the situation   
![something went wrong](https://cloud.githubusercontent.com/assets/28513012/26071208/31dee084-399f-11e7-9941-10f6e19c7475.PNG)

**Comment by trustedsec** [comment]
pip install pexpect

**Comment by Preeqo** [comment]
it didn't work

**Comment by chicconumber1** [comment]
type commands:

apt-get install python-pip
pip install pexpect

**Comment by codeSmart2307** [comment]
Has anyone else solved this issue?

**Comment by singhmayank9560** [comment]
> apt-get install python-pip

i am getting the error for this "unable to locate the package"

**Comment by chicconumber1** [comment]
> > apt-get install python-pip
> 
> i am getting the error for this "unable to locate the package"

try to do this let me know if it works:

`sudo apt-get update && sudo apt-get install python-pip`

if not, python-pip should be in the universe repositories so:

`sudo apt-get install software-properties-common
sudo apt-add-repository universe
sudo apt-get update
sudo apt-get install python-pip`

https://askubuntu.com/a/672836

**Comment by singhmayank9560** [comment]
> > > apt-get install python-pip
> > 
> > 
> > i am getting the error for this "unable to locate the package"
> 
> try to do this let me know if it works:
> 
> `sudo apt-get update && sudo apt-get install python-pip`
> 
> if not, python-pip should be in the universe repositories so:
> 
> `sudo apt-get install software-properties-common`
> `sudo apt-add-repository universe`
> `sudo apt-get update`
> `sudo apt-get install python-pip`
> 
> https://askubuntu.com/a/672836

f-helper.socket.
Setting up packagekit-tools (1.1.13-2+b1) ...
Processing triggers for libc-bin (2.30-4) ...
Processing triggers for systemd (245.4-3) ...
Processing triggers for mime-support (3.64) ...
Processing triggers for dbus (1.12.16-2) ...
root@localhost:~# apt-add-repository universe
Error: 'universe' invalid
root@localhost:~#

**Comment by singhmayank9560** [comment]
I got this error

**Comment by singhmayank9560** [comment]
> > > apt-get install python-pip
> > 
> > 
> > i am getting the error for this "unable to locate the package"
> 
> try to do this let me know if it works:
> 
> `sudo apt-get update && sudo apt-get install python-pip`
> 
> if not, python-pip should be in the universe repositories so:
> 
> `sudo apt-get install software-properties-common`
> `sudo apt-add-repository universe`
> `sudo apt-get update`
> `sudo apt-get install python-pip`
> 
> https://askubuntu.com/a/672836

I am getting error of "universe" invalid

**Comment by singhmayank9560** [comment]
> ![it also says this](https://cloud.githubusercontent.com/assets/28513012/26071085/cff28876-399e-11e7-9eeb-05dc7607b449.PNG)
> 
> i think this problem is preventing me from using setoolkit and it is saying 'something went wrong printing the error no module named pexpect' and i do not know what to do, i've typed it up but i cant find a solution, does anyone know how to install it, if so let me know please
> also this doesn't work as well 'pip install pexpect or apt-get install python-pexpect', to help out the situation
> ![something went wrong](https://cloud.githubusercontent.com/assets/28513012/26071208/31dee084-399f-11e7-9941-10f6e19c7475.PNG)

Did your problem solved??

**Comment by chicconumber1** [comment]
> > ![it also says this](https://cloud.githubusercontent.com/assets/28513012/26071085/cff28876-399e-11e7-9eeb-05dc7607b449.PNG)
> > i think this problem is preventing me from using setoolkit and it is saying 'something went wrong printing the error no module named pexpect' and i do not know what to do, i've typed it up but i cant find a solution, does anyone know how to install it, if so let me know please
> > also this doesn't work as well 'pip install pexpect or apt-get install python-pexpect', to help out the situation
> > ![something went wrong](https://cloud.githubusercontent.com/assets/28513012/26071208/31dee084-399f-11e7-9941-10f6e19c7475.PNG)??
> 
> Had you solved this problem??

May I know the module you are trying to get to work in setoolkit

**Comment by singhmayank9560** [comment]
> > > ![it also says this](https://cloud.githubusercontent.com/assets/28513012/26071085/cff28876-399e-11e7-9eeb-05dc7607b449.PNG)
> > > i think this problem is preventing me from using setoolkit and it is saying 'something went wrong printing the error no module named pexpect' and i do not know what to do, i've typed it up but i cant find a solution, does anyone know how to install it, if so let me know please
> > > also this doesn't work as well 'pip install pexpect or apt-get install python-pexpect', to help out the situation
> > > ![something went wrong](https://cloud.githubusercontent.com/assets/28513012/26071208/31dee084-399f-11e7-9941-10f6e19c7475.PNG)??
> > 
> > 
> > Had you solved this problem??
> 
> May I know the module you are trying to get to work in setoolkit

I am trying to do web cloning but at the start getting the error of python-pycrpto module is not installed and then after getting the error of "no mudule named pexpect "  after completing all the steps and when i am even trying to install any package getting the error of unable to locate the package. i tried everything but won't fix it. Help me if you can..

**Comment by chicconumber1** [comment]
If it is site cloning that you want you can use an alternative socialfish.py: https://github.com/UndeadSec/SocialFish
You will probably have more chances with that. I have tried setoolkit but recently switched to social fish. My setoolkit does not have the same problem as yours but mine does not work either. Simply, it just does not continue at all.

**Comment by singhmayank9560** [comment]
> If it is site cloning that you want you can use an alternative socialfish.py: https://github.com/UndeadSec/SocialFish
> You will probably have more chances with that. I have tried setoolkit but recently switched to social fish. My setoolkit does not have the same problem as yours but mine does not work either. Simply, it just does not continue at all.

Okayy thanks for this but still i would face another problem that is unable to locate the package. Any solution do you know for this?

**Comment by chicconumber1** [comment]
> > If it is site cloning that you want you can use an alternative socialfish.py: https://github.com/UndeadSec/SocialFish
> > You will probably have more chances with that. I have tried setoolkit but recently switched to social fish. My setoolkit does not have the same problem as yours but mine does not work either. Simply, it just does not continue at all.
> 
> Okayy thanks for this but still i would face another problem that is unable to locate the package. Any solution do you know for this?

Yes actually! unable to locate packages are usually due to your repository. Depending on your kali version there are sets of recommended repository and make sure to update your packages. you can follow this https://itsfoss.com/unable-to-locate-package-error-ubuntu/

**Comment by singhmayank9560** [comment]
> > > If it is site cloning that you want you can use an alternative socialfish.py: https://github.com/UndeadSec/SocialFish
> > > You will probably have more chances with that. I have tried setoolkit but recently switched to social fish. My setoolkit does not have the same problem as yours but mine does not work either. Simply, it just does not continue at all.
> > 
> > 
> > Okayy thanks for this but still i would face another problem that is unable to locate the package. Any solution do you know for this?
> 
> Yes actually! unable to locate packages are usually due to your repository. Depending on your kali version there are sets of recommended repository and make sure to update your packages. you can follow this https://itsfoss.com/unable-to-locate-package-error-ubuntu/
Okayy thank you very much. I will try that.

**Comment by 2MLG4U** [comment]
install it manually
git clone https://github.com/pycrypto/pycrypto
cd pycrypto
sudo python3 setup.py install

worked for me

**Comment by rtteer** [comment]
![image](https://user-images.githubusercontent.com/69398716/91348003-d67bf480-e7eb-11ea-92a0-804277e271fd.png)

**Comment by 2MLG4U** [comment]
rtteer you are using python 3.6

**Comment by msaiabhinav** [comment]
its howing mine is not running as root so the setoolkit open and exits 
error :

 The Social-Engineer Toolkit (SET) - by David Kennedy (ReL1K)

 Not running as root.

Exiting the Social-Engineer Toolkit (SET).



 Thank you for shopping with the Social-Engineer Toolkit.

 Hack the Gibson...and remember...hugs are worth more than handshakes.

**Comment by idk-12345678** [comment]
> its howing mine is not running as root so the setoolkit open and exits error :
> 
> The Social-Engineer Toolkit (SET) - by David Kennedy (ReL1K)
> 
> Not running as root.
> 
> Exiting the Social-Engineer Toolkit (SET).
> 
> Thank you for shopping with the Social-Engineer Toolkit.
> 
> Hack the Gibson...and remember...hugs are worth more than handshakes.

do sudo setoolit

**Comment by Yungwonderbread** [comment]
> install it manually git clone https://github.com/pycrypto/pycrypto cd pycrypto sudo python3 setup.py install
> 
> worked for me
 when I did this, it brought a syntax error that I cant revert, I cant delete the pycrypto file either
