### ISSUE TITLE
[!] Something went wrong, printing the error: global name 'smtp' is not defined

### ISSUE THREAD

**Issue by masterkill3** [trustedsec/social-engineer-toolkit#411]
.M"""bgd `7MM"""YMM MMP""MM""YMM
        ,MI    "Y   MM    `7 P'   MM   `7
        `MMb.       MM   d        MM
          `YMMNq.   MMmmMM        MM
        .     `MM   MM   Y  ,     MM
        Mb     dM   MM     ,M     MM
        P"Ybmmd"  .JMMmmmmMMM   .JMML.

[---]        The Social-Engineer Toolkit (SET)         [---]
[---]        Created by: David Kennedy (ReL1K)         [---]
                      Version: 7.6.2
                    Codename: 'Vault7'
[---]        Follow us on Twitter: @TrustedSec         [---]
[---]        Follow me on Twitter: @HackingDave        [---]
[---]       Homepage: https://www.trustedsec.com       [---]
        Welcome to the Social-Engineer Toolkit (SET).
         The one stop shop for all of your SE needs.

     Join us on irc.freenode.net in channel #setoolkit

   The Social-Engineer Toolkit is a product of TrustedSec.

           Visit: https://www.trustedsec.com

   It's easy to update using the PenTesters Framework! (PTF)
Visit https://github.com/trustedsec/ptf to update all your tools!

 Unable to check for new version of SET (is your network up?)

 Select from the menu:

   1) Spear-Phishing Attack Vectors
   2) Website Attack Vectors
   3) Infectious Media Generator
   4) Create a Payload and Listener
   5) Mass Mailer Attack
   6) Arduino-Based Attack Vector
   7) Wireless Access Point Attack Vector
   8) QRCode Generator Attack Vector
   9) Powershell Attack Vectors
  10) SMS Spoofing Attack Vector
  11) Third Party Modules

  99) Return back to the main menu.

set> 5
[-] Sendmail is a Linux based SMTP Server, this can be used to spoof email addresses.
[-] Sendmail can take up to three minutes to start
[*] Sendmail is set to ON
set:phishing> Start Sendmail? [yes|no]:n

   Social Engineer Toolkit Mass E-Mailer

   There are two options on the mass e-mailer, the first would
   be to send an email to one individual person. The second option
   will allow you to import a list and send it to as many people as
   you want within that list.

   What do you want to do:

    1.  E-Mail Attack Single Email Address
    2.  E-Mail Attack Mass Mailer

    99. Return to main menu.
   
set:mailer>2

  The mass emailer will allow you to send emails to multiple
  individuals in a list. The format is simple, it will email
  based off of a line. So it should look like the following:

  john.doe@ihazemail.com
  jane.doe@ihazemail.com
  wayne.doe@ihazemail.com

  This will continue through until it reaches the end of the
  file. You will need to specify where the file is, for example
  if its in the SET folder, just specify filename.txt (or whatever
  it is). If its somewhere on the filesystem, enter the full path,
  for example /home/relik/ihazemails.txt
 
set:phishing> Path to the file to import into SET:'/root/Desktop/email.txt' 
[!] File not found! Please try again and enter the FULL path to the file.
set:phishing> Path to the file to import into SET:/root/Desktop/email.txt

  1. Use a gmail, hotmail, and yahoo. Account for your email attack.
  2. Use your own server or open relay

set:phishing>1
set:phishing> Your gmail, hotmail, and yahoo. email address:sinkahchuen@gmail.com
set:phishing> The FROM NAME the user will see:well
Email password: 
set:phishing> Flag this message/s as high priority? [yes|no]:y
Do you want to attach a file - [y/n]: n
set:phishing> Email subject:warening
set:phishing> Send the message as html or plain? 'h' or 'p' [p]:h
You have specified to track user email accounts when they are sent. In
order for this to work, you will need to specify the URL within the body
of the email and where you would like to inject the base64 encoded name.

When a user clicks on the link, the URL Will post back to SET and track
each of the users clicks and who the user was. As an example, say my SET
website is hosted at http://www.trustedsec.com/index.php and I want to track users.
I would type below http://www.trustedsec.com/index.php?INSERTUSERHERE. Note that in
order for SET to work, you will need to specify index.php?INSERTUSERHERE. That is the
keyword that SET uses in order to replace the base name with the URL.

Insert the FULL url and the INSERTUSERHEREon where you want to insert the base64 name.

NOTE: You must have a index.php and a ? mark seperating the user. YOU MUST USE PHP!

Note that the actual URL does NOT need to contain index.php but has to be named that for the php code in Apache to work.
[!] IMPORTANT: When finished, type END (all capital) then hit {return} on a new line.
set:phishing> Enter the body of the message, type END (capitals) when finished:
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: ksjkjsiks
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: ajhjlajhla
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: html
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: wooooskk
Next line of the body: END
[!] You have track email to on however did not specify ?INSERTUSERHERE.
[!] Tracking of users will not work and is disabled. Please re-read the instructions.
Press {return} to continue.   

[!] Something went wrong, printing the error: global name 'smtp' is not defined
hello when i finish update came out like this

**Comment by trustedsec** [comment]
Upgrade to the latest version of SET, this does not appear to be an issue in the latest version:

Note that the actual URL does NOT need to contain index.php but has to be named that for the php code in Apache to work.
[!] IMPORTANT: When finished, type END (all capital) then hit {return} on a new line.
set:phishing> Enter the body of the message, type END (capitals) when finished:sdf
Next line of the body: sdf
Next line of the body: dsf
Next line of the body: ds
Next line of the body: fds
Next line of the body: sd
Next line of the body: 
Next line of the body: sd
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: 
Next line of the body: end
Next line of the body: END
[!] You have track email to on however did not specify ?INSERTUSERHERE.
[!] Tracking of users will not work and is disabled. Please re-read the instructions.
Press {return} to continue.
[*] Sent e-mail number: 1 to address: goat@goat.com
[*] Sent e-mail number: 2 to address: gosfdsf@sdfdsf.com
[*] Sent e-mail number: 3 to address: sdfdsfsdf@sdfdsfds.coms
[*] Sent e-mail number: 4 to address: sdfdsfsd@sdfdsfsd.com
[*] SET has finished sending the emails

      Press <return> to continue

**Comment by 1peaceloves** [comment]
Something went wrong, printing the error: name 'file' is not defined
me ajudem com esse erro pfv

**Comment by csharshtiwari** [comment]
[!] Something went wrong, printing the error: name 'file' is not defined
plz solve this sir

**Comment by rashedulsizan** [comment]
How do i change setconfig SENDMAIL OFF to SENDMAIL ON?

Please, let me know. I can't edit setoolkit.conf file with nano. Tell me exact way. Thanks.
