### ISSUE TITLE
Blank Page - Site Cloner

### ISSUE THREAD

**Issue by rahimh5** [trustedsec/social-engineer-toolkit#412]
**Expected Behaviour**

The cloned website should show up on desktop and on phone and the IP can be sent to people/victims.

**Actual Behaviour**

Opening up the IP on the laptop hosting the server gives a blank page.. no error.. just nothing. But on the phone(iphone), it loads perfectly fine and the credentials are harvested.

When giving the IP to others, the website never loads. It just sits there..

**Set Version**

7.6.3

**Comment by trustedsec** [comment]
This does not appear to be consistent. You may have a configuration issue. When cloning a site, the website can be sent via the individuals as long as you have either a port forward on a NAT'ed address or you have a public IP address. Opening up the IP on a laptop or mobile shows the intended cloned server on 7.6.4. There does not appear to be a cloning issue.

**Comment by pro-xie** [comment]
I am having the same issue.
I have my apache turned on, website gets cloned into /var/www. But when I click on index.html the browser seems to go into some sort of loop, unable to open the page.

Also the same proboem persists if I type in my localhost in the URL bar, please help!
