### ISSUE TITLE
Gmail website clone: Not working

### ISSUE THREAD

**Issue by rahimh5** [trustedsec/social-engineer-toolkit#413]
I have the SET version 7.6.3

Whenever i try to use the site cloner tool and use the website gmail.com, it doesnt work. Although the site does show up, i am only able to enter the email and then it just says "sorry something went wrong" after i click next. Is there any way to get around this? Maybe linking the next button to the second part of the page?

btw, I have my port 80 port forwarded but i still cant send the link to anyone outside of network.
Plz help

**Comment by Preeqo** [comment]
try pip install pexpect or apt-get install python-pexpect.

**Comment by rahimh5** [comment]
ok. I solved the second problem (can't send the link to friends).

But I still have the problem on cloning Gmail. It's mainly due to it redirecting to a completely different website when you try to input the password.
If you don't understand what I mean, go on the incognito mode in your browser and go to the google sign in page. When you type the username and click enter, it redirects to a different password page.

My question is if there is any way to make it so that the cloned version of the page also redirects to a different page. Thanks.

**Comment by rahimh5** [comment]
bump

**Comment by rahimh5** [comment]
@Preeqo

**Comment by trustedsec** [comment]
You can try using Apache mode by editing /etc/setoolkit/set.config and changing APACHE_SERVER=OFF to APACHE_SERVER=ON. The problem with gmail specifically is that they change the codebase for it. I would recommend using the templates instead of the actual website gmail itself.
