### ISSUE TITLE
Site Cloner not working (facbook,gmail,yahoo)

### ISSUE THREAD

**Issue by kali64amd** [trustedsec/social-engineer-toolkit#415]
# **Issue:- Sit clone not working, it's just stuck (waited all night )**

Set Ver :- 7.6.3
OS :- Kali main rolling

set:webattack> Enter the url to clone:http://www.facebook.com

[*] Cloning the website: https://login.facebook.com/login.php
[*] This could take a little bit...

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:

Can anyone have any idea what is wrong???

**Comment by csmali** [comment]
Actually it seems worked.It is waiting for interaction with your web server. This is why nothing happens. 

Try to open your browser and go to localhost and check console again.
