### ISSUE TITLE
[!] Something went wrong, printing the error: No module named pexpect

### ISSUE THREAD

**Issue by Jubail** [trustedsec/social-engineer-toolkit#416]
In setoolkit under phishing when i set option 1) Perform a Mass Email Attack..
this mesg is displayed...also at the top when i launch setoolkit i see these two lines:
[!] The python-pycrypto python module not installed. You will lose the ability for encrypted communications.
[!] The python-pycrypto python module not installed. You will lose the ability to use multi-pyinjector.

**Comment by Jubail** [comment]
In setoolkit under phishing when i set option  1) Perform a Mass Email Attack..
this mesg is displayed...also at the top when i launch setoolkit i see these two lines:
[!] The python-pycrypto python module not installed. You will lose the ability for encrypted communications.
[!] The python-pycrypto python module not installed. You will lose the ability to use multi-pyinjector.

**Comment by csmali** [comment]
you should install modules as follows 
pip install pexpect

and for pycrypto module
"The modules are packaged using the Distutils, so you can simply run “python setup.py build” to build the package, and “python setup.py install” to install it." 
from python website https://pypi.python.org/pypi/pycrypto

**Comment by Preeqo** [comment]
i have the same problem and I've tried the code csmali sent but still didn't work for me

**Comment by Jubail** [comment]
Hello,
i was able to install pexpect by following these below lines:
1>git clone https://github.com/pexpect/pexpect.git
2>cd pexpect
3>python setup/py install
after this the install was success however when i run the setoolkit again i got another message saying:
Something went wrong, printing the error: No module named ptyprocess.
I followed the same steps for this module also however same mesg comes again.

**Comment by csmali** [comment]
what is your python version? you can check your version like

python
import sys
print sys.version

**Comment by Jubail** [comment]
i am having python 2.7.13

**Comment by csmali** [comment]
turns out i dont know why why but sometimes it fails to load module https://bugs.archlinux.org/task/46868
try to install module from here https://pypi.python.org/pypi/ptyprocess

**Comment by Jubail** [comment]
Thanks a lot from this link i was able to install the module...

**Comment by csmali** [comment]
you are welcome!

**Comment by pratyushk403** [comment]
while installing pexpect i got this error
python: can't open file 'setup/py': [Errno 2] No such file or directory

**Comment by subhgod** [comment]
Hi i solved the pexpect the reading commments but the ptyprocess module is issue is not sorted i have done all things but nothing happpen help pl

**Comment by subhgod** [comment]
Hi I solved the pexpect problems by reading comments and for ptyprocess i followed same but nothing happened
![Screenshot_20200529-205546](https://user-images.githubusercontent.com/66117343/83277072-29dfa600-a1ef-11ea-853f-a2fe2ea82c1e.png)
