### ISSUE TITLE
The Python-Pycrypto Python Module not installed and something went wrong printing the error no module named pexpect

### ISSUE THREAD

**Issue by Preeqo** [trustedsec/social-engineer-toolkit#419]
setoolkit
The Python-Pycrypto Python Module not installed
The Python-Pycrypto Python Module not installed

![it also says this](https://cloud.githubusercontent.com/assets/28513012/26528468/888a6eee-43a4-11e7-9bce-227515c4a83b.PNG)

![1 2 3 1](https://cloud.githubusercontent.com/assets/28513012/26528495/43c3249e-43a5-11e7-8e31-480937017d0c.PNG)

number 1
number 2 
number 3
number 2
then it says put your I.P in 
Then it says put the website in 
but it then comes up with this "something went wrong, printing the error no module named pexpect"
and the codes 'pip install pexpect or apt-get install python-pexpect' work but do not fix this problem if you could help that would be great,
cheers

**Comment by masterkill3** [comment]
hello bro you need install the python-pycrypto or make the delete download again

**Comment by Preeqo** [comment]
yeah i know but i dont know how and what do u mean by " make the delete download again"

**Comment by Preeqo** [comment]
ive fixed the python-pycrypto problem but it still says something went wrong, printing error no module named pexpect

**Comment by Preeqo** [comment]
my version is 7.6.2

**Comment by trustedsec** [comment]
7.6.5 is the latest version, but this isn't a version issue. You have something jacked up with Python. You need the pycrypto modules. Theres a few ways to address this.

If using Kali or Ubuntu:

apt-get install python-pycrypto

If not, try using:

pip install pycrpto.

I can confirm this is not a SET issue, but a module issue and installing in Python.

**Comment by Preeqo** [comment]
i have tried what u said and it came up with this 'could not find a version that satisfies the requirement pycrypto'

**Comment by codeSmart2307** [comment]
Has anyone figured out a solution for this issue? It still does not work

**Comment by 2MLG4U** [comment]
install it manually
git clone https://github.com/pycrypto/pycrypto
cd pycrypto
sudo python3 setup.py install

worked for me

**Comment by GreedyHope** [comment]
not still working for me

**Comment by GreedyHope** [comment]
can someone assist please

**Comment by hellraiser720** [comment]
here is the module you need if you do pt search python-pycrypto 

you'll get this python-pycryptodome-doc/kali-rolling,kali-rolling 3.11.0+dfsg1-4 all cryptographic Python library (documentation), so install this

apt install python-pycryptodome-doc -y I tried to deliver a payload through the default java applet & I didn't get that error so it must have worked, that's your best bet!  

Good Luck!
