### ISSUE TITLE
pycrypto modules

### ISSUE THREAD

**Issue by Preeqo** [trustedsec/social-engineer-toolkit#422]
i have tried using these codes apt-get install python-pycrypto
pip install pycrpto.
and when i do it comes up with 'could not find a version that satisfies the requirement pycrypto', i dont know why, ive got the pip installed and i have downloaded the pycrypto file and it still says it.

**Comment by trustedsec** [comment]
You would want to do apt-get install python-crypto (not python-pycrypto).

Also trying to do "import pycrypto" wouldn't work because the module is called Crypto. SET uses this:

from Crypto.Cipher import AES 

for testing.

**Comment by Preeqo** [comment]
alright thank you ill give it ago now
