### ISSUE TITLE
About Mass Mailer Attack -I am performing the attack and everything is going successfully it's even showing it's done but the output i am not getting please help me out!!

### ISSUE THREAD

**Issue by vpriyanshu** [trustedsec/social-engineer-toolkit#423]
**Expected Behaviour**

Put here what the expected behaviour should be when reporting an issue

**Actual Behaviour**

Put here what the actual behaviour should be when reporting an issue

**Set Version**

_Set version_

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by trustedsec** [comment]
This doesn't have any of the details of whats actually happening. Please put the details of what you are doing.

**Comment by piyush19996** [comment]
![Mail](https://user-images.githubusercontent.com/67028397/89683852-e86a2600-d916-11ea-81ef-b4b58aa189cc.png)
it is showing that mail is sent on target mail.but when i check target mail..their is no mail over their. please help me in this issue

**Comment by DA-RKO** [comment]
any updates? i've the same issue, showing me it's been successful, but no emails received

**Comment by piyush19996** [comment]
No
