### ISSUE TITLE
sir plz solve this error

### ISSUE THREAD

**Issue by abhishekborse111** [trustedsec/social-engineer-toolkit#424]
Python OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.
[*] Printing error: zipimporter() argument 1 must be string, not function

above shows me after cloning the wesite..i dont understand where is the and what is the problem
plz solve it
help me

**Comment by trustedsec** [comment]
Update your version of SET, this was fixed already.

**Comment by abhishekborse111** [comment]
how to update version of set sir?

**Comment by L1ghtn1ng** [comment]
What OS are you using?

Sent from phone

________________________________

**Comment by abhishekborse111** [comment]
how to update version of set in kali linux..plz help me

**Comment by L1ghtn1ng** [comment]
If you check the issues guide when you create a new issue it would of told you how to do that but you need to 1 make sure you are on Kali rolling

so do lsb_release -a in a terminal and you should see it say Kali rolling if not go to there website and download a new iso.

If you are on Kali rolling then you need to do apt update && apt dist-upgrade and you will have an up to date Kali install then but you will need to reboot after it has finished everything

Sent from phone

________________________________

**Comment by abhishekborse111** [comment]
i didnt understand how to update set on kali linux...plz give me step by step advice

**Comment by L1ghtn1ng** [comment]
https://youtu.be/<https://youtu.be/qtv9kRHbVa8>qtv9kRHbVa8<https://youtu.be/qtv9kRHbVa8> this video will show you how to do it

Sent from phone

________________________________

**Comment by abhishekborse111** [comment]
i used apt-get update
           apt-get upgrade
then wht can i do for update the set..

**Comment by L1ghtn1ng** [comment]
You will want to do apt-get dist-upgrade and set will be updated after you have done that but what do you get when you type lsb_release -a in the terminal

Sent from phone

________________________________

**Comment by abhishekborse111** [comment]
i used ./ptf 
use module/install_update_all
yes
tht process is going on from 4hrs....
is it right?
help me
