### ISSUE TITLE
SETOOLKIT pausing while cloning the website

### ISSUE THREAD

**Issue by rishabhupreti** [trustedsec/social-engineer-toolkit#425]
**Expected Behaviour**

SETOOLKIT will clone the website

**Actual Behaviour**

SETOOLKIT is pausing here and not going further:

[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:

**Set Version**

_Set version_ 7.6.5

I want to remove SETOOL and re-install it again.
Please tell me the commands.

**Comment by trustedsec** [comment]
That is the normal behavior and nothing wrong. 

You can hit control-c to get out of that, but it is the harvester waiting for credentials. If you go into the website and enter creds, you'll see the credentials appear (and logged). You can run the Apache mode by editing /etc/setoolkit/set.config and changing APACHE_SERVER=OFF to ON.
