### ISSUE TITLE
git clone 

### ISSUE THREAD

**Issue by LuciferMoSt** [trustedsec/social-engineer-toolkit#426]
It is supposed to clone the SET to my pc. I run the command: 

It gives me this error: fatal: unable to access 'https://github.com/trustedsec/social-engineering-toolkit/': gnutls_handshake() failes: A TLS packet with unexpected lenght was recived.

Doing it in the Linux Subsystem for Windows 10

**Comment by L1ghtn1ng** [comment]
You forgot the .git extension at the end so it should be
git clone https://github.com/trustedsec/social-engineering-toolkit.git

Sent from phone



From: LuciferMoSt
Sent: Wednesday, 14 June, 12:42
Subject: [trustedsec/social-engineer-toolkit] git clone (#426)
To: trustedsec/social-engineer-toolkit
Cc: Subscribed


It is supposed to clone the SET to my pc. I run the command:

It gives me this error: fatal: unable to access 'https://github.com/<https://github.com/trustedsec/social-engineering-toolkit/>trustedsec<https://github.com/trustedsec/social-engineering-toolkit/>/social-engineering-toolkit/<https://github.com/trustedsec/social-engineering-toolkit/>': gnutls_handshake() failes: A TLS packet with unexpected lenght was recived.

**Comment by agvs03** [comment]
Cloning into 'social-engineering-toolkit'...
fatal: unable to access 'https://github.com/trustedsec/social-engineering-toolkit.git/': Could not resolve host: github.com
 getting an error
