### ISSUE TITLE
pycrypto modules 

### ISSUE THREAD

**Issue by Preeqo** [trustedsec/social-engineer-toolkit#427]
i have tried using these codes apt-get install python-pycrypto, pip install pycrpto and apt-get install python-crypto
and when i try to do them it comes up with 'could not find a version that satisfies the requirement pycrypto', ive already addressed this issue but when i did i followed what you said and  it still didn't work, im not sure why 
also is there anyway i can check to see if ive got pip because if i dont will that be why, i think i do have it 
![boss](https://user-images.githubusercontent.com/28513012/27150188-187f7cfa-513e-11e7-8f01-aef19d888e40.PNG)

**Comment by trustedsec** [comment]
This isn't really a Social-Engineer Toolkit issue on this front - looks to be a dependency issue. Would recommend reinstalling Python 2.7 and ensuring that it's working properly.

**Comment by Preeqo** [comment]
okay ill go and try now thank you
