### ISSUE TITLE
site cloner creds harvester not working properley and when apache enabled it dose not copy over the site cloned to the directorey 

### ISSUE THREAD

**Issue by necony286** [trustedsec/social-engineer-toolkit#430]
**Expected Behaviour**

Put here what the expected behaviour should be when reporting an issue
*] Cloning the website: https://store.steampowered.com/login/
[*] This could take a little bit...

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:
97.146.149.172 - - [19/Jun/2017 19:29:58] "GET / HTTP/1.1" 200 -

^C[*] File exported to /root/.set//reports/2017-06-19 19:30:17.063952.html for your reading pleasure...
[*] File in XML format exported to /root/.set//reports/2017-06-19 19:30:17.063952.xml for your reading pleasure...

      Press <return> to continue
now when i open the xml file i should have the login info?

**Actual Behaviour**
but when i open it i get 
<?xml version="1.0" encoding='UTF-8'?>
<harvester>
   store.steampowered.com/login/
</harvester>
no username or passwds

and when i set the config file to use apache2 i cant even get the site cloned.

**Comment by necony286** [comment]
and i have been having trouble with this libapache2-mod-php
is this good ? 

apt-get install git apache2 python-requests libapache2-mod-php5   python-pymssql build-essential python-pexpect python-pefile python-crypto python-openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
python-pexpect is already the newest version.
python-pymssql is already the newest version.
python-openssl is already the newest version.
python-pefile is already the newest version.
python-requests is already the newest version.
apache2 is already the newest version.
git is already the newest version.
git set to manually installed.
libapache2-mod-php5 is already the newest version.
python-crypto is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by necony286** [comment]
and when i set the config file to use apache2 i cant even get the site cloned.
there only post.php in /var/www but no index.php only index.html which is not the cloned site.

**Comment by trustedsec** [comment]
Some sites are tricky, right click save as on the page, and use the import functionality to get it in the right way.
