### ISSUE TITLE
set not properly cloning sites 

### ISSUE THREAD

**Issue by thejbruu** [trustedsec/social-engineer-toolkit#433]
my  set is updated. i am using it on OSX.

When I go to the cloned website, it is all choppy and looks like an uncompleted website.  ive been trying to find other people who have had this problem and no one seems to. 

any idea?
------
update
it now stopped cloning completely and tells me this (even after killing processes using 80. usually a restart of my system fixes it, annoying but bearable. more worried about the first part)
[*] Looks like the web_server can't bind to 80. Are you running Apache?
Do you want to attempt to disable Apache? [y/n]: y
[*] Try disabling Apache and try SET again.
[*] Printing error: [Errno 48] Address already in use

maybe theres a bug needing to be fixed on OSX version?

**Comment by yorondahacker** [comment]
Hello
type in terminal: ( cd /etc/setoolkit/ )
then type : ( leafpad set.config )
then go and search ( APACHE_SERVER ) and change it from APACHE_SERVER=ON to APACHE_SERVER=OFF
:dancer:

**Comment by azamet90** [comment]
still not cloning

**Comment by m0caa** [comment]
> still not cloning

Change it to ON not OFF! worked 4 me
