### ISSUE TITLE
Setoolkit phishing issue while opening the link (cloning tool)

### ISSUE THREAD

**Issue by yorondahacker** [trustedsec/social-engineer-toolkit#438]
Hello.....
please can anyone help me??
the problem is when i make a fake website with cloning tool 
it doesn't work
like it's working on my laptop but it's not working on my friend's laptop
   ...............................................................ON MY PC.........................................................................
                          
![screenshot from 2017-07-13 04-08-18](https://user-images.githubusercontent.com/30133055/28146230-43ba1484-6746-11e7-85cb-094eb5780ebb.png)

 ...............................................................ON MY FRIEND'S PC..............................................................
![screenshot from 2017-07-13 04-14-02](https://user-images.githubusercontent.com/30133055/28146335-14d0b906-6747-11e7-9e0e-0282b23e1096.png)

any help please?!

**Comment by trustedsec** [comment]
Looks like you are cloning two different sites? I would try saving that website (save as) then importing it into SET.
