### ISSUE TITLE
Something went wrong, printing the error: tuple index out of range

### ISSUE THREAD

**Issue by bluedomain** [trustedsec/social-engineer-toolkit#439]
Set Version : 7.7
Running fully-updated kali linux rolling version in Vmware workstation pro 12.5.1
virtual machine network mode set to bridging mode 
I selected first option of arduino-based attack.
first option for types of payloads (Powershell HTTP GET MSF payload)
first option for payloads (Meterpreter Memory Injection) 

After program created arduino code, when I hit return
It said the error (Something went wrong, printing the error: tuple index out of range)

Is there anything special about the vmware version of kali linux that I have to deal with?

**Comment by trustedsec** [comment]
Hmm, can you put the full log there? I can't seem to reproduce:

set:payloads> Enter the number for the payload [meterpreter_reverse_https]:
[*] Reverse_HTTPS takes a few seconds to calculate..One moment..
No encoder or badchars specified, outputting raw payload
Payload size: 354 bytes
Final size of c file: 1512 bytes
[*] Prepping pyInjector for delivery..

[*] INO file created. You can get it under '/root/.set/reportsteensy_2017-07-23 11:44:18.018393.ino'
[*] Be sure to select "Tools", "Board", and "Teensy 2.0 (USB/KEYBOARD)" in Arduino

[*] If your running into issues with VMWare Fusion and the start menu, uncheck
the 'Enable Key Mapping' under preferences in VMWare
Press {return} to continue.

[*] Launching MSF Listener...
[*] This may take a few to load MSF...
This copy of metasploit-framework is more than two weeks old.
 Consider running 'msfupdate' to update to the latest version.
