### ISSUE TITLE
How to change credential harvester's Default port from 80 to 4444 ????

### ISSUE THREAD

**Issue by PaKiStAnZiNdAbAdD** [trustedsec/social-engineer-toolkit#441]
i want to change credential harvester's default port from 80 to 4444 so when i open :

http://127.0.0.1:4444/

the phishing page loads , and when i enter credentials , they display on the terminal ...

please help me , i have tried everything , but i have not been successful yet ...

if you help me , i will be very thank full to you ...

**Comment by trustedsec** [comment]
Edit the port under /etc/setoolkit/set.config:

WEB_PORT=80
