### ISSUE TITLE
 i cant find config file in setoolkit,why? i had updated setoolkit

### ISSUE THREAD

**Issue by kdie** [trustedsec/social-engineer-toolkit#442]
No config file exists,so i cant modify set_config, how to solve this problem

**Comment by trustedsec** [comment]
/etc/setoolkit/set.config

**Comment by sithijalakshan** [comment]
Shows that- cd: no such file or directory: SEToolkit
what to do with this?

**Comment by Hackeralgerian** [comment]
> No config file exists,so i cant modify set_config, how to solve this problem
