### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by Preeqo** [trustedsec/social-engineer-toolkit#443]
![why hass it](https://user-images.githubusercontent.com/28513012/28493750-c3b20c4e-6f13-11e7-88e0-0d716f6807c8.PNG)
why does it just stay on that, where as when i looked it up loads more of other stuff came up for different people
do i need to download something?

**Comment by trustedsec** [comment]
Nope, check out the message:

"Information will be displayed to you as it arrives below:"

It's waiting for credentials at that point. If you want to use apache and not use the built in web server you can edit /etc/setoolkit/set.config and turn APACHE_SERVER=OFF to APACHE_SERVER=ON

**Comment by Preeqo** [comment]
okay ill give it ago now, thank you

**Comment by Preeqo** [comment]
when i type in /etc/setoolkit/set.config it says permission denied
