### ISSUE TITLE
sms spoof is not working

### ISSUE THREAD

**Issue by CrissAngel007** [trustedsec/social-engineer-toolkit#447]
sms spoofing vector is not working 

it says that when i choose that option
"set> 10
**[!] This module is currently disabled as spoofmytextmessage.com is currently experiencing issues. As soon as it is working again or I can rework the module, this will remain disabled.
"
![screenshot from 2017-07-31 23-52-34](https://user-images.githubusercontent.com/30617101/28812816-253bcadc-765c-11e7-8f41-2b8b05b24701.png)
**
please fix it. if that option is not working in set then please remove it .
or please fix it fast

**Comment by ssshah2131** [comment]
same probleam how to fix?

**Comment by externintvoid** [comment]
install kali linux 1.0.6 or older, it should work

**Comment by enochsingano** [comment]
please fix that issue ASAP

**Comment by zackvirushacke** [comment]
alguem conseguil aruma isso na versao 2018.3
