### ISSUE TITLE
Problem with harvesting credentials - Credential Harvester Method

### ISSUE THREAD

**Issue by cantthinkofanydecentname** [trustedsec/social-engineer-toolkit#448]
I am having an issue with the CHM. Whenever someone enters their credentials into the cloned website, the page simply refreshes, and redirects them to the actual login page of the website which I cloned. After a user enters their details, they are not taken to the expected next page, and no error is shown, it simply just redirects them to the actual login page. 

How can this be fixed? Is this inevitable and is there any way to fix this?

**Comment by trustedsec** [comment]
Some sites have strange ways of handling post params and SET doesn't necessarily know all of the variations. It's possible that the POST params are strange and not properly posting to the SET harvester. The behavior your experiencing there sounds just like that, refreshing to the legitimate site is normal once the post has been set. I would recommend turning APACHE_SERVER to ON under /etc/setoolkit/set.config, then once the site is cloned, go into index.html and look at where the POST params are and rewrite them to post to the SET server and test accordingly.

**Comment by ghero** [comment]
I'm cloning gmail, everything works fine up to the point where you enter email, and then it won't redirect to the password page.
Here is the error that I get:

`[*] WE GOT A HIT! Printing the output:
PARAM: trace=CustomError
    at new vu (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:623:92)
    at Du.Yb (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:635:325)
    at Cn (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:493:231)
    at Bn (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:491:44)
    at _.zn.Ea (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:490:452)
    at Cn (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:493:231)
    at Bn (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:491:44)
    at _.zn.a (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:491:207)
    at Du.<anonymous> (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:633:214)
    at sr (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:567:183)
PARAM: context.location=http://10.10.1.11/signin/v2/identifier
PARAM: context.top.location=http://10.10.1.11/signin/v2/identifier
PARAM: context.version=gaia.gaiafe_glif.en.1hw9HpnD7D8.O
PARAM: context.call-stack=Error
    at Yp (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:676:96)
    at Zp (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:537:194)
    at rw.$p [as f] (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:537:351)
    at c (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:678:447)
PARAM: script=http://10.10.1.11/signin/v2/identifier
PARAM: error=There was an error during the transport or processing of this request. Error code = 10, Path = /_/signin/sl/lookup
PARAM: line=Not available`

Regards,

**Comment by sriniv398** [comment]
KALI LINUX 2017.1 setoolkit Credential Harvester Attack Method cloning website Error 501: Not Implemented error shows pls help me

**Comment by L1ghtn1ng** [comment]
You need to reinstall Kali as you are not on Kali rolling, go to kali.org to get up to date iso.


________________________________

**Comment by sriniv398** [comment]
i am already re-intsall kali

**Comment by sriniv398** [comment]
I am not understand pls refer me detail

**Comment by sumon1142** [comment]
When  I use credential Harvester > site Cloner in my LAN environment it works fine that means, it returns 1) POSSIBLE USERNAME FIELD FOUND, 2) POSSIBLE PASSWORD FIELD FOUND, 3)Redirects to actual site. BUT when I use the same method on WAN it returns some arbitrary data and comes to the last line "WHEN YOU HAVE FINISHED......." I am using kali-rolling 2017.2, SET version 7.7.2 and NO PROBLEM with port forwarding.

**Comment by trustedsec** [comment]
You need to use your external IP address not your NAT'd address. This is networking not a SET issue... External users from the outside browsing a site won't know where to hit or to post to if you don't specify the external interface when prompted for the NAT address.

**Comment by sumon1142** [comment]
I am using VPN service and enabled remote port forwarding from port 9366 to local port 80. My test victim is connecting using my external IP (the ip i get from whatismyip.com after connecting with VPN) as x13.x82.1x1.24x:9366

**Comment by sumon1142** [comment]
OK, With Remote Port Forwarding from my VPN and keeping all default in set.config I was able to get the credentials by entering my VPN IP and port in the field 
"IP address for the POST back in Harvester/Tabnabbing" like xxx.xxx.xxx.xxx:9366. 

It returns back the credentials I entered in the fake website but after clicking login button it is forwarding to xxx.xxx.xxx.xxx:9366/login.php?login_attempt=1&lwv=100 whereas it supposed to forward to the original site.

**Comment by samsingham** [comment]
I have the same problem with my Kali Linux 2017.3 if you find any solution kindly inform me please

**Comment by Omegamk** [comment]
same here

**Comment by trustedsec** [comment]
Take a look at whats contained within post.php, that is where the redirect should be occurring, also check /etc/setoolkit/set.config ensure AUTO_REDIRECT=ON

**Comment by Tijanempire** [comment]
please i have an issue, i recently just installed Kali Linux on my mac via VMware my Kali Linux is working fine but anytime i try the setoolkit and i send the link the person i sent the link to will say it is not opening"web page not available" please help me

**Comment by benseshi** [comment]
Tijanempire you will be using the local ip address of yours for setoolkit it will work only on localhost not on WAN

**Comment by benseshi** [comment]
@sumon1142  use ngrok with port forwading  ./ngrok http 80 and use the line after the http in the ip place while cloning youll get the output what you wanted enjoy! but hacking is illegal nobody here promotes hacking

**Comment by hforte** [comment]
I have been trying to create a website using the Credential Harvester tool and it is taking forever to create.  What could be the issue?

**Comment by AmanDragoon** [comment]
@benseshi  I got the results using ngrok, but the problem is that while directing to ngrok server . I'm not able to see the pictures it's just a HTML file .in black and white . 
What to do

**Comment by harshaw88** [comment]
i have a problem in my device i am getting the clonned site but in my friends device its not showing anything any one help please
--

**Comment by Prajwal196** [comment]
I am using ./ngrok http 80
And the link thus proved as ip. 
Victim is able to open the colned site
But I am unable to get the credential. It automatically shows some bunch of random data and says WHEN YOU'RE FINISHED, HIT CONTROL C TO GENERATE AND STOPS. 
Also when victim enters credentials and hits login it redirects to some ngrok page and says error loading page.

PLEASE HELP. I can't find solution anywhere!!!

**Comment by GoldenAppStudio** [comment]
Hi, Prajwal. 
When SEToolkit ask for IP address for the POST back in Harvester/Tabnabbing, use your local address instead of Ngrok link.

**Comment by franzleo** [comment]
i used the local ip but the result is same

**Comment by franzleo** [comment]
i used the local ip but the result is same

**Comment by franzleo** [comment]
i used the local ip but the result is same

**Comment by franzleo** [comment]
i used the local ip but the result is same

**Comment by kallabharath** [comment]
i created a cloned website and i want to test it but i cant open the url in other devices then how can i send it to others.

**Comment by The-Jester12** [comment]
Not too sure where to post this, just wondering why I got this Binary text which translate to "you really have too much time on your hands" 
 01011001011011110111010100100000011100
         10011001010110000101101100011011000111
         10010010000001101000011000010111011001
         10010100100000011101000110111100100000
         01101101011101010110001101101000001000
         00011101000110100101101101011001010010
         00000110111101101110001000000111100101
         10111101110101011100100010000001101000
         01100001011011100110010001110011001000
         00001110100010110100101001001000000101
         01000110100001100001011011100110101101
         11001100100000011001100110111101110010
         00100000011101010111001101101001011011
         10011001110010000001110100011010000110
         01010010000001010011011011110110001101
         10100101100001011011000010110101000101
         01101110011001110110100101101110011001
         01011001010111001000100000010101000110
         11110110111101101100011010110110100101
         11010000100000001010100110100001110101
         011001110111001100101010

**Comment by ShaikMisbha** [comment]
> I'm cloning gmail, everything works fine up to the point where you enter email, and then it won't redirect to the password page.
> Here is the error that I get:
> 
> `[*] WE GOT A HIT! Printing the output: PARAM: trace=CustomError at new vu (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:623:92) at Du.Yb (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:635:325) at Cn (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:493:231) at Bn (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:491:44) at _.zn.Ea (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:490:452) at Cn (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:493:231) at Bn (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:491:44) at _.zn.a (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:491:207) at Du.<anonymous> (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:633:214) at sr (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:567:183) PARAM: context.location=http://10.10.1.11/signin/v2/identifier PARAM: context.top.location=http://10.10.1.11/signin/v2/identifier PARAM: context.version=gaia.gaiafe_glif.en.1hw9HpnD7D8.O PARAM: context.call-stack=Error at Yp (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:676:96) at Zp (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:537:194) at rw.$p [as f] (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:537:351) at c (/accounts/static/_/js/k=gaia.gaiafe_glif.en.1hw9HpnD7D8.O/m=glifb,identifier,unknownerror/am=ggAQAAAAqEAFQQRgAioAGQw/rt=j/d=1/rs=ABkqax0EYoYhGRjqsizRCyC9tWIrTrkrGQ:678:447) PARAM: script=http://10.10.1.11/signin/v2/identifier PARAM: error=There was an error during the transport or processing of this request. Error code = 10, Path = /_/signin/sl/lookup PARAM: line=Not available`
> 
> Regards,

Brother Facing Same issue have uh solved that?

**Comment by Anarchy00** [comment]
> I am using ./ngrok http 80
> And the link thus provided as ip. 
> Victim is able to open the colned site
> But I am unable to get the credential. It automatically shows some bunch of random data and says WHEN YOU'RE FINISHED, HIT CONTROL C TO GENERATE AND STOPS. 
> Also when victim enters credentials and hits login it redirects to some ngrok page and says error loading page.
> 
> PLEASE HELP. I can't find solution anywhere!!!

Hello please are you able to solve your problem I have similar issues
