### ISSUE TITLE
Delete a site on a IP on SET ~ The Site Cloner

### ISSUE THREAD

**Issue by coolneb** [trustedsec/social-engineer-toolkit#449]
So basically when i used the site cloner it cloned a site perfectly. Then when I tried to use it again to clone a different looking site it didn't do it. It just showed the same site I cloned earlier. Is there a fix
 for this?

Like is there a way to delete the previously cloned site to clone another one?

**Comment by usama7628674** [comment]
@coolneb 
You can fix it by doing the following
Go _to_ /root/.set/ directory and delete all files and folders then clone any site.Do this everytime when cloning different sites

**Comment by trustedsec** [comment]
You can also completely exit SET which will clear that folder as well when re-issuing. I'll add a check in there to clean the site out upon exit of harvester in next release.

**Comment by coolneb** [comment]
I dont know what you mean by
Go to /root/.set/ directory and delete all files and folders then clone any site.

**Comment by PhistterbutInc** [comment]
What he means is cd to the .set directory in a terminal and then cd to the web clone folder and rm *
