### ISSUE TITLE
Python Openssl wasn't detected

### ISSUE THREAD

**Issue by ottorobertson** [trustedsec/social-engineer-toolkit#450]
![screen shot 2017-08-16 at 19 31 48](https://user-images.githubusercontent.com/31076575/29379329-03df506a-82ba-11e7-87d9-de681e3b6e92.jpg)

I'm kind of an idiot (new to all this) so can someone spell out to me exactly what to do.

Yes, I know that there are similar / the same issues on this already but I've tried some solves with no success.

Running on Virtual Box. Think everything is new and updated.

Thanks in advance.

**Comment by trustedsec** [comment]
What version of SET you using? This came up a long time ago but it should be fixed in the most recent.

**Comment by dhamo003** [comment]
give a solution

**Comment by dhamo003** [comment]
i have a same problem

**Comment by trustedsec** [comment]
pip install openssl
