### ISSUE TITLE
not receiving spoof mail from gmail

### ISSUE THREAD

**Issue by anarchia1** [trustedsec/social-engineer-toolkit#453]
**Expected Behaviour**

receive spoof mail on victims pc send bij hack pc setoolkit 1 => 5 mass mailer => 1 E-Mail Attack Single Email Address => Use a gmail Account for your email attack

**Actual Behaviour**

don't receive any spoof mail on different mail addressen do I need to activate something ?

**Set Version**

Version: 7.7.1

root@KL:~/data# lsb_release -rdc
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

I also use your very cool ptf toolkit is wonderfull thank you very much is a great help.

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by anarchia1** [comment]
Ok found it had to activate the less secure access for apps on gmail,
Now it works like expected but in the "from to" you also see the original gmail address any option to hide this ?

Thank you 

Kind Regards

**Comment by tunis454** [comment]
use an smtp bruh

**Comment by anjash** [comment]
> use an smtp bruh

But how
help, no email is given by SET
