### ISSUE TITLE
Credential Harvester

### ISSUE THREAD

**Issue by dankestdog** [trustedsec/social-engineer-toolkit#454]
Should be done cloning sites within a few minutes?

The credential harvester never seems to end up cloning a page and hosting the site with my ip address.
I'm guessing i need to port forward? 

latest version
in  parrotsec os

**Comment by JaxsonYoung** [comment]
I'm having problems with SET on Parrot Sec too, But my problem is that the normal POST.php and harvaster.txt are not stored inside /var/www/html. I found when I clone a website it just says we will keep you updated with new credentials or something and it did not show the output of there the cloned website was stored, so i checked the /var/www/html and nothing but I managed to find it inside /root/.set/ but am still unable to generate a POST.php and harvaster.txt.

Hopefully that helps

**Comment by JaxsonYoung** [comment]
Oh lol, goto https://github.com/trustedsec/social-engineer-toolkit/issues/364 That fixed my problem, Files inside /var/www/html :)

**Comment by trustedsec** [comment]
If you are behind a firewall then you would need to port forward/nat and place the external IP address of that on the harvester IP.
