### ISSUE TITLE
Error while using website cloning tool

### ISSUE THREAD

**Issue by azartheen** [trustedsec/social-engineer-toolkit#457]
Help me What is that

**Comment by usama7628674** [comment]
Please provide full error details including screenshot.

**Comment by cloakedsec** [comment]
The setoolkit throws a warning that Python SSL was not detected but going forward to clone the website, it keeps on getting stuck on 'Cloning the website can take a few minutes or something' and stays on it for a while so that I have to manually exit the tool

**Comment by usama7628674** [comment]
Which OS are you using?Please clone latest repo.

**Comment by usama7628674** [comment]
@cloakedsec The new version (7.7.1) doesn't throw any Python SSL error and site cloner is working fine.

**Comment by azartheen** [comment]
linux....

**Comment by azartheen** [comment]
linux....

**Comment by Wh1te5had0w** [comment]
I also have the same issue 
okey I installed fedora and after installing it and running as root I cloned set after installing it , it tells me that I may not be running a fedora system and many more and then also I may not have installed git which I have already done, also I may not have installed python pexpect and many more
