### ISSUE TITLE
SET (Social Engineering Toolkit) Metasploit path not found MAC_OS SIerra 10.12.6

### ISSUE THREAD

**Issue by SuperSuperSenpai** [trustedsec/social-engineer-toolkit#460]
# So this is the problem  - ↓

"Sorry. This feature is not yet supported in Windows or Metasploit was not found." - I have this **everytime** I try to use Spear Phishing attacks ext. What should I do? 

**Also when I start SET, it says** -

>  [!] Metasploit path not found. These payloads will be disabled.
> [!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.
> Traceback (most recent call last):
>   File "./setoolkit", line 100, in <module>
>     update_config()
>   File "/Users/denysbondarenko/social-engineer-toolkit/src/core/update_config.py", line 97, in update_config
>     new_config = open("/etc/setoolkit/set_config.py", "w")
> IOError: [Errno 13] Permission denied: '/etc/setoolkit/set_config.py'

So **sometimes** SET **starts**, sometimes **don't.** 

------------------------------------------------------------------------------------------

But the message  ↓↓↓

> [!] Metasploit path not found. These payloads will be disabled. [!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.

**Stays anyways**.

----------------------------------------------------------------------------------------

In my case I do not have set.config file, instead, I have set.py! And so I open it and this is one interesting thing, it says: 

> Define path and set it to the SET root dir
> 
> definepath = os.getcwd()
> sys.path.append(definepath)

So please explain **step-by-step** what should I go, because I browsed the whole internet in hope that someone will help but unfortunately nobody did. 

I am running MAC_OS Sierra 10.12.6

**Comment by guodong000** [comment]
end path with splash like `/usr/local/share/metasploit/` not `/usr/local/share/metasploit`

**Comment by leodimaz** [comment]
1) find your msfconsole path (in my case /opt/metasploit-framework/bin/)
2) open src/core/setcore.py located in set folder
3) add these lines to meta_path() function:

`# Sierra
        if os.path.isfile("/opt/metasploit-framework/bin/msfconsole"):
            if trigger == 0:
                msf_path = "/opt/metasploit-framework/bin/"
                trigger = 1`

4) restart setoolkit and all should work

**Comment by never0lie** [comment]
> end path with slash like `/usr/local/share/metasploit/` not `/usr/local/share/metasploit`

really solved the problem by adding the slash
