### ISSUE TITLE
interference

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [trustedsec/social-engineer-toolkit#461]
Hello
when i try to start social engineer toolkit using `set` command i got this:
[asciinema capture](https://asciinema.org/a/137910)

Any idea?
[all the text shown by set command](https://ybin.me/p/3a3467fe4838acfa#fCPWqeeRcsg2hCTX8U4+Ix9CR9x6st+Bq450pIhaCnE=)

extra info: 

- Os: Elementray OS

- $ uname

       `Linux ghostlab 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 
        x86_64 x86_64 x86_64 GNU/Linux`

[issue in elementary os](https://github.com/pimvullers/elementary/issues/179)

**Comment by trustedsec** [comment]
Looks like a bad install of SET. Would recommend reinstalling.
