### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by troyboyfuad** [trustedsec/social-engineer-toolkit#462]
i try it with  ngrok but doesn't work weird issue
![21767071_227407867787822_786815541_o](https://user-images.githubusercontent.com/32087010/30576944-0bd1fd94-9d2d-11e7-8f2f-674f2f15bc17.png)

**Comment by usama7628674** [comment]
Use local tunnel instead.The link is following
https://github.com/localtunnel/localtunnel
