### ISSUE TITLE
Feature Request, Cred Harvest

### ISSUE THREAD

**Issue by PhistterbutInc** [trustedsec/social-engineer-toolkit#463]
Can the use of apache virtual hosts be added to the cred harvesting options? Ideally, the harvester would be able to clone and host multiple websites on one apache server, then output captured info to a database accessible by metasploit. My python skills are non-existent at best.

Also, the line that has possible user, login, Login, LOGIN variable names needs a 'User' added to it I believe.
One of the entries didn't have a duplicate with varied case.

**Comment by PhistterbutInc** [comment]
harvester.py, line 330

**Comment by trustedsec** [comment]
Added User, thanks! For Apache virtual hosts, you should be able to configure that since after SET copies the files to the directory path, there is nothing else SET really does on that side, o you can configure Apache to your desire after that point.
