### ISSUE TITLE
Mac Os Sierra

### ISSUE THREAD

**Issue by blackhatethicalhacking** [trustedsec/social-engineer-toolkit#465]
**Expected Behaviour**

Create an index.html under:

### Path to the Apache web root.
APACHE_DIRECTORY=/Library/WebServer/Documents/

This path was configured also through apache httpd.conf and added virtual host to accept this specific path.

**Actual Behaviour**

What its doing is, creating correctly the post.php with this content:

<?php $file = 'harvester_2017-09-25 20:15:39.298385.txt';file_put_contents($file, print_r($_POST, true), FILE_APPEND); 
/* If you are just seeing plain text you need to install php5 for apache apt-get install libapache2-mod-php5 */ ?><meta http-equiv="refresh" content="0; url=http://www.google.com" />

But it doesnt create an index.html

i created a manual one, and placed it there --> it doesnt write to it.

The Rights are set through chmod and chown correctly, this is why it is allowed and is creating post.php

**Set Version**

 Version: 7.7.1

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**
i am using mac os sierra.

**Comment by blackhatethicalhacking** [comment]
![untitled](https://user-images.githubusercontent.com/13942386/30822392-48295554-a231-11e7-9a65-6f95fb6d1531.png)

Its also able to generate the harvester log file as you can see.

it doesnt create index.html

just creates post.php and the harvester log file.

**Comment by blackhatethicalhacking** [comment]
![apache working on macsierra](https://user-images.githubusercontent.com/13942386/30822537-c4070b94-a231-11e7-8d22-03274d7ea652.png)
Apache Working, so i dont think we have to look into that.

**Comment by PhistterbutInc** [comment]
What dir are you trying to find the html under? I believe it's located at /.set/web_clone

**Comment by blackhatethicalhacking** [comment]
It should create the clone site, locally directly to the Apache Path, so my path for apache in my mac os is:

APACHE_DIRECTORY=/Library/WebServer/Documents/


Its creating post.php and the harvester___log.txt but not index.html

**Comment by blackhatethicalhacking** [comment]
Um Bump? :)

**Comment by trustedsec** [comment]
This appears to be fixed, at least it is on OSX High Sierra, it uses shutil to copy to apache directory.
