### ISSUE TITLE
Credential harvestor hosted on HTTPS page

### ISSUE THREAD

**Issue by harshil2105** [trustedsec/social-engineer-toolkit#467]
I want to know that if I have a https domain then can I start credential harvesting( it appears nice when people see https written on the top rather then http) As you know setoolkit on starting credential harvestor shutdowns Apache server,resulting in shutting down my https page running on port 443 and show a page on http which is on port 80.......All I want is to host a page on a https server rather then on normal http page....is it possible to do so and if it is them how to do it

**Comment by PhistterbutInc** [comment]
Try using the config file at /etc/setoolkit/
theres an option for ssl and apache both. make sure set is updated too.

**Comment by harshil2105** [comment]
Negative,it doesn't work I changed set to work with a Apache server and allowed ssl and tls but still I can't get credential a person types

**Comment by trustedsec** [comment]
With APACHE_SERVER=ON, all contents are copied to /var/www/ or /var/www/html (depending on Linux distro). Once that happens, SET is essentially done and you can configure SSL via Apache. For writing files, the creds are placed in a randomized txt file in the var directory

**Comment by himuura** [comment]
im having a couple of issues regarding the cloning, whenever the cloned website has the characters " Ç " or " ó ", they appear as % or ~ . Any ideas on how to fix this? i think it must be related to charset...

**Comment by trustedsec** [comment]
You can try cloning the site on your own by going to the site and doing a file / save as in the browser and from there using the import functionality if you are having issues. SET uses first wget, if that fails then it uses beautifulsoup and a few other things to grab the site, sometimes strange characters don't get converted properly - just the way of cloning sites :)
