### ISSUE TITLE
setoolkit broke up 

### ISSUE THREAD

**Issue by oussamagtp** [trustedsec/social-engineer-toolkit#470]
i had a problem before when i try to start the setoolkit on my - ubuntu 17.04 - ita said there is a problem with the method and so i could fix it manually by changing the Method in the Config but a new problem show up 
when i try to start it i see that message in the top  : Something went wrong. Printing error: 'NoneType' object has no attribute 'endswith'
![screenshot from 2017-10-02 12-02-41](https://user-images.githubusercontent.com/32412605/31074917-2eabd2c2-a773-11e7-9ace-bbf6254109a9.png)
as you can see here 
and same when i try to - clone or so  a weird messages come up 
is there any one can help ?
![screenshot from 2017-10-02 12-03-54](https://user-images.githubusercontent.com/32412605/31074941-4c697832-a773-11e7-8e7c-ae1759f57d2f.png)

**Comment by chrisstone07** [comment]
What changes did u make? And where did u make these changes?

**Comment by oussamagtp** [comment]
set.config 
i changed the path 
Define the path to Metasploit. For example: /opt/metasploit/apps/pro/msf3
**/opt/metasploit/apps**

**Comment by chrisstone07** [comment]
Add / at the end and update your set configuration

**Comment by trustedsec** [comment]
Added a fix for this in the future, will be releasing soon
