### ISSUE TITLE
problem cloning website

### ISSUE THREAD

**Issue by avanger9** [trustedsec/social-engineer-toolkit#471]
Hi,

i have problems when i try to clone a website

![captura66](https://user-images.githubusercontent.com/32470419/31103613-27f6c170-a7d8-11e7-804c-2c32fb8506b2.PNG)

and nothing happen. i read other post in this forum but nothing work. i did update and upgrade but nothing change. What i can do?

Thanks!

**Comment by gourgopal3** [comment]
check your internet connection...
i think there was a problem with your internet connection

**Comment by avanger9** [comment]
the problem can be for bad connection? i'm little far from router.

**Comment by trustedsec** [comment]
You need to hit the site remotely and enter in credentials, the information of the creds will be posted below when they are submitted.
