### ISSUE TITLE
RATTE Third Party Module Not Loading

### ISSUE THREAD

**Issue by krypto-kraken** [trustedsec/social-engineer-toolkit#473]
**Expected Behaviour**

When loading third-party modules (option 3), all third party modules present in /usr/share/setoolkit/modules directory load and are displayed as options when running SET.

**Actual Behaviour**

After choosing option 3 (Third-Party Modules) off of the main SET menu, only the Google Analytics Module loads. I am specifically looking to use the RATTE module. The python file is present in the /usr/share/setoolkit/modules directory, but it won't load into SET when I start it up.

If I try to run the ratte_module.py staright from the directory (not using the SET interface), I get this error:

Traceback (most recent call last):
  File "./ratte_module.py", line 29, in <module>
    import src.core.setcore as core
ImportError: No module named src.core.setcore

**Set Version**

7.2.2

**Comment by trustedsec** [comment]
You can't run ratte module directly, you need use it through SET.
