### ISSUE TITLE
 [Errno 2] No such file or directory: '/etc/setoolkit/set.config'

### ISSUE THREAD

**Issue by Hax4us** [trustedsec/social-engineer-toolkit#478]
This error comes after choosing option site cloner ...I know..this is not big error so...plz tell me that where should I look for this line where I can change the path of set.config file....

**Comment by Vaxthe** [comment]
I also have the same problem too

**Comment by trustedsec** [comment]
You most likely have not installed SET, would recommend running python setup.py install - the directory missing would mean that it can't locate the configuration file which is under /etc/setoolkit/set.config

**Comment by MAHDI00032** [comment]
I tried :
python setup.py install
Installed but the same error😓😓

**Comment by albeniraouf** [comment]
@MAHDI00032
What software are you using

**Comment by MAHDI00032** [comment]
hi i forgot this problem... i now in a wrong way i dont know what should i
do i became crazy...

i just need a kali linux or etc
my android is 4.4.2 i 30 days tried to install kali in my andtoid but i
couldnt. i now trying to get linux vps ... and install SET ... please help
me give solushen ... your team is prophet ... help me guys...;((((

**Comment by albeniraouf** [comment]
you can use Limbo "PC Emulator QEMU ARM x86" application with any linux distributions (kali linux in your case) iso file it works like a sharm for Android 4.2+ 
And if you don't have space you can download the light version of kali from here https://www.kali.org/downloads/

**Comment by MAHDI00032** [comment]
Yes your right ... thanks a lot .
But when i coudnt boot the kali with iso file i uninstall the limbo pc
emulator
And now i cant install it again

Can i install it using Bochs app?
Is it root required ?
Where can i download the iso file?

Thanks a world🤗🤗

در تاریخ پنجشنبه ۱۱ آوریل ۲۰۱۹،‏ ۷:۳۱ Raouf Albeni <notifications@github.com>
نوشت:

**Comment by albeniraouf** [comment]
Okay. First why can't you install it again? 
Second To be honest I never tested or used "bochs app"
Third in the limbo emulator no root needed
But in Bochs I don't know 'cause I never used it
Fourth you can download the iso file from the Link
https://www.kali.org/downloads/

**Comment by 2002-2003** [comment]
I am using termux in my android phone so can I use the function site cloner

**Comment by MAHDI00032** [comment]
Hi, I could not install it at that time. I do not know why. Today I checked
and tested my email and I was installed. Thank you so much
If you can get the best iso file you need to download, download it and run
it on the app
thanks again
نتیجه وب حاوی پیوند سایت
مترجم Google
https://translate.google.com › ...
<https://translate.google.com/?hl=fa>
------------------------------
سرویس رایگان Google کلمات، عبارات و صفحه‌های وب را فوراً به زبان انگلیسی و
بیش از ۱۰۰ زبان دیگر ترجمه می‌کند.
------------------------------
مترجم Google <https://translate.google.com/?hl=fa&langpair=en%7Cen>
------------------------------
درباره <https://translate.google.com/intl/fa/about/index.html>
------------------------------
<https://translate.google.com/intl/fa/about/languages/>
------------------------------
<https://translate.google.com/intl/fa/about/forbusiness.html>
------------------------------
نتایج وب
ترجمه متن
<https://dictionary.abadis.ir/translator/>

در تاریخ سه‌شنبه ۱۶ آوریل ۲۰۱۹،‏ ۳:۲۹ Raouf Albeni <notifications@github.com>
نوشت:

**Comment by MAHDI00032** [comment]
Hi, I could not install it at that time. I do not know why. Today I checked
and tested my email and I was installed. Thank you so much
If you can get the best iso file you need to download, download it and run
it on the app
thanks again

در تاریخ سه‌شنبه ۱۶ آوریل ۲۰۱۹،‏ ۳:۲۹ Raouf Albeni <notifications@github.com>
نوشت:

**Comment by AlokHunt** [comment]
Error 
No such file or directory: '/etc/setoolkit/set.config'
