### ISSUE TITLE
[Errno 49] Can't assign requested address

### ISSUE THREAD

**Issue by MDelaney7700** [trustedsec/social-engineer-toolkit#480]
I am currently running setoolkit version 7.7.4 on OS X Sierra. 

When attempting to run the Credential Harvester attack, Tabnabbing attack, or Web Jacking attack, under Website Attack Vectors, an error would be thrown immediately as follows: 

set:webattack>(3, 4 or 5)

 The first method will allow SET to import a list of pre-defined web
 applications that it can utilize within the attack.

 The second method will completely clone a website of your choosing
 and allow you to utilize the attack vectors within the completely
 same web application you were attempting to clone.

 The third method allows you to import your own website, note that you
 should only have an index.html when using the import website
 functionality.
   
   1) Web Templates
   2) Site Cloner
   3) Custom Import

  99) Return to Webattack Menu

set:webattack>(1, 2 or 3)
[-] Credential harvester will allow you to utilize the clone capabilities within SET
[-] to harvest credentials or parameters from a website as well as place them into a report
[-] This option is used for what IP the server will POST to.
[-] If you're using an external IP, use your external IP for this

**[!] Something went wrong, printing the error: [Errno 49] Can't assign requested address**

From what I understand this means that an attempt was made to create a socket with an address that doesn't exist. Is there a configuration setting I'm missing that I need to change?

**Comment by adriancmiranda** [comment]
@MDelaney7700 Probably if you change the port from 0 to another on line [357](https://github.com/trustedsec/social-engineer-toolkit/blob/master/src/core/set.py#L357) should be works

**Comment by yisus5810** [comment]
Thanks @adriancmiranda, I only change the port 0 to 1 in the line you indicated and it worked.

**Comment by romain1T** [comment]
Hey guys !
I'm having the same error with the 7.7.5 version of SET running on Mac OS X Sierra too, i've tried to change the port from 0 to 1, 2, 222 and a few others ports but it always return me with the same error.. do you have any clue on this ?
Thanks !

**Comment by sskriptkiddy** [comment]
@yisus5810  How do you change port ? ( I'm new)

**Comment by yisus5810** [comment]
@sskriptkiddy you must enter on the folder social-engeener-toolkit/scr/core and edit the file set.py on the line 354 as indicated @driancmiranda.

https://github.com/trustedsec/social-engineer-toolkit/issues/480

**Comment by sskriptkiddy** [comment]
@yisus5810  I did XD I found it, Thx anyway

**Comment by indra8** [comment]
how to solve it?...i am still on confusion!!

**Comment by JcQSteven** [comment]
hey ,even i changed my port to 1 or 2 ,but still can't work
