### ISSUE TITLE
Mass Mailer  Stops With no reason

### ISSUE THREAD

**Issue by amiralkizaru** [trustedsec/social-engineer-toolkit#483]
Hello 

I've been using mass mailer for years to send emails , today i tried to send 150 email with my SMTP server it bugs it send 15 mails and stops and i should re-run it again 
The same behavior ...

**Comment by trustedsec** [comment]
I just tested with about 50, it doesn't seem to stop, there could be timeouts in the SMTP server you are using depending. I put a delay in there just to ensure.
