### ISSUE TITLE
Issue with Yahoo Credential Harvester Template

### ISSUE THREAD

**Issue by ezeddie** [trustedsec/social-engineer-toolkit#485]
**Expected Behaviour**

Expect yahoo to be able to send credentials back to SET after clicking submit.

**Actual Behaviour**

Yahoo template loads, however, getting multiple errors "directory traversal attempt detected from 192.168.x.x.   Credentials never make it back to SET.

Google template works and twitter works fine.

**Set Version**
7.7.4
_Set version_

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by usama7628674** [comment]
same here.Google and twitter templates work fine.

**Comment by siza3x** [comment]
same problem
same set version
bt my clone facebook doesnt work :(

**Comment by siza3x** [comment]
facebook template problem

**Comment by trustedsec** [comment]
I've removed these templates as the sites have changed and is no longer relevant.
