### ISSUE TITLE
invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by TheProfessor100** [trustedsec/social-engineer-toolkit#488]
Hello
in HTA attack ...
when I put my host (noip) it doesn't work and shows this message: 
[!] Something went wrong, printing error: invalid literal for int() with base 10: 'XXXX'

XXXX represents my hostname
![noip](https://user-images.githubusercontent.com/34414665/33804124-f16f1bfc-dda6-11e7-8168-baf38bed037d.png)

Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

please help

**Comment by trustedsec** [comment]
You can't use a hostname for reverse_tcp, you would need to specify the reverse_https payload.
