### ISSUE TITLE
Setcore.py check_config

### ISSUE THREAD

**Issue by diakonos073** [trustedsec/social-engineer-toolkit#490]
Hi, 

When running harvester in set I found a minor issue. After changing the set config to redirect to different website after capturing credentials I noticed that the url wasn't redirecting correctly. 

This is because in setcore.py - line 1382, there is a 'split("=")' which will split the url on all '='. This will only work if there is not an '=' in the url. 

To fix this problem, line 1382 in setcore.py should be changed as follows:

\-               line = line.split("=")
\+              line = line.split("=", 1)

Adding in ', 1' will split on the first occurrence of '=', which will result in the desired behavior for all variables pulled from the config file. 

Please let me know if you have any questions or need anything else. Thank you for all of the work that you do on this project and for the security community!

**Comment by trustedsec** [comment]
Fixed, thanks! I'll add a new version out shortly.
