### ISSUE TITLE
Email "stack" bypass

### ISSUE THREAD

**Issue by ILIKEKOALAS123** [trustedsec/social-engineer-toolkit#491]
**Expected Behaviour**

It should have stack bypass: Next sent email should have dot on the end like this: Test Subject. Test Subject.. Test Subject... etc.
And it will display that:
Example <----- (sender)
Test Subject. <----- (Not stacked email without (number))

Example
Test Subject..  (Not stacked email without (number) - other subject)

The target will have 59 emails (other subject) instead of having 1 email with (59) <--- (Email Number)
**Add option in mass email attack "Do you want to use stack bypass?" <Y/N>** (which will add dot in subject to the next sent email)

**Actual Behaviour**

When i do mass email (59 emails) attack to target it's working propely, but it's stacks - the target has:
Example  <----- (sender)
Test Subject (59) <----- (one email with (59) instead of 59 other emails without that thing)

**Set Version**
7.7.4

**Set in Kali**

Everything good. I'm not reporting bugs. It's update idea
**Sorry for bad english. I will be very happy if you add this!**

**Comment by trustedsec** [comment]
Thanks! I'll take a peek.
