### ISSUE TITLE
Harvester Redirect Issue

### ISSUE THREAD

**Issue by ambas23123** [trustedsec/social-engineer-toolkit#492]
**Expected Behaviour**
When I create www.facebook.com phishing harvested page it redirect to my ip 192.168.1.108 and the site obviously crashes for them and I do not get any info. This bug is only on phone. On computer/laptop machine i get the info and they get redirected to www.facebook.com

**Actual Behaviour**

I should get the pass and name from phones too and they should be redirected to www.facebook.com not 192.168.1.108

**Set Version**

_Set version_
7.4.4

**Set in Kali**

Latest

**Comment by trustedsec** [comment]
You can hit file, save as in a browser and clone the webpage that way in order to make the appropriate page. I would also recommend taking a peek at the setoolkit.config option and turn APACHE_SERVER=OFF to ON, that will allow you to use Apache instead of the built in one in Python.
