### ISSUE TITLE
Setoolkit Apache Error Mac OS X El Capitan

### ISSUE THREAD

**Issue by Komandos823** [trustedsec/social-engineer-toolkit#497]
The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:
[*] Looks like the web_server can't bind to 80. Are you running Apache or NGINX?
Do you want to attempt to disable Apache? [y/n]: 
[*] Try disabling Apache and try SET again.
[*] Printing error: [Errno 48] Address already in use

what's going on in this?

**Comment by noobscode** [comment]
Try using this command:
sudo lsof -i tcp:80

depending on what port you use. Then look for the PID number and do:
kill yourPIDnumber

else: you can try and look at you "Activity Monitor" and see if you find anything running with the name nginx or apache.
