### ISSUE TITLE
Can't find SET configuration file

### ISSUE THREAD

**Issue by charliepaks** [trustedsec/social-engineer-toolkit#501]
I need to edit the set configuration file but i can't find it. I hear it's at config/set_config but no such file exists.

I've updated the set version by cloning it from here . It still says my version is 7.7.4 and there's a newer one called 7.7.5 

My kali version is kali-rolling 2017.3

**Comment by trustedsec** [comment]
/etc/setoolkit/set.config :)

**Comment by extd11** [comment]
How do I turn SET listening pot to open for outside connections?
