### ISSUE TITLE
error in setoolkit

### ISSUE THREAD

**Issue by Mickyasd** [trustedsec/social-engineer-toolkit#503]
when i try to do a "Credential harvester" in **"WebAttack"**, i put lhost and the site that i have to clone, but after this, set give me error number 98.

this is the error:

**[*] Looks like the web_server can't bind to 80. Are you running Apache or NGINX?
Do you want to attempt to disable Apache? [y/n]: y
[ ok ] Stopping apache2 (via systemctl): apache2.service.
[*] Successfully stopped Apache. Starting the credential harvester.
[*] Harvester is ready, have victim browse to your site.
[*] Try disabling Apache and try SET again.
[*] Printing error: [Errno 98] Address already in use**

**Set Version**
7.7.5

what i have to do?? pls

**Comment by trustedsec** [comment]
You need to stop whatever is listening on port 80.

**Comment by trustedsec** [comment]
netstat -antp | grep LISTEN

**Comment by pillowz6666** [comment]
I have the same problem but whenever I close or don't close it just rerun everything.

**Comment by newbieehere** [comment]
use the following command to kill the process in port 80
sudo lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill

**Comment by faccboy** [comment]
> 
> 
> use the following command to kill the process in port 80
> sudo lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill

Thanks, that worked for me!

**Comment by AnwarulHQ** [comment]
> use the following command to kill the process in port 80 sudo lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill

thank you so much .. I had the same issue ..n I waste my many time on youtube and other website also ..but their method was wrong...i have tried all the method except your method..
thanks you again..

**Comment by Anstoboydollar** [comment]
I have similar issues  ..and the command didn't work, is there anything I need to check or do before I use the command pls🙏

**Comment by Emdad05** [comment]
> when i try to do a "Credential harvester" in **"WebAttack"**, i put lhost and the site that i have to clone, but after this, set give me error number 98.
> 
> this is the error:
> 
> **[_] Looks like the web_server can't bind to 80. Are you running Apache or NGINX? Do you want to attempt to disable Apache? [y/n]: y [ ok ] Stopping apache2 (via systemctl): apache2.service. [_] Successfully stopped Apache. Starting the credential harvester. [_] Harvester is ready, have victim browse to your site. [_] Try disabling Apache and try SET again. [*] Printing error: [Errno 98] Address already in use**
> 
> **Set Version** 7.7.5
> 
> what i have to do?? pls

I have solved this issue manually by editing a file 😎😎

**Comment by stjohnboy** [comment]
Hi sudo lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill does not work for me and i have this error message: 
[*] Cloning the website: https://login.facebook.com/login.php
[*] This could take a little bit...

The best way to use this attack is if username and password form fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:
[*] Looks like the web_server can't bind to 80. Are you running Apache or NGINX?
Do you want to attempt to disable Apache? [y/n]: y
Stopping Apache httpd web server: apache2.
Stopping nginx: nginx.
[*] Successfully stopped Apache. Starting the credential harvester.
[*] Harvester is ready, have victim browse to your site.
What do i do?

**Comment by mohmmed7373** [comment]
لدي مشكلة  يضهر لي يبدو أن خادم الويب لا يمكنه الارتباط بـ 80. هل تقوم بتشغيل Apache أو NGINX؟
هل تريد محاولة تعطيل Apache؟ [y/n]: y
