### ISSUE TITLE
Resolve dependencies Dont work on Debian 9.1   

### ISSUE THREAD

**Issue by JaviDBG** [trustedsec/social-engineer-toolkit#505]
> THIS COMMAND DONT WORK ON DEBIAN 9.3:

```
$ apt-get --force-yes -y install git apache2 python-requests libapache2-mod-php \
  python-pymssql build-essential python-pexpect python-pefile python-crypto python-openssl
```

> and the dependences dont install:

```
The python-pymssql package is not available, but some other package makes reference
to the. This may mean that the package is missing, obsolete or only
find available from some other source

E: The "python-pymssql" package does not have a candidate for installation
```

> on set run this warning is present:

```
[!] The python-pycrypto python module not installed. You will lose the ability for encrypted communications.

[!] The python-pycrypto python module not installed. You will lose the ability to use multi-pyinjector.

```
# **How can I fix it?**

**Comment by L1ghtn1ng** [comment]
You do not need to force it and the package will be python2-pymssql

From: JaviDBG
Sent: Wednesday, 31 January, 06:53
Subject: [trustedsec/social-engineer-toolkit] Resolve dependencies Dont work on Debian 9.1 (#505)
To: trustedsec/social-engineer-toolkit
Cc: Subscribed


THIS COMMAND DONT WORK ON DEBIAN 9.1:
$ apt-get --force-yes -y install git apache2 python-requests libapache2-mod-php \ python-pymssql build-essential python-pexpect python-pefile python-crypto python-openssl
and the dependences dont install:
The python-pymssql package is not available, but some other package makes reference to the. This may mean that the package is missing, obsolete or only find available from some other source E: The "python-pymssql" package does not have a candidate for installation
on set run this warning is present:
[!] The python-pycrypto python module not installed. You will lose the ability for encrypted communications. [!] The python-pycrypto python module not installed. You will lose the ability to use multi-pyinjector.
How can I fix it?
