### ISSUE TITLE
Enhancement Proposal: Don't require root to run the app

### ISSUE THREAD

**Issue by IonoclastBrigham** [trustedsec/social-engineer-toolkit#508]
## Motivation

For numerous reasons, it is desirable to be able to avoid running SET as root, except/until such a time as the specific task being executed absolutely requires it. That subprocess could then be launched with `sudo`, or if in pure python privs could be escalated temporarily or the interpreter re-exec'd.

In support of this, as a first step I have [created a branch](https://github.com/IonoclastBrigham/social-engineer-toolkit/commits/config-loading) that moves the generation of `set_config.py` from `/etc/setoolkit` to `~/.set/`, among other improvements. Once initial install and perhaps a single initial run as root makes sure all the correct directories and files are distributed in appropriate locations, you can start it up, get into the menu, and all the expected config values are correctly imported.

## Discussion

Config loading is just a first step, and ultimately the greater goal may require further work in various pieces across the app to make it an acceptable and self-consistent user experience. That is to say, in cases where you actually do need root, at the very least it should prompt you to exit and re-run with sudo.

There are numerous ways we could support the top level goal. Because I'm not sure where exactly to go from here, I haven't created a PR yet for the branch linked above. Here are a few of my ideas. Some of them may be mutually exclusive or redundant.

* Keep most of the changes made thus far in the config refactor branch, but...
    * Reinstate the root check at startup, unless...
    * The user launches with the `--no-root` option (or possibly, assume no-root by default unless the user includes `--root` option, which could do the check and request root access from system if it doesn't have it)
* Any commands that require root could make the check prior to execution time, and optionally escalate privs for the user with password prompt
* All commands could go through a root-aware wrapper, which could catch `OSError`s with `.errno == 13` ("Access denied"), do the root check at that point, and then optionally escalate privs for the user with password prompt

I'd like to see some discussion below regarding this line of pursuit. I can do most/all of the work myself, but the changes will end up touching a good deal of the code in possibly non-trivial ways, so some thought should be put into this. Feedback from the author and/or other experienced contributors especially desired.

Even if we don't think root-less operation is ultimately desirable for most users, the branch linked above definitely has a lot of useful improvements and bugfixes regarding config loading. Once we know where we're heading, I can adjusted as needed to submit that as a formal PR.

## Set Version

_HEAD_ on github

**Comment by trustedsec** [comment]
This would require a pretty substantial rewrite, the config isn't anywhere near as far as location what requires root, we have socket binding, apache modifications, web server startups, and a number of others - pretty much each attack vector would require root, even generation of payloads. While I can see the benefit in this as far as best practices - I'm not aware of anything as far as a security exposure this would create since all of the attacks and its success would require root permissions to launch.
