### ISSUE TITLE
Modules Missing in SET

### ISSUE THREAD

**Issue by Dogren** [trustedsec/social-engineer-toolkit#509]
# PROBLEM:

For some reason whenever I try to use any of the options, it gives me the same message, that there are no modules. I have followed atleast 20 different types of tutorials following each one but for some reason I have no modules. 

For example, when I try to do site cloning it tells me "no module found webattack:web_cloning.cloner" and it does that for everything I try to do, no matter how many times I try to redownload it and try again.

**Comment by trustedsec** [comment]
What are you using for an operating system?
