### ISSUE TITLE
Web cloner not working

### ISSUE THREAD

**Issue by Eureka09** [trustedsec/social-engineer-toolkit#515]
Hi, I want use site cloner tool but I have this message : 

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:

I have the new version of setoolkit. I haven't something running on port 80. 
I write my external ip for this, and when I go on web with my external ip it's not work, I have my internet box. 
But when I put my private ip it's work I can go to my private ip and see the site cloned.  But something wrong because when I return on setoolkit I don't see password but some lines coded 

If you have a solution thanks.

(sorry for my english i'm french)

**Comment by usama7628674** [comment]
What is your os?which site you tried to clone?when you use your external ip in browser did it redirect you to default gateway?

**Comment by Eureka09** [comment]
Linux Debian
Facebook for test or gmail 
Yes when I use my external ip on my browser it's redirect on my gateway

**Comment by usama7628674** [comment]
@Eureka09 The pass and email should be in lines coded just search email in terminal for external ip use ngrok

**Comment by usama7628674** [comment]
Look #513

**Comment by trustedsec** [comment]
You need to specify your external IP address, not your NAT address. When doing a POST request, the browser doesn't understand an internal IP address (non rfc 1918), it needs the external IP address of your host, and that IP must be port forwarded if you are in a NAT situation to the harvester box.

**Comment by sushil40** [comment]
Setoolkit credentials harvestig page not redirected

- - [09/Jun/2022 16:57:56] "POST /ajax/bz?__a=1&__ccg=GOOD&__comet_req=0&__csr=&__dyn=7xe6Fo4OQ1PyUbFuC1swgE98nwgU6C7UW3q327E2vwXx60kO4o3Bw5VCwjE3awbG782Cw8G1Qw5MKdwnU1oU884y0lW0SU2swdq0Ho2ewnE3fw5rwSyE1582ZwrU&__hs=19152.BP%3ADEFAULT.2.0.0.0.&__hsi=7107254964593452881-0&__req=2&__rev=1005657341&__s=5am7rd%3Asbornt%3Am2r8og&__spin_b=trunk&__spin_r=1005657341&__spin_t=1654786748&__user=0&dpr=1&jazoest=2828&lsd=AVrY1h5UA-I HTTP/1.1" 302 -
