### ISSUE TITLE
SMS Spoof Not Working (Help!)

### ISSUE THREAD

**Issue by ColeShelly** [trustedsec/social-engineer-toolkit#517]
This module is currently disabled as spoofmytextmessage.com is currently experiencing issues. As soon as it is working again or I can rework the module, this will remain disabled.

I Updated the Social-Engineer Toolkit (4) and the SET Configuration (5).. Still Doesn't Work..

(Please Help!)

~Cole

**Comment by NIGHTMARE06** [comment]
Same problem :disappointed:
