### ISSUE TITLE
Credential Harvester - Not redirecting

### ISSUE THREAD

**Issue by Francis75848** [trustedsec/social-engineer-toolkit#518]
**Set Version**
7.7.5

Hello.
I'm using SET with ngrok.
All is working fine when accessing the URL generated by ngrok > I get the credentials.
Still, the user is not redirected to the genuine website (e.g. Facebook). 
I turned AUTO_REDIRECT to ON and also tried with HARVESTER_REDIRECT to ON. No positive results.

Is there anything I've been missing ?
Thanks

**Comment by trustedsec** [comment]
I tested with HARVESTER_REDIRECT to ON and HARVESTER_URL, redirects properly..

**Comment by AshishSindhu** [comment]
SET Version 8.0.3 

I'm using SET with ngrok. But it is not redirecting to original page after victim puts credentials.

**Comment by sushil40** [comment]
Credential Harvester - Not redirecting #302
(IP address) - - [09/Jun/2022 16:57:56] "POST /ajax/bz?__a=1&__ccg=GOOD&__comet_req=0&__csr=&__dyn=7xe6Fo4OQ1PyUbFuC1swgE98nwgU6C7UW3q327E2vwXx60kO4o3Bw5VCwjE3awbG782Cw8G1Qw5MKdwnU1oU884y0lW0SU2swdq0Ho2ewnE3fw5rwSyE1582ZwrU&__hs=19152.BP%3ADEFAULT.2.0.0.0.&__hsi=7107254964593452881-0&__req=2&__rev=1005657341&__s=5am7rd%3Asbornt%3Am2r8og&__spin_b=trunk&__spin_r=1005657341&__spin_t=1654786748&__user=0&dpr=1&jazoest=2828&lsd=AVrY1h5UA-I HTTP/1.1" 302 -

**Comment by NeaxArts** [comment]
Someone fixed that? I cloned a WordPress login site and when I send the login information it directs me to a /wp-admin page, which does not exist, I would like it to direct me to the /wp-login.php page that does exist, can someone help?
