### ISSUE TITLE
mass mailer demanding END command over and over !!!!!!

### ISSUE THREAD

**Issue by reeky1706** [trustedsec/social-engineer-toolkit#521]
mass mailer demanding END command after typing body off the message and typing END severally !!

Your gmail email address:jimmytaijeron@gmail.com 
set:phishing> The FROM NAME the user will see:kkk
Email password: 
set:phishing> Flag this message/s as high priority? [yes|no]:n
Do you want to attach a file - [y/n]: n
set:phishing> Email subject:dnrig
set:phishing> Send the message as html or plain? 'h' or 'p' [p]:p
[!] IMPORTANT: When finished, type END (all capital) then hit {return} on a new line.
set:phishing> Enter the body of the message, type END (capitals) when finished:febfueg
Next line of the body: END 
Next line of the body: END 
Next line of the body: END 
Next line of the body: END 
Next line of the body: END 
Next line of the body: 
please tell me what to do asap! thanks !

**Comment by trustedsec** [comment]
That looks like an extremely old version of SET as it's not prompting to use inline files.  I used the latest version and attempted to recreate and using END works find.

**Comment by reeky1706** [comment]
Hi there and thanks for your reply....took a while though lol
I actually twitted @ you
I’m using the latest version of set because I did an update from github but
the bug still persist

**Comment by trustedsec** [comment]
With 7.7.6, I'm able to use either an imported list, or single mail address and when selecting END, it delivers appropriately. Tested on Kali and Ubuntu.

In your example:

"set:phishing> Flag this message/s as high priority? [yes|no]:n
Do you want to attach a file - [y/n]: n
set:phishing> Email subject:dnrig"

The do you want to attach a file, it should be asking for an inline file after - this version is almost a year or two old.

**Comment by reeky1706** [comment]
In essence what should I do to solve this problem And the steps as well I’m
a newbie and will like to be guided right please ...thanks

**Comment by trustedsec** [comment]
git clone https://github.com/trustedsec/social-engineer-toolkit set/

python setup.py

Install to use the latest version.

**Comment by reeky1706** [comment]
Ok thanks for your support will get back to you if need be
I appreciate!

**Comment by reeky1706** [comment]
Hello I have installed the new set but unfortunately it still does same
thing
Doesn’t it work when sending with gmail ?
