### ISSUE TITLE
Kali Linux credential harvester stops loading

### ISSUE THREAD

**Issue by Maxterino** [trustedsec/social-engineer-toolkit#522]
Hello!

I have a problem with the SET-Toolkit.

I run this in a virtual box on a normal Windows 10 system (windows 10 is in test modus)

When i want to make a credential harvester it asks me to fill in some information. When im finished, i need to fill in the url of the website it just keeps loading. I waited a long time but nothing is happening. I tried it with diffrent sites but none of them is working. 

Can someone help me please? If you need more information about my system for example, just ask!

Thanks!!

**Comment by ColeShelly** [comment]
Victim needs to go on to that website using the Host IP address you used.

**Comment by Maxterino** [comment]
You mean my IP or the IP of website or something like that?

**Comment by ColeShelly** [comment]
Both, You use your IP host to host that website, so if you type your IP in the Search Bar on the internet.. I believe any search engine.. it will take you to the url you that you used to attack
