### ISSUE TITLE
SET does not work with sites that use AngularJS

### ISSUE THREAD

**Issue by joseph-ntl** [trustedsec/social-engineer-toolkit#523]
**Expected Behaviour**

Site clone works as intended, cloned site captures credentials.

Using Website Attack Vectors > Credential Harvester Attack Method > Site Cloner

Example Sites: 
Tutorial: http://jasonwatmore.com/post/2015/03/10/angularjs-user-registration-and-login-example-tutorial

**Actual Behaviour**

POST requests are not captured, or site is unable to be cloned.

**Set Version**

7.7.5

**Comment by trustedsec** [comment]
You can save the site in browser format with html, then import it into SET. Since SET uses python to rip the site, for handling sites it can be problematic if it can't find the post parameters.
