### ISSUE TITLE
Hello Possible solution to this problem

### ISSUE THREAD

**Issue by muhommadalmusawi** [trustedsec/social-engineer-toolkit#526]
I installed the offices but the script did not work
Please answer

-------------------------------

python fsattacks.py
Traceback (most recent call last):
  File "fsattacks.py", line 51, in <module>
    from src.core.setcore import *
ImportError: No module named src.core.setcore

**Comment by trustedsec** [comment]
You can't fun fsaattacks.py directly, you would need to use it through the SET launcher (setoolkit).
