### ISSUE TITLE
Https problems(Apache2) on credential harvestor

### ISSUE THREAD

**Issue by harshil2105** [trustedsec/social-engineer-toolkit#528]
I am using Apache2 server to harvest credentials via setoolkit.......I bought a https domain and was using it for credential harvesting but....as soon as I start using setoolkit credential harvestor on a https server,I loose my green secure sign of my domain

**Comment by trustedsec** [comment]
You need to edit /etc/setoolkit/set.config and turn APACHE_SERVER to ON. Then need to configure Apache to use HTTPS. Second, if you are cloning a site, check out /var/www/html and grep for http://, that would cause the site to not sure up as green.
