### ISSUE TITLE
SMS Spoofing Attack Vector  error: global name 'setdir'

### ISSUE THREAD

**Issue by slyther21** [trustedsec/social-engineer-toolkit#53]
I'm using newest SET 5.4.7  and have had this problem for a long time but got out of linux for months and now back in it and even after so many updates its still there, and just wanted to inform you. I have never try this ever, and would be very interested in experimenting with it on my phone.
I'm running Kali Linux

heres what i did when i opened setoolkit

1) social-enginieerinig attacks
7) SMS spoofing attack vector
1) perform a SMS spoofing attack
1. SMS attack singe number

single SMS attack
set:sms> send sms too: 7249880000
1. pre-defined Template

set:sms> use a predefined template or craft a one time SMS?:1

[!] Something went wrong, printing the error: global name 'setdir' is not defined

**Comment by rish67** [comment]
I am using kali linux 2.0 and i have replaced setoolkit files with setoolkit5.4.8 version now it is showing sms spoofing attack vector but when i send the email an error is coming.

**Comment by L1ghtn1ng** [comment]
You need to be using kali 2016.1 rolling as that version of kali is not supported anymore, I advise you to download a new ISO and do a clean reinstall
