### ISSUE TITLE
Setoolkit Credential Harvester error. [Errno -2]

### ISSUE THREAD

**Issue by whynox** [trustedsec/social-engineer-toolkit#539]
Hi,
When i try and use the credential harvester i get this error,
[!] Something went wrong, printing the error: [Errno -2] Name or service not know.
How can this be fixed? 

I use the latest version of kali linux (2018.2) on a vbox.

**Comment by trustedsec** [comment]
1, looks like old version, 2. would recommend installing apache, apt-get install apache2 - which is installed by default, may have been removed.

**Comment by whynox** [comment]
I couldn't because I was without internet in kali for some reason, even saying that I was with internet. Anyway the problem was solved, thanks.
