### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by slyther21** [trustedsec/social-engineer-toolkit#54]
About SMS Spoofing.

sms_launch.py    i update the new lines for 5.4.8 and now i get the templates, and have couple questions.
1. SohoOS (buggy)   What is it? and i get "Error while sending SMS"   (every-time)
   It could be from my end, not sure.  It would be very cool to be more verbose.
2. Android Emulator (need to install Android Emulator) do i have to edit any files for it to work. 

Thanks, Syther21

**Comment by ThatGuy018277** [comment]
Heyy slyther21 let's talk about it..
