### ISSUE TITLE
SD to teensy attack (deploy any exe)

### ISSUE THREAD

**Issue by saurabh185** [trustedsec/social-engineer-toolkit#541]
**Expected Behaviour**
Something went wrong, printing the error: '\n BlinkFast(2);\n delay(5000);\n CommantAtRunBar(

**Actual Behaviour**

Actually this should create .ino file 

**Set Version**

_Set version_

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by trustedsec** [comment]
Fixed this, git pull for the latest. Thanks!
