### ISSUE TITLE
Sendmail not found on macOS High Sierra

### ISSUE THREAD

**Issue by robingoth** [trustedsec/social-engineer-toolkit#543]
**Actual Behaviour**

Set cannot find _sendmail_ on macOS because the path to _sendmail_ is hardcoded in _src/phishing/smtp/client/smtp_client.py_.

Current code:
```
if not os.path.isfile("/etc/init.d/sendmail"):
    pause = input("[!] Sendmail was not found. Install it and try again. (For Kali: apt-get install sendmail-bin)")
sys.exit()
```
**Workaround**
`ln -s '/usr/sbin/sendmail' '/etc/init.d/sendmail'`

**Set Version**

7.7.8

**Comment by trustedsec** [comment]
placed a fix in 7.7.9, thanks!
