### ISSUE TITLE
setoolkit stoped getting usrname and password when using website cloning

### ISSUE THREAD

**Issue by nero0sy** [trustedsec/social-engineer-toolkit#544]
hello everyone 
i was using SET and it all worked fine next day i tried to use it again but it just stopped getting the username and password
this happens only when using it over WAN with ngrok, otherwise it still working on LAN
and this is what I'm keep getting , i am using it to clone facebook
 [*] WE GOT A HIT! Printing the output:
PARAM: __a=1
PARAM: __be=-1
PARAM: __dyn=5V8WXBzamaUCUx2u6Xolg9odpbGEW8yExLFwgoqwWhE98nwgUaqwHx24UJi28rxuF98ScDKuEjKewExaag4idxK4ohyUCq78nyogKcx2785S9wUx66E4G26251G7Utwo8G2Z0aiu4pHxCq2qFoy6o5-3mbwExu68K13x3xGfxu8Cx6789E-dgoV8O2V7yolwPxeiaz8-mUpzUryEqz9E4e4qwg8ixuui5bAw
PARAM: __pc=PHASED:DEFAULT
PARAM: __req=3
PARAM: __rev=3977590
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: lsd=AVoA25uv
PARAM: ph=C3

i noticed that it starts receiving  infos when i click on the username or password boxes but it doesn't get the entered data
can you help me please ?

**Comment by trustedsec** [comment]
Unable to reproduce - able to harvest creds
