### ISSUE TITLE
File empty harvester

### ISSUE THREAD

**Issue by Jubileuhacker** [trustedsec/social-engineer-toolkit#545]
**Expected Behaviour**

I hope I can see the credentials

**Actual Behaviour**

I can not see the credentials, the harvester file is blank

**Set Version**

Version 3.28.0

**Set in Kali**

```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````

**Comment by trustedsec** [comment]
Unable to reproduce, creds are posted to file properly when using built in server and apache
