### ISSUE TITLE
sms spoofing

### ISSUE THREAD

**Issue by hitbond** [trustedsec/social-engineer-toolkit#552]
when i try to use sms spoofing an error showing like this
"Spoofmytextmessages.com no longer works and spoofs messages. Until this is fixed, this module is disabled"
help me

**Comment by L1ghtn1ng** [comment]
Hi, there is nothing that can be done as it is out of dave's control

**Comment by trustedsec** [comment]
If /etc/setoolkit/set.config isn't there - you didn't run setup.py to install :)

**Comment by hitbond** [comment]
Can u give me the instructions for that im new to this sry for the trouble

**Comment by hitbond** [comment]
Thanks for the rply

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 12, 2018 at 5:40 PM, J.Townsend<notifications@github.com> wrote:   Hi, there is nothing that can be done as it is out of dave's control

**Comment by ekovegeance** [comment]
setoolkit Verison 8.0.3 there is no menu sms spoofing

**Comment by vaibhav-rm** [comment]
Then how do I use that freature now?

**Comment by horllste** [comment]
generate the link and use any sms service provider to send it to your targets

**Comment by vaibhav-rm** [comment]
> generate the link and use any sms service provider to send it to your targets

Can you explain briefly please???

**Comment by vaibhav-rm** [comment]
> Can u give me the instructions step by step for installing the setoolkit in my termux.
> im new to this
> sry for the trouble

You can just search for setoolkit termux version on github

**Comment by joeyfigaro** [comment]
> generate the link and use any sms service provider to send it to your targets

Feature is no longer available.
