### ISSUE TITLE
ERROR: invalid syntax (harvester.py, line 598) | While trying to clone Google (Manjaro)

### ISSUE THREAD

**Issue by Jakub1310** [trustedsec/social-engineer-toolkit#555]
**Expected Behaviour**

It is supposed to clone the website

**Actual Behaviour**

SET throws an error `invalid syntax (harvester.py, line 598)`
It throws after selecting a template:
During this process...
```
[*] Cloning the website: http://www.google.com
[*] This could take a little bit...
```

**Set Version**
7.7.8
_Set version_

If it helps I am using 'manjaro linux'

**Comment by lokeshganesh** [comment]
Ian also using manjaro it gives me the same error when cloning Facebook for credential harvester method it shows 
Something went wrong, printing the error : invalid syntax (harvester.py,line 598)

**Comment by mxsadegh** [comment]
i run setoolkit from source and i had same problem and using "python" (python version 2) instead of "python3" worked for me
