### ISSUE TITLE
Tabnabbing is not working because source.js is missing

### ISSUE THREAD

**Issue by mangow** [trustedsec/social-engineer-toolkit#557]
**Expected Behaviour**

Tabnabbing works because it loads index.html, source.js and index2.html on the server.

**Actual Behaviour**

source.js is not uploaded on the server, so tabnabbing does not work since the javascript which is necessary for tabnabbing is missing. 

**Set Version**

_7.7.8 Blackout_

**Set in Kali**

I use the newest version of Kali. I reinstalled set 2 times, tried editing some files, but nothing helped yet.

**Comment by trustedsec** [comment]
Can confirm. Have fixed in latest release.

**Comment by mangow** [comment]
It does work when using the apache server. Not the standard python one. :)

**Comment by flakpaket** [comment]
`src/webattackes/harvester/harvester.py` needs the following inserted at line 277:
```python
            # used for source.js
            elif self.path == "/source.js":
                self.send_response(200)
                self.send_header('Content_type', 'application/javascript')
                self.end_headers()
                fileopen = open(userconfigpath + "web_clone/source.js", "r")
                for line in fileopen:
                    self.wfile.write(line)
                # write out that we had a visit
                visits.write("hit\n")
```
