### ISSUE TITLE
Mass mailer not attaching pdf as inline file

### ISSUE THREAD

**Issue by pukingsheath** [trustedsec/social-engineer-toolkit#558]
My setoolkit mass mailer is not attaching pdf files when i mail them. As a matter of fact, it does not deliver at all when i attach a pdf file as. I have done all updates and upgrades

sudo apt-get update
sudo apt-get dist-upgrade

i am using the most recent kali.

Please what might be the cause??

**Comment by trustedsec** [comment]
Could be getting snagged by AV, I just tested PDF appears to work.
