### ISSUE TITLE
Setting DNS Name instead of IP adress in cloned site

### ISSUE THREAD

**Issue by DocKali** [trustedsec/social-engineer-toolkit#561]
Hi everyone,

I think this question as already been asked but I didn't find the answer by myself.

I would like to specify a domain name (that I had purchase before) and use it instead of an IP adress to link to the clone site. It is possible with SET or did I search for another tool?

Thank you for your help!

**Comment by trustedsec** [comment]
There isn't a problem with that, you can use a domain name instead of IP.
