### ISSUE TITLE
issue in webattack

### ISSUE THREAD

**Issue by Rks11** [trustedsec/social-engineer-toolkit#565]
**Expected Behaviour**

Put here what the expected behaviour should be when reporting an issue

**Actual Behaviour**

Put here what the actual behaviour should be when reporting an issue

**Set Version**

_Set version_

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by Rks11** [comment]
Hi Everyone,
I need help. I have imported  Kali linux latest VMversion inside Vmware. While trying to select any of the options under Webattack 


"[!] Something went wrong, printing the error: [Errno -2] Name or service not known"

Not sure what I am doing wrong. Any of the 3 options is showing the error. Please help.

Regards,
Rks
![webattack_error](https://user-images.githubusercontent.com/28613709/44298140-23728980-a2fb-11e8-8e6c-c57745484d55.JPG)

**Comment by L1ghtn1ng** [comment]
@Rks11 Please make sure you follow the issue guidelines then report back

**Comment by Rks11** [comment]
@L1ghtn1ng : Sorry but not sure what mistake have I committed  both while using in Kali and while reporting. Please help since I am stuck.

**Comment by trustedsec** [comment]
I can't see what attack method you are using, let me know and I can take a peek

**Comment by Rks11** [comment]
I am using webattack. 
I am stuck. Please help.
