### ISSUE TITLE
[Not an issue] spoofmytextmessage.com back up

### ISSUE THREAD

**Issue by swagskillsup** [trustedsec/social-engineer-toolkit#569]
Hello!,
This isn't an issue. In fact, it's a good thing the website is up. Please may you remake/reprogram the SMS Spoofing Attack Vector (in setoolkit first 1 then 10). This is just a friendly reminder! ;-D

**Comment by trustedsec** [comment]
The site might be up, but it doesn't actually spoof text messages unless it was fixed which I don't believe it has been..
