### ISSUE TITLE
Credential Harvestor

### ISSUE THREAD

**Issue by BoUgIeMaN** [trustedsec/social-engineer-toolkit#573]
The credential harvestor doesnt run because apparently my port 80 is used by Apache server
this happened right after i updated it to version 7.7.9

**Comment by BoUgIeMaN** [comment]
When i run others modules they say they can't be found i have simply failed to know where the issue is coming from. i seem to be doing everything the way i am supposed to

**Comment by trustedsec** [comment]
service apache2 stop
