### ISSUE TITLE
[!] Something went wrong, printing the error: No module named 'cStringIO'

### ISSUE THREAD

**Issue by wdjpng** [trustedsec/social-engineer-toolkit#576]
**Expected Behaviour**

The dialog should just bring me to "Mass Mailer Attack"

**Actual Behaviour**

The program just throws the exception above.

**Set Version**

The newest one (I've just installed it an hour ago.)

I use Antergos Linux.

**Comment by trustedsec** [comment]
Would assume you are using Python3 here - give python2 a whirl for now, I can rewrite this section but StringIO is gone in Python3 and is replaced with io.
