### ISSUE TITLE
Cloning looking like Dog Shit

### ISSUE THREAD

**Issue by Ajgeorge** [trustedsec/social-engineer-toolkit#579]
**Expected Behaviour**

Mirror image cloning

**Actual Behaviour**

Poorly made rip off of the actual website which looks like it was done by a web developer who watched 1 hour of lectures and decided he was good enough. 

**Set Version**

7.7.9
**Set in Kali**

7.7.9

**Comment by Ajgeorge** [comment]
I have attempted custom imports also. To no benefit.

**Comment by trollmad3** [comment]
Having the same problem.
