### ISSUE TITLE
Gmail account for the email attack

### ISSUE THREAD

**Issue by yodel232** [trustedsec/social-engineer-toolkit#596]
The gmail account i used to make the single attack with  the **setoolkit** appears in the email that is recived by the victim ..
this choice
`1. Use a gmail Account for your email attack.`

example:
alert@gmail.com < <jerk.kwerl12@gmail.com> >

this clarifies to the victim that i am the sender and it shows the real sender..
Please help me with any solutions !!!!!

**Comment by deadfishhackers** [comment]
the owner ignores us

**Comment by DulyHub** [comment]
Yep!
I mean... you can choose the 2nd option but you need to buy a server :/

Imagine I buy a Server...it will called be ahmmm.... "set"  so.. 

ServerUser and Password 
EXAMPLE
---User: Johny@set.com 
---Pass: 1234

Then SET will need your:
Smtp (Simple Mail Transfer Protocol) "SET use SMTP  as default" 

Example

---smtp.set.com     When you buy a Server you will see your SMTP and POP3 configurations but its like smtp."your name server".com
---Password: 1234   SMTP have password to...I dont remember if SET need it but dont worry its almost the same as your user
---Port: 25     The same with the port... when you buy a Server you will see your default port for SMTP and POP3 

Have a nice day :)

**Comment by labuboco** [comment]
How to send HTML format email?
