### ISSUE TITLE
Why CentOS system can't install SET?

### ISSUE THREAD

**Issue by rootgrandfather** [trustedsec/social-engineer-toolkit#597]
**Expected Behaviour**

The SET can be installed on my CentOS system.

**Actual Behaviour**

When I tried to install SET on CentOS system by command "python setup.py install",it reported me an error:
[*] Installing dependencies...
[!] You're not running a Debian, Fedora or Arch variant. Installer not finished for this type of Linux distro.
[!] Install git, python-pexpect, python-crypto, python-openssl, python-pefile manually for all of SET dependancies.
However,I had installed all the dependency successfully by the command written in README.md,and python packages in requirements.According to the README.md ,CentOS is also a valid system
My CentOS version:
Linux VM_0_15_centos 3.10.0-514.26.2.el7.x86_64

**Set Version**

_Set version_

7.7.9

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by trustedsec** [comment]
I've updated requirements on the installer, should fix this in future.
