### ISSUE TITLE
Why can't i send bold text using Mass Mailer??

### ISSUE THREAD

**Issue by r3x07** [trustedsec/social-engineer-toolkit#598]
help when i send bold text using fake mail it will look like this
``**,hello, *,*``
i put the comma because it will actually bold it on github
but on gmail i did this
**Hello** and it gets sent with the stars

**Comment by 0xInfection** [comment]
GitHub supports markdown, while others don't.

**Comment by deadfishhackers** [comment]
I know html and used syntax <strong></strong> but it won't make the text bold
