### ISSUE TITLE
how to fix this  in kali linux

### ISSUE THREAD

**Issue by shashankdon** [trustedsec/social-engineer-toolkit#602]
you may need to copy /var/www/* into /var/www/html depending on where your directory structure is  problem occurs when setoolkit site cloner is executed

**Comment by testerfr810** [comment]
same problem i tried to reinstall is same any idea ???


ty

**Comment by DulyHub** [comment]
Ok bro lets check...
1st Are you pressing CTRL C when you finish your attack?
2nd The harvest file is in /root/.set//reports and obviusly ".set" folder is hidden so you need to press CTRL and H in /root/.
3rd Don`t touch the /var/www/html folder and just remember. You may need to copy /var/www/* into /var/www/html depending on where your directory structure is.

Have a nice day and if you have other/same trouble ill be here!

**Comment by 5sarad** [comment]
im still having the problem

**Comment by 5sarad** [comment]
> Ok bro lets check...
> 1st Are you pressing CTRL C when you finish your attack?
> 2nd The harvest file is in /root/.set//reports and obviusly ".set" folder is hidden so you need to press CTRL and H in /root/.
> 3rd Don`t touch the /var/www/html folder and just remember. You may need to copy /var/www/* into /var/www/html depending on where your directory structure is.
> 
> Have a nice day and if you have other/same trouble ill be here!

please help me..im still having problem

**Comment by trustedsec** [comment]
This is normal, in APACHE_SERVER=ON the files are under /var/www/ or /var/www/html
