### ISSUE TITLE
!

### ISSUE THREAD

**Issue by SCREAM2017** [trustedsec/social-engineer-toolkit#603]
scream@ADWAA:/mnt/c/users/ad/desktop/TOOLS/social-engineer-toolkit$ setoolkit
Traceback (most recent call last):
  File "setoolkit", line 60, in <module>
    os.makedirs("src/logs/")
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: 'src/logs/'
scream@ADWAA:/mnt/c/users/ad/desktop/TOOLS/social-engineer-toolkit$

**Comment by L1ghtn1ng** [comment]
You will need to run set with sudo in your case

**Comment by trustedsec** [comment]
I've added a better check in the future so you don't get that error message and notifies you need to run as root.
