### ISSUE TITLE
SET sms text disabled

### ISSUE THREAD

**Issue by mikeknap** [trustedsec/social-engineer-toolkit#604]
sms vector still disabled? is it because the spoofmytextmessage cost money? 
i think we would gladly pay then to get rid of the whole thing,

"module is currently disabled as spoofmytextmessage.com is currently experiencing issues. as soon as it is working again or i can rework the module, this will remain disabled." 

i used the spooftextmessage.com site itself. paid for the tokens. it works and send text messages but its doesn't sent it from the number that i want. when will they get it together? its been months/year now

is there a way around it this?

**Comment by trustedsec** [comment]
We have no affiliation with spoofmytextmessage and they won't fix that problem which is why its disabled in SET, sorry.
