### ISSUE TITLE
website clone credential harvester file is missing

### ISSUE THREAD

**Issue by orangelogic** [trustedsec/social-engineer-toolkit#607]
**Expected Behaviour**

Once website is cloned and victim enters credentials, a harvester file is created in the /var/www/html folder with entered credentials.

**Actual Behaviour**

After victim enters credentials no harvester file is ever created.  I've searched the entire computer.

**Set Version**

7.7.9

**Comment by DulyHub** [comment]
Ok bro lets check...
1st Are you pressing CTRL C when you finish your attack?
2nd The harvest file is in  /root/.set//reports   and obviusly ".set" folder is hidden so you need to press CTRL and H in /root/.
3rd Don`t touch the /var/www/html folder and just remember. You may need to copy /var/www/* into /var/www/html depending on where your directory structure is.

Have a nice day and if you have other/same trouble ill be here!

**Comment by 20sidd** [comment]
You may need to copy /var/www/* into /var/www/html depending on where your directory structure is.
What does this mean? Help please!

**Comment by trustedsec** [comment]
This is normal, the files are under /var/ww or /var/www/html
