### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [trustedsec/social-engineer-toolkit#612]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by L1ghtn1ng** [comment]
No it has not it has been something I have been wanting to contribute to resolving but have not had the time to have a look at it yet
________________________________

**Comment by gustavosizilio** [comment]
Ok. Thank you!
