### ISSUE TITLE
Can't update SET (Termux) 

### ISSUE THREAD

**Issue by VoQZHD** [trustedsec/social-engineer-toolkit#613]
[!] Not running a Debian variant..
[!] Not running a Debian variant..
[-] Kali or BackBox Linux not detected, manually updating..
[-] Updating the Social-Engineer Toolkit, be patient...
[-] Performing cleanup first...
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[-] Updating... This could take a little bit...
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by trustedsec** [comment]
Haven't tested on Termux and no current plans to add.

**Comment by noob0192** [comment]
> Haven't tested on Termux and no current plans to add.

Hmu i need knowledge lol im feeling enlightened and know i have the brains to master this i could give credentials not as in coding or programming but iq and scholarship offers but for what i need more please contact me
