### ISSUE TITLE
failed building wheel for cryptography

### ISSUE THREAD

**Issue by Ashbuhrz** [trustedsec/social-engineer-toolkit#618]
Failed building wheel for cryptography                  Running setup.py clean for cryptography               Failed to build cryptography                            Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

**Comment by trustedsec** [comment]
Which OS? Works fine on Ubuntu..

**Comment by angerhang** [comment]
Facing the same issues on Mac OS.
