### ISSUE TITLE
cant find setup.py in the set directory

### ISSUE THREAD

**Issue by aditya-fpv** [trustedsec/social-engineer-toolkit#622]
Expected Behaviour
setoolkit should be succesfully installing in my machne.(ubuntu 18.04

Actual Behaviour

`python setup.py install`
the above installation command gives an error like:
python: can't open file 'setup.py': [Errno 2] No such file or directory

Ive already tried installation using `sudo pip install -r requirements.txt
`

**Set Version**

Downloaded the latest verson just yesterday.

**Comment by Mason-18** [comment]
I'm having this problem too. Can't find any help or solutions, I downloaded it today. Any ideas on solving it would be great. Thanks!

**Comment by mekaielarslan** [comment]
cant find setup.py in st directory
plzz help me

**Comment by fam007e** [comment]
Same problem here

**Comment by Cronuh** [comment]
Still nothing in here? :o

**Comment by DDuffy92** [comment]
I am having same problem no setup.py file.  I looked for it manually and still can't find it followed
instructions using "pip install -r requirements.txt"  says all requirements are installed, still not working.
any ideas?

**Comment by tyler-1987** [comment]
set non work at today man

**Comment by Sun-ishaq** [comment]
same here! can't find the setup file

**Comment by equi-design** [comment]
I'm guessing they don't care about install issues at this point. Can a fellow user help us out? I'm a tech geek & am still experiencing this issue.

**Comment by tyler-1987** [comment]
Ok man! Why SMS spoofing was it erased from tool?


Il dom 2 feb 2020, 17:33 equi_design <notifications@github.com> ha scritto:

**Comment by trustedsec** [comment]
Not that we don’t care - just very busy. About to release a new huge community project. We will take a peek soon.

Also - on SMS spoofing - the third party service integration stopped working and they no longer maintained it.

**Comment by trustedsec** [comment]
Check out 8.0.2, I added a new setup.py which does the install for you. It was removed because it was moved to requirements.txt but I added a quick installer for folks that didn't read the README :)

**Comment by tyler-1987** [comment]
Very good Boyz you are best!!!!

Il mar 4 feb 2020, 02:13 trustedsec <notifications@github.com> ha scritto:
