### ISSUE TITLE
setoolkit 

### ISSUE THREAD

**Issue by aman545** [trustedsec/social-engineer-toolkit#625]
i am new using setoolkit to clone a site but in the last step i cant understand what is it saying....it is saying..-You may need to copy /var/www/* into /var/www/html depending on where your directory structure is.
plaese tell me what to do next..
![image](https://user-images.githubusercontent.com/50523619/57571607-e375a880-742d-11e9-9bc5-976349ec2543.png)

**Comment by pnjn102** [comment]
Facing same issue

**Comment by trustedsec** [comment]
It depends on what version of Linux you are using. Some use /var/www/ or /var/www/html. Depending on what your webroot for apache is setup for, you might need to host it in a different directory.
