### ISSUE TITLE
HTA Attack not working

### ISSUE THREAD

**Issue by Rapt0r445** [trustedsec/social-engineer-toolkit#627]
**Expected Behaviour**

Once clicking the HTA Attack and entering your IP address it should move on to the next part

**Actual Behaviour**

After putting in the IP address and clicking enter it goes back to the main menu every time.

**Set Version**

Version 8.0 Maverick - BETA

**Comment by neerajpandey101114** [comment]
I am facing the same issue.. Did u got some solution to this?

**Comment by trustedsec** [comment]
Fixed and pushed an update in 8.0.1
