### ISSUE TITLE
SSL certificate problem Credential Harvester Attack Method

### ISSUE THREAD

**Issue by Thesamsam** [trustedsec/social-engineer-toolkit#629]
**Expected Behaviour**

Put here what the expected behaviour should be when reporting an issue

The clone site web using apache conf and SSL does not work

1) Social-Engineering Attacks / 2) Website Attack Vectors / 3) Credential Harvester Attack Method / 1) Web Templates
 / Enter 

The certificates used are signed with letsencrypts

I configured the /etc/set/setool.conf configuration file: /etc/setoolkit/set.config

APACHE_SERVER=ON
#
### Path to the Apache web root.
APACHE_DIRECTORY=/var/www/html
#
### need to specify what port Apache is listening on in order for this to work properly.
WEB_PORT=443
...
WEBATTACK_SSL=ON
#
### If you're using this flag, ensure openSSL is installed! Turn SELF_SIGNED_CERT on.
SELF_SIGNED_CERT=OFF
#
### Simply place the path you want. For example: /root/ssl_client/server.pem
PEM_CLIENT=/etc/letsencrypt/live/mydomain.fr/fullchain.pem
PEM_SERVER=/etc/letsencrypt/live/mydomain.fr/privkey.pem

Functional certificates in apache

**Actual Behaviour**

Put here what the actual behaviour should be when reporting an issue

Error : [!] Something went wrong.. Printing error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'file_ctrl', 'system lib'), ('SSL routines', 'SSL_CTX_use_PrivateKey_file', 'system lib')]

**Set Version**

_Set version_

Version: 8.0

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdim
![1](https://user-images.githubusercontent.com/50978152/58304212-ad540380-7df3-11e9-9c8e-ed751d8a2531.PNG)

age.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

I use ubuntu 

thank you for helping me

**Comment by trustedsec** [comment]
With WEBATTACK_SSL=ON is only for when using built in, turn this to off and use apache_server to on.
