### ISSUE TITLE
SE-Toolkit No module named src.core.setcore

### ISSUE THREAD

**Issue by CaptainBlastXD** [trustedsec/social-engineer-toolkit#63]
Here is the whole error message:

Traceback (most recent call last):
  File "/usr/bin/setoolkit", line 27, in <module>
    from src.core.setcore import *
ImportError: No module named src.core.setcore

Anyone know a fix thanks

**Comment by Daenerys24** [comment]
Same problem, have src/core in both usr/share/setoolkit and /opt/set which is where i gitcloned to. Exact same error on the same line. I am using whatever version is newest off of the command git clone https://github.com/trustedsec/social-engineer-toolkit.git set/ I assume as said command was updated Dec 31 its pretty up to date :-/

**Comment by trustedsec** [comment]
Daenerys24 - is this when you first launch SET? I'm not sure what to tell you - I have a brand new flavor of SET loaded on Kali, Ubuntu, and Fedora as an example and launches perfectly fine without the error message in a freshly checked out version of SET from github. Not saying there isn't something wrong, I just can't reproduce any of the issues you are experiencing there. Happy to help out but you'll need to figure out what's different on your system and where this error message is popping up. Are you in a menu when this occurs or when you first launch?

**Comment by Daenerys24** [comment]
I figured it out for some reason alien to me I had lost the original set
probably something I installed but anyway I had to not just run the
installer as it came from git cloning into my /opt but also make in
/usr/share a directory called set to go with the other one (not in kali atm
setoolkit maybe?) It worked fine afterward so go ahead and post that as a
fix or don't either way works perfect

On Jan 16, 2015 8:31 AM, "trustedsec" <notifications@github.com> wrote:
>
> Daenerys24 - is this when you first launch SET? I'm not sure what to tell
you - I have a brand new flavor of SET loaded on Kali, Ubuntu, and Fedora
as an example and launches perfectly fine without the error message in a
freshly checked out version of SET from github. Not saying there isn't
something wrong, I just can't reproduce any of the issues you are
experiencing there. Happy to help out but you'll need to figure out what's
different on your system and where this error message is popping up. Are
you in a menu when this occurs or when you first launch?

**Comment by diablodaz** [comment]
I've just had the same issue. For some reason when you invoke setoolkit from within the git cloned directory it happens:
root@kali:~/social-engineer-toolkit# ls
config   readme     seautomate  setoolkit  seupdate
modules  README.md  seproxy     setup.py   src
root@kali:~/social-engineer-toolkit# setoolkit 
Traceback (most recent call last):
  File "/usr/bin/setoolkit", line 27, in <module>
    from src.core.setcore import *
ImportError: No module named src.core.setcore

And when you invoke it outside of the installation directory  it works fine:root@kali:~# setoolkit 
[-] New set_config.py file generated on: 2015-01-30 10:10:39.820200
[-] Verifying configuration update...
[*] Update verified, config timestamp is: 2015-01-30 10:10:39.820200
[*] SET is using the new config, no need to restart

Copyright 2014, The Social-Engineer Toolkit (SET) by TrustedSec, LLC
All rights reserved.
...

Hopefully this helps.

**Comment by warlockinit** [comment]
SET is causing my bullshit

**Comment by blaxfuq** [comment]
im getting this can any one help here !:
Traceback (most recent call last):
  File "./setoolkit", line 17, in <module>
    import src.core.setcore as core
ModuleNotFoundError: No module named 'src.core.setcore

**Comment by canosaur** [comment]
for all those who got error, run the file as sudo
src is a folder, which requires root previliages to access
thank me later

**Comment by canosaur** [comment]
> im getting this can any one help here !: Traceback (most recent call last): File "./setoolkit", line 17, in import src.core.setcore as core ModuleNotFoundError: No module named 'src.core.setcore

run the it is sudo, thank me later

**Comment by canosaur** [comment]
> im getting this can any one help here !: Traceback (most recent call last): File "./setoolkit", line 17, in import src.core.setcore as core ModuleNotFoundError: No module named 'src.core.setcore

run it as sudo

**Comment by canosaur** [comment]
> im getting this error
> 
> Traceback (most recent call last): File "setoolkit", line 50, in import src.core.setcore as core ImportError: No module named setcore
> 
> just done a fresh install off SET on Mac OSX i typed "sudo python setup.py install" and then "setoolkit" and then comes up with the error when trying to run setoolkit

sudo setoolkit

**Comment by EPiCxRIOTZZ** [comment]
@canosaur any reason why setoolkit is giving python requests no module found error when I have requests installed, tried with pip3 and pip install, yes I have all permissions already for setoolkit

**Comment by canosaur** [comment]
> @canosaur any reason why setoolkit is giving python requests no module found error when I have requests installed, tried with pip3 and pip install, yes I have all permissions already for setoolkit

If it gives an error telling request module not found you might have installed it using pip/pip3. pip3 install requests. And the setoolkit needs to be run as sudo, no matter what permissions have been given. That should work

**Comment by Spideyachu** [comment]
I have that same issue
im getting this can any one help here !:
Traceback (most recent call last):
File "./setoolkit", line 17, in
import src.core.setcore as core
ModuleNotFoundError: No module named 'src.core.setcore
Please some one help

**Comment by Perkins09** [comment]
Traceback (most recent call last):
  File "/usr/share/setoolkit/./setoolkit", line 17, in <module>
    import src.core.setcore as core
ModuleNotFoundError: No module named 'src'

Even after using sudo, it still didn't work.
Any help please?
