### ISSUE TITLE
sms spoofing

### ISSUE THREAD

**Issue by sanjarbek1999** [trustedsec/social-engineer-toolkit#631]
[!] This module is currently disabled as spoofmytextmessage.com is currently experiencing issues. As soon as it is working again or I can rework the module, this will remain disabled.

**Comment by esilshala** [comment]
are you ready to bring back sms spoofing module?

**Comment by eaydin228** [comment]
Having the same problem. Hope to use again.

**Comment by trustedsec** [comment]
Right, the provider doesn't support SMS spoofing anymore. It was removed.
