### ISSUE TITLE
Third Party module not recognised : RATTE 

### ISSUE THREAD

**Issue by Avaar111** [trustedsec/social-engineer-toolkit#634]
Ive verified the other threads speaking about it, one mentionned the issue, but the thread was closed giving a answer for a different issue. Verified on various forums as well looking up the read.me thirdpartymodule text file and the pdf manual, could not figure out was is wrong.

**Expected Behaviour**

The RAT tool should open since it is in the module directory as included in the current SET version, the rat is ratte_module.py but I also have a ratte_only_module.py in the directory.

**Actual Behaviour**

when I try to access it through SET with option 3. (Third party module)  I only see : 
1.Google Analytics Attack by @ZonkSec

And then 99 to return. Therefore unable to access it.

**Set Version**

Version 8.0

**Set in Kali**

Updates were fully manually ran on Kali Linux as advised with the upgrade commands, I have Kali linux rolling and updated. Not quite sure what I'm missing here.

Thanks for any help in advance, sincerely hoping it's not something silly I've missed.
Thanks again,
A

**Comment by trustedsec** [comment]
fixed in the latest release 8.0.2
