### ISSUE TITLE
can't find msf4

### ISSUE THREAD

**Issue by FishNChisps** [trustedsec/social-engineer-toolkit#639]
HELP!!! I've been browsing my files for a while and I still can't find the msf4 folder. I was making a payload for doing a school project, but in the middle of making the payload. it supposedly said that it saved it on /home/fishnchisps/.msf4/local/test.pdf, but I can't find .msf4. please help

**Comment by trustedsec** [comment]
Do you have Metasploit installed? It creates a .msf4 directory for you..
