### ISSUE TITLE
error installing mac osx 

### ISSUE THREAD

**Issue by Burzlurker** [trustedsec/social-engineer-toolkit#643]
Attempting to install to Mac OS X 10.13.16. using either pip or pip3 install -r requirements.txt i get the following error and then dumped back into a command prompt after several packages are downloaded. Any thoughts on how to correct please let me know. The starting https below is the last file it reaches out for and then the errors happen. 

https://files.pythonhosted.org/packages/2e/81/99562b93d75f3fc5956fa65decfb35b38a4ee97cf93c1d0d3cb799fffb99/pymssql-2.1.4.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: /usr/local/lib/python3.7/site-packages/setuptools/dist.py:45: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l3/_q_92ymj1pd_wydw72_vkkpr0000gn/T/pip-install-gvs8dimg/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l3/_q_92ymj1pd_wydw72_vkkpr0000gn/T/pip-install-gvs8dimg/pymssql/

**Comment by pazDontExist** [comment]
$ pip install Cython

**Comment by Burzlurker** [comment]
> first:
> $ brew install freetds
> Second
> $ pip install Cython
> then
> $ pip install -r requirements.txt

Thank you. This did the trick. Thanks for helping a noob...
