### ISSUE TITLE
Credential harvester cloned site does not load

### ISSUE THREAD

**Issue by 20sidd** [trustedsec/social-engineer-toolkit#644]
**Expected Behaviour**

After the website is cloned, the victim presses ip to open the cloned website. 

**Actual Behaviour**
Rather it is not and it just keeps loading until the connection time is out.
i think the issue lies somewhere here:
"You may need to copy /var/www/* into /var/www/html depending on where your directory structure is."
this line appears after the site is cloned. Please mention the command to solve this issue.
Thanks in advance

 

**Set Version**

8.0.1

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	2019.3
![set](https://user-images.githubusercontent.com/53923194/62747290-367eec00-ba6d-11e9-84c9-f0f8287080f1.JPG)

Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by root452** [comment]
I HAVE THE SAME PROBLEM

**Comment by tdog3406** [comment]
Have this been solved?

**Comment by trustedsec** [comment]
This is expected behavior, go to /var/www or /var/www/html to see the files present there when using APACHE_SERVER=ON. All files are stored under /root/.set/
