### ISSUE TITLE
no credentials

### ISSUE THREAD

**Issue by jonesstewart000** [trustedsec/social-engineer-toolkit#645]
every time I use setoolkit with apache set to off in set.config, I get a result but when I set it to on, I don't. 
I get 
"Array
(
) "
it states in the post.php that I need to install php5, I have php7 installed. I went over some already asked questions, you stated that it doesn't matter whether it be php5 or 7, could you help?

**Comment by jonesstewart000** [comment]
hello I asked this question days ago, no reply yet. Please can you help

**Comment by root452** [comment]
directory traversal attempt detected from: 192.168.0.100
192.168.0.100 - - [26/Aug/2019 13:37:01] "GET /hr/xping/?app=m_login&key=AQNBnSfUhfGH3jMoF4R8oLJ_e52M9kB58iNM6xGU7bNmAcSwx0Ng2BUUBMBaTeO1p-614rDTfC40u3Q5GddvBBSInPLm8K1bVC8GeCexynCMAckrlFVYCh9M1FcRaItTgZ_SiOIVhqiL67RYplymUn1yAYeptIsuLhGELUiu7bGkSA&zc=AQNkIMpawQNbxAn6V5ZtMxB-AQNVv-_Rco8M8p6aNrHlN4NDfwOmkE8lZA8h_hh6h0Q HTTP/1.1" 404 -

WHEN I OPEN THE CLONE PAGE THIS SHOWS IN SET.
HELP

**Comment by trustedsec** [comment]
This can happen depending on the site, recommended to visit site in browser, navigate to the site, and then download page and import into SET.
