### ISSUE TITLE
directory traversal attempt detected from: 192.168.0.100 192.168.0.100 - - [26/Aug/2019 13:37:01] "GET /hr/xping/?app=m_login&key=AQNBnSfUhfGH3jMoF4R8oLJ_e52M9kB58iNM6xGU7bNmAcSwx0Ng2BUUBMBaTeO1p-614rDTfC40u3Q5GddvBBSInPLm8K1bVC8GeCexynCMAckrlFVYCh9M1FcRaItTgZ_SiOIVhqiL67RYplymUn1yAYeptIsuLhGELUiu7bGkSA&zc=AQNkIMpawQNbxAn6V5ZtMxB-AQNVv-_Rco8M8p6aNrHlN4NDfwOmkE8lZA8h_hh6h0Q HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by root452** [trustedsec/social-engineer-toolkit#646]
**Expected Behaviour**

Put here what the expected behaviour should be when reporting an issue

**Actual Behaviour**

Put here what the actual behaviour should be when reporting an issue

**Set Version**

_Set version_

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by root452** [comment]
THIS SHOW WHEN I OPEN THE CLONED PAGE

**Comment by trustedsec** [comment]
This can happen based on different sites, recommended to visit via a browser and save the page then use the import option.
