### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by znyperleon** [trustedsec/social-engineer-toolkit#651]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-SePQbR/pymssql/

any ideas some one im new at this

**Comment by dafish7** [comment]
yeah you need to install cython i believe

pip install cython 
and then continue with requirements.txt

**Comment by sudoaza** [comment]
pymssql is discontinued, need to update the requirements.txt with pymssql<3.0

**Comment by johnhenryyeet** [comment]
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-SePQbR/pymssql/
> 
> any ideas some one im new at this
I just updated pip with the following line of code and worked for me: python3 -m pip install -U pip

**Comment by johnhenryyeet** [comment]
I just updated pip with the following line of code and worked for me: python3 -m pip install -U pip
