### ISSUE TITLE
You may need to copy /var/www/* into /var/www/html depending on where your directory structure is.

### ISSUE THREAD

**Issue by 5sarad** [trustedsec/social-engineer-toolkit#653]
while using setoolkit and cloning the website i am getting an error
"You may need to copy /var/www/* into /var/www/html depending on where your directory structure is."
I am getting this error while using setoolkit please help me
please help me

**Comment by bauaaman** [comment]
I also faced same problem

**Comment by Affus** [comment]
no problem just continue because the /var/www it the same as the varwww/html and letting you aware
