### ISSUE TITLE
Email error

### ISSUE THREAD

**Issue by sh1va73** [trustedsec/social-engineer-toolkit#654]
I am trying Single Email attack and finished the settings , but email is not send . It did not arrive. 
EDIT i tried again and its working now. I dont know why first test was not succesful : i my mail settings it says: soft bounce.

**Comment by tdog3406** [comment]
Could you help me out bud?

**Comment by sh1va73** [comment]
> Could you help me out bud?

How can I help you?

**Comment by tdog3406** [comment]
I’m trying to use attack vectors but it not working do yours work

**Comment by sh1va73** [comment]
> I’m trying to use attack vectors but it not working do yours work
> […](#)

I just did a new test and it is working here.

**Comment by tdog3406** [comment]
Ok thanks just wondering because everytime I run it and you know where you
type your ip into the browser to pop up the copy website there is nothing!
It say cannot connect to host

**Comment by sh1va73** [comment]
> Ok thanks just wondering because everytime I run it and you know where you type your ip into the browser to pop up the copy website there is nothing! It say cannot connect to host
> […](#)

It sounds like server issue, is your page in correct directory for server? Are you on local network?

**Comment by tdog3406** [comment]
That what I’m thinking because I get that little message thing that says while
using setoolkit and cloning the website i am getting an error

"You may need to copy /var/www/* into /var/www/html depending on where your
directory structure is." Which I know isn’t a error but I’m not sure if
there a problem that occurs here and when you say local how can I check to
see that  also thanks for the replies !

**Comment by sh1va73** [comment]
> That what I’m thinking because I get that little message thing that says while using setoolkit and cloning the website i am getting an error "You may need to copy /var/www/* into /var/www/html depending on where your directory structure is." Which I know isn’t a error but I’m not sure if there a problem that occurs here and when you say local how can I check to see that also thanks for the replies !
> […](#)

I get the same message, but when I go to :  http://computername:portnumber then the created page opens. I do this in my own network, not outside.

**Comment by tdog3406** [comment]
Thank you I check it out!
