### ISSUE TITLE
SET doesn't install properly on Lubuntu 20.04 Focal.

### ISSUE THREAD

**Issue by royalPanic** [trustedsec/social-engineer-toolkit#657]
**Expected Behavior**
SET installs properly and all tools function.
**Actual Behavior**
The clone listed in the readme.md fails, so I took the actual link to the repo and cloned it in. I cd into the folder, use `pip install -r requirements.txt` as it says. This completes with no errors. Then upon trying to run the toolkit (`setoolkit`) in bash, I get a command not found error, which would seem to imply it failed to install.

**Set Version**

*8.01*

**Comment by trustedsec** [comment]
Try running setup.py on 8.0.2, run setup.py should address
