### ISSUE TITLE
SSL config in latest version causes issue described

### ISSUE THREAD

**Issue by ceramicskate0** [trustedsec/social-engineer-toolkit#658]
Issue similar to #606  Having same issue with not self signed cert and not LetsEncrypt certs. Issue not present 6 months ago (last use). I am also using Apache=On in config (rest of config is similar. OS=ubuntu 18.04. re cloning tool allows it to run but issue causes each clone to not fire again when executed.

Output below:
Traceback (most recent call last):
  File "./setoolkit", line 17, in <module>
    import src.core.setcore as core
  File "Tools/social-engineer-toolkit/src/core/setcore.py", line 8, in <module>
    import socket
  File "Tools/social-engineer-toolkit/socket.py", line 68, in <module>
    from _ssl import \
ImportError: cannot import name RAND_egd

**Comment by ceramicskate0** [comment]
command run before issue occures when exited from setoolkit.py:

[*] You may need to copy /var/www/* into /var/www/html depending on where your directory structure is.
Press {return} if you understand what we're saying here.
[*] Apache is set to ON - everything will be placed in your web root directory of apache.
[*] Files will be written out to the root directory of apache.
[*] ALL files are within your Apache directory since you specified it to ON.
[*] Starting built-in SSL server
[!] Something went wrong.. Printing error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'file_ctrl', 'system lib'), ('SSL routines', 'SSL_CTX_use_PrivateKey_file', 'system lib')]

**Comment by ceramicskate0** [comment]
issue appears identical to issue #629

**Comment by trustedsec** [comment]
Fixed in 8.0.2
