### ISSUE TITLE
SET for 32 bit lubuntu

### ISSUE THREAD

**Issue by peterpies** [trustedsec/social-engineer-toolkit#661]
Is there a 32 bit kit for lubuntu I tried installing using the directions including here but it fails, firstly with crypto wheel failed to build etc and then did not complete build. If there is a different kit where and how do I load it.
Many thanks

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

**Comment by trustedsec** [comment]
Try running python setup.py in 8.0.2
