### ISSUE TITLE
SET doesn't show credentials 

### ISSUE THREAD

**Issue by moshe6524** [trustedsec/social-engineer-toolkit#665]
**Expected Behaviour**

To show me the Email and Password

**Actual Behaviour**

Alot of gibberish but no actual credentials 

**Set Version**

8.0.1

Hi.
I have tried to use SET over WAN with ngrok and localtunnel to forward my port to them.
i get many results. sadly not the credentials i have entered my self.

[*] WE GOT A HIT! Printing the output:
PARAM: __a=1
PARAM: __csr=
PARAM: __dyn=7xe6Fo4OQ1PyUhxOnFwn84a2i5U4e1Fx-ewSwMxW0DUeUhwmU3Mx60Vo1upE4W0OE2WxO0So5u1Qw5MKdwnU1oU881FU3rw
PARAM: __hsi=6764990386559719973-0
PARAM: __pc=PHASED:DEFAULT
PARAM: __req=1
PARAM: __rev=1001480169
PARAM: __s=hwq495:xi3ntd:x9gsr5
POSSIBLE PASSWORD FIELD FOUND: __spin_b=trunk
POSSIBLE PASSWORD FIELD FOUND: __spin_r=1001480169
POSSIBLE PASSWORD FIELD FOUND: __spin_t=1575097066
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: dpr=1
PARAM: jazoest=2722
PARAM: lsd=AVpf5fUu
PARAM: ph=C3
POSSIBLE USERNAME FIELD FOUND: q=[{"user":"0","webSessionId":"hwq495:xi3ntd:x9gsr5","app_id":"256281040558","posts":"uxPwaVtbImdrMl9leHBvc3VyZSIseyJpZGVudGlmaWVyIjoiMTA3MzUwMCIsImhhc2giOiJBVDVVMWY4VzNmcDFEeExtIn0sMTU3NTA5NzE1NjUwNS44NywwLDUwXSxbInJlcXVpcmVfY29uZF8RYxxfbG9nZ2luZ0JrAPBWQWEycnNtOE9oMzA2MEdidTByTVJkTEtYMnkyRTZaYmRZcUtidVY1VnViS3djWlBuR2R4Q1l3cURaYVJNaFJmZFZyaEdWaDNsU1lTUjA2YTkzakY1ZV9rOqEAJDYuNTMsMCwxMDQBonL8ABQ5NDY4OTQu+wA0N25jUDY2OVY2aHZMOElCWgAcNjA1LDAsNDmCWgAUNjc2OTIyLloANDUyYS1LUjhVTTZwenRFRloAIVWeWQAAMC5ZADQ0RGhGVldHTE9zeWx6VDpZAAw4LjkzrrMAADEuWgA0NmVjMzYtLVo2eUU2ZU06WgAMOS42OKZaAAg4MzcyWgAwUE1XTGo1OWN5VG1oczZaABAxMC40NppaABQxMTEzMjQyWwA0NTd2ZHNjYi10VTlsNHA6WwAMMS40NAFbSb5Ec2NyaXB0X3BhdGhfY2hhbmdlQbMUc291cmNlBRYYIjpudWxsLBETEHRva2VuERQIZGVzCTs4IjoiL2xvZ2luLnBocCIsCRkNKxgiYWQ5NzY0JbHwXmltcHJlc3Npb25faWQiOiIwS1JMMUxwODlTZzZJbHRJVyIsImNhdXNlIjoibG9hZCIsInNpZF9yYXciOiJod3E0OTU6eGkzbnRkOng5Z3NyNSIsInJlZmVycmVyIjoiEXoYZWZfcGFnZTKnAHR1cmkiOiJodHRwczovL3d3dy5mYWNlYm9vay5jb20dvgB9LusDKDcwLjA2LDAsMjU1QfC+7APwUjAwcDJxZHhGNEpvVTVXaktFQ0IzSFNVVTJfRExFNlRRb2ZqUDJ3M2JBOTRmQTVKM3lDOVhHM1FiOUVkUnd0dUgwWGpicGRndnp2bmRaYWNMWEciPp8ABDExZekAMQGfcukDGDExODkxNzYugwI0NzE0b3RNSF84LVZNNXc6+gAQMi44MiyR5XJaABQ3Mjk2MjkuWQA0NTVzMmI3cHVUR2pZYVU2WQAMODEuMJ7cAgFaADMy6gM0NVlwM0lZSElScVVRdk1CWgAlDgA0hpwEBVky6QM0NTNrQnlvSDdHdERCa0ZGWQAEMyyS9QQUMTEzMDQ2MvYENDY0dUpQY29pMG1MT2Q1RloAQWBpjXJmAQw2Nzc3NlkANDdJQ2ZwdTF6X0NMY0xrOlkAEDQuNzI1FbQEcmW2pQbwYzMzUFNoTjN4UXQtaHV4Q3RhTTU0MENxcklVZ3BLXzRRRzFMMHdfMzJEM2xwRU1HNHZtTlJ2QnQwTW9zNWN1eEpQUU5WT2g4Z29RTEEifSwxNTc1MDk3MTU2NTg0Ljc1LDAsOTWCsgIUNzA4MjUzLlgCNDRocDZyVGpTMkNfZHp5NvIADDkzLjW96L7yAPBEMXFicHBKeDl1eHFMeTFoRWNtdDd3dTgzV3pvam1sakQxWllFVHNUVzNtU2YxemhyRXdHdGJQVDFRb1R3UlpvYjR4eUhZRpIABewEODgB7CBjbGlja19yZWYSHQgoZXIiLFsiMkZZWSKVcSQ2MTk2MCwiYWN0MhQAMDU4LDAsImVtYWlsIiwJRx0IAC2hBAwiLCIvobkQZnQiOnsJI0BfdHlwZSI6ImxlZnQifSwiZwEbLH19LDkxMiwyNjksMAFVFHg5Z3NyNQE+ub8AXS6QAAg1OS5BRggxNTEFwzRhdGVnb3JpemVkX29kcwFyDDI5NjYBdExtcy50aW1lX3NwZW50LnFhLnd3dwEYHRU4Yml0cy5qc19pbml0aWFsAUYYIjpbMV19fVkiIQMsNi4zMTUsMCw3Ml1d","snappy":true,"trigger":"categorized_ods","send_method":"ajax","snappy_ms":2},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[23]}}},1575097161966.66,0,null]],"user":"0","app_id":"256281040558"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[23]}}},1575097161966.705,0,null]],"user":"0","app_id":"256281040558"}]
PARAM: ts=1575097161971
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

[*] WE GOT A HIT! Printing the output:
PARAM: __a=1
PARAM: __csr=
PARAM: __dyn=7xe6Fo4OQ1PyUhxOnFwn84a2i5U4e1Fx-ewSwMxW0DUeUhwmU3Mx60Vo1upE4W0OE2WxO0So5u1Qw5MKdwnU1oU881FU3rw
PARAM: __hsi=6764990386559719973-0
PARAM: __pc=PHASED:DEFAULT
PARAM: __req=2
PARAM: __rev=1001480169
PARAM: __s=hwq495:xi3ntd:x9gsr5
POSSIBLE PASSWORD FIELD FOUND: __spin_b=trunk
POSSIBLE PASSWORD FIELD FOUND: __spin_r=1001480169
POSSIBLE PASSWORD FIELD FOUND: __spin_t=1575097066
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: dpr=1
PARAM: jazoest=2722
PARAM: lsd=AVpf5fUu
PARAM: ph=C3
POSSIBLE USERNAME FIELD FOUND: q=[{"user":"0","webSessionId":"hwq495:xi3ntd:x9gsr5","app_id":"256281040558","posts":[["time_spent_bit_array",{"tos_id":"x9gsr5","start_time":1575097156,"tos_array":[59,0],"tos_len":9,"tos_seq":0,"tos_cum":5,"sid_raw":"hwq495:xi3ntd:x9gsr5"},1575097164575.065,0,131],["require_cond_exposure_logging",{"identifier":"Aa1BZcKp-ttBw7RLf_o6EPcPwFk0TZaXMs2qciiC4WjZCcTCJXTUvOWivyMWtoe4RU-8KWDakgpZI3iMsEy_lIztsKQ"},1575097164575.39,0,108]],"trigger":"time_spent_bit_array","send_method":"ajax"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[4]}}},1575097164578.62,0,null]],"user":"0","app_id":"256281040558"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[4]}}},1575097164578.755,0,null]],"user":"0","app_id":"256281040558"}]
PARAM: ts=1575097164583
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

[*] WE GOT A HIT! Printing the output:
PARAM: __a=1
PARAM: __csr=
PARAM: __dyn=7xe6Fo4OQ1PyUhxOnFwn84a2i5U4e1Fx-ewSwMxW0DUeUhwmU3Mx60Vo1upE4W0OE2WxO0So5u1Qw5MKdwnU1oU881FU3rw
PARAM: __hsi=6764990386559719973-0
PARAM: __pc=PHASED:DEFAULT
PARAM: __req=5
PARAM: __rev=1001480169
PARAM: __s=hwq495:xi3ntd:x9gsr5
POSSIBLE PASSWORD FIELD FOUND: __spin_b=trunk
POSSIBLE PASSWORD FIELD FOUND: __spin_r=1001480169
POSSIBLE PASSWORD FIELD FOUND: __spin_t=1575097066
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: dpr=1
PARAM: jazoest=2722
PARAM: lsd=AVpf5fUu
PARAM: ph=C3
POSSIBLE USERNAME FIELD FOUND: q=[{"user":"0","webSessionId":"hwq495:xi3ntd:x9gsr5","app_id":"256281040558","posts":[["click_ref_logger",["2FYY",1575097179131,"act",1575097179130,1,"pass","click","click","-","r","/",{"ft":{"click_type":"left"},"gt":{}},914,318,0,0,"x9gsr5","/login.php"],1575097179130.305,0,150]],"trigger":"click_ref_logger","send_method":"ajax"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[3]}}},1575097179148.255,0,null]],"user":"0","app_id":"256281040558"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[3]}}},1575097179148.325,0,null]],"user":"0","app_id":"256281040558"}]
POSSIBLE PASSWORD FIELD FOUND: q=[{"user":"0","webSessionId":"hwq495:xi3ntd:x9gsr5","app_id":"256281040558","posts":[["click_ref_logger",["2FYY",1575097179131,"act",1575097179130,1,"pass","click","click","-","r","/",{"ft":{"click_type":"left"},"gt":{}},914,318,0,0,"x9gsr5","/login.php"],1575097179130.305,0,150]],"trigger":"click_ref_logger","send_method":"ajax"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[3]}}},1575097179148.255,0,null]],"user":"0","app_id":"256281040558"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[3]}}},1575097179148.325,0,null]],"user":"0","app_id":"256281040558"}]
PARAM: ts=1575097179150
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: __a=1
PARAM: __dyn=7xe6Fo4OQ1PyUhxOnFwn84a2i5U4e1Fx-ewSwMxW0DUeUhwmU3Mx60Vo1upE4W0OE2WxO0So5u1Qw5MKdwnU1oU881FU3rw
PARAM: __csr=
PARAM: __req=8
PARAM: __pc=PHASED:DEFAULT
PARAM: dpr=1
PARAM: __rev=1001480169
PARAM: __s=hwq495:xi3ntd:x9gsr5
PARAM: __hsi=6764990386559719973-0
PARAM: lsd=AVpf5fUu
PARAM: jazoest=2722
POSSIBLE PASSWORD FIELD FOUND: __spin_r=1001480169
POSSIBLE PASSWORD FIELD FOUND: __spin_b=trunk
POSSIBLE PASSWORD FIELD FOUND: __spin_t=1575097066
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

[*] WE GOT A HIT! Printing the output:
PARAM: __a=1
PARAM: __csr=
PARAM: __dyn=7xe6Fo4OQ1PyUhxOnFwn84a2i5U4e1Fx-ewSwMxW0DUeUhwmU3Mx60Vo1upE4W0OE2WxO0So5u1Qw5MKdwnU1oU881FU3rw
PARAM: __hsi=6764990386559719973-0
PARAM: __pc=PHASED:DEFAULT
PARAM: __req=9
PARAM: __rev=1001480169
PARAM: __s=hwq495:xi3ntd:x9gsr5
POSSIBLE PASSWORD FIELD FOUND: __spin_b=trunk
POSSIBLE PASSWORD FIELD FOUND: __spin_r=1001480169
POSSIBLE PASSWORD FIELD FOUND: __spin_t=1575097066
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: dpr=1
PARAM: jazoest=2722
PARAM: lsd=AVpf5fUu
PARAM: ph=C3
POSSIBLE USERNAME FIELD FOUND: q=[{"user":"0","webSessionId":"hwq495:xi3ntd:x9gsr5","app_id":"256281040558","posts":[["click_ref_logger",["2FYY",1575097190797,"act",1575097190797,2,"login","click","click","-","r","/",{"ft":{"click_type":"left"},"gt":{}},1019,354,0,0,"x9gsr5","/login.php"],1575097190797.05,0,152]],"trigger":"click_ref_logger","send_method":"ajax"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[3]}}},1575097190828.28,0,null]],"user":"0","app_id":"256281040558"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[3]}}},1575097190828.375,0,null]],"user":"0","app_id":"256281040558"}]
PARAM: ts=1575097190829
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

[*] WE GOT A HIT! Printing the output:
PARAM: __a=1
PARAM: __csr=
PARAM: __dyn=7xe6Fo4OQ1PyUhxOnFwn84a2i5U4e1Fx-ewSwMxW0DUeUhwmU3Mx60Vo1upE4W0OE2WxO0So5u1Qw5MKdwnU1oU881FU3rw
PARAM: __hsi=6764990386559719973-0
PARAM: __pc=PHASED:DEFAULT
PARAM: __req=b
PARAM: __rev=1001480169
PARAM: __s=hwq495:xi3ntd:x9gsr5
POSSIBLE PASSWORD FIELD FOUND: __spin_b=trunk
POSSIBLE PASSWORD FIELD FOUND: __spin_r=1001480169
POSSIBLE PASSWORD FIELD FOUND: __spin_t=1575097066
POSSIBLE USERNAME FIELD FOUND: __user=0
PARAM: dpr=1
PARAM: jazoest=2722
PARAM: lsd=AVpf5fUu
PARAM: ph=C3
POSSIBLE USERNAME FIELD FOUND: q=[{"user":"0","webSessionId":"hwq495:xi3ntd:x9gsr5","app_id":"256281040558","posts":"iQWQW1siY2F0ZWdvcml6ZWRfb2RzIix7IjI5NzkiOnsiYmFuemFpIgEK8D5sdWVfdG90YWxfbWVzc2FnZXNfcmVjZWl2ZWQiOlszNV19fX0sMTU3NTA5NzE5MzExNS4zNCwwLG51bGxdLFvmZgAMc2VudGJiAAQ4NR1jRHNjcmlwdF9wYXRoX2NoYW5nZQHMFHNvdXJjZQUWOCI6Ii9sb2dpbi5waHAiLBEbVHRva2VuIjoiYWQ5NzY0MjAiLCJkZXMJSRQiOm51bGwNEQ0pCRI0Y2F1c2UiOiJ1bmxvYWQBTnBpZF9yYXciOiJod3E0OTU6eGkzbnRkOng5Z3NyNQEhAG8FihhlZl9wYWdlEVoNFgh1cmkBOlh0dHBzOi8vd3d3LmZhY2Vib29rLmNvbR23BH0sLmYBDDcuNjIhBGgyMTFdLFsidGltZV9zcGVudF9iaXRfYXJyYXkhBSB0b3NfaWQiOiIZjRB0YXJ0XwEwBCI6EVEINzAsBSoJNyw6WzIwMTQyMDUsMF0JGABsIScEMjQJDRRzZXEiOjEJDCBjdW0iOjIyLCJ6BAE+vAAoOTk1LDAsMTM4XV0=","snappy":true,"send_method":"beacon","snappy_ms":0},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[4]}}},1575097193118.29,0,null]],"user":"0","app_id":"256281040558"},{"webSessionId":"hwq495:xi3ntd:x9gsr5","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[6]}}},1575097193118.32,0,null]],"user":"0","app_id":"256281040558"}]
PARAM: ts=1575097193121
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.

thats my results.

my email is test12345@gmail.com
pass 12345test

cant figure out why i dont see the actual credentials.
any help will be welcomed.
thanks.

**Comment by seThom20** [comment]
that's also happening to me with WAN, but works fine using LAN IP's

**Comment by trustedsec** [comment]
Edit the /root/.set/ and in there is an index.html file, modify so that the password parameter posts to the website. Some sites don't clone properly, it's just the way some of these go.

**Comment by rinxhen17** [comment]
I need help with the same issue please

**Comment by moshe6524** [comment]
I have a much better way now.
I can guide you with everything, but it's going to cost you.

בתאריך יום ב׳, 18 במאי 2020, 02:17, מאת rinxhen17 ‏<notifications@github.com

**Comment by rinxhen17** [comment]
no thankyou.

**Comment by moshe6524** [comment]
Can't help you with SET. I have other working great phishing method...

בתאריך יום ב׳, 18 במאי 2020, 04:49, מאת rinxhen17 ‏<notifications@github.com
