### ISSUE TITLE
Instagram cloning gives me a blank screen

### ISSUE THREAD

**Issue by reparrot** [trustedsec/social-engineer-toolkit#670]
Whenever i try to clone instagrams login page it will show a blank screen but the header and tab/title shows "Login∙Instagram". Almost every website is working except for instagram

**Comment by sysAdmin9678** [comment]
Same here..can anyone help?

**Comment by trustedsec** [comment]
Some sites this can happen, recommend going to instagram, save the page, and use the import - cloning sites isn't a perfect science
