### ISSUE TITLE
 website cloning does not work outside the session (Harvester)

### ISSUE THREAD

**Issue by izno69** [trustedsec/social-engineer-toolkit#672]
Hi,
I use 1, 2, 3, 2 to clone a website on my vmware version ok kali
I have the newest version of kali & set
Is working when i use my own navigator, i read the password when i use the IP
But if i open an other brownser in a real machine, the IP connection not working
What i missed ?
Thx

**Comment by izno69** [comment]
i found how :)

**Comment by Frankhack7** [comment]
How can I solve it
