### ISSUE TITLE
Metasploit path not found - mac

### ISSUE THREAD

**Issue by LielHan** [trustedsec/social-engineer-toolkit#676]
**Greetings people of github and most importantly the people who created SET.**
I have downloaded set and metasploit but when I run set it says: 
```
[!] The python-pycrypto python module not installed. You will lose the ability for encrypted communications.
[!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.
[!] The python-pycrypto python module not installed. You will lose the ability to use multi-pyinjector.
```
when I go to set.config metasploit path I look up the path and see metasploit-framework so I don't understand what is the problem. If you can also help me solve the python issue it will be a bonus, Any help will be highly apperciated.

**Comment by trustedsec** [comment]
I would recommend installing SET on Linux, it's extensively tested there, less so on OS X.  Have you tried pip3 install pycrypto or crypto to see if that resolves the installation of that one ?

Also for the Metasploit framework, ensure its the path it can get to that has msfconsole and msfvenom installed..
