### ISSUE TITLE
setoolkit can't Run in root folder, the icon is missing

### ISSUE THREAD

**Issue by XSecr3t** [trustedsec/social-engineer-toolkit#677]
**Expected Behaviour**
setoolkit should be run in root directory even configured to /usr/share/set/ but that will be something wrong with my setup even im already running pip install -r requirements.txt , i can't find any file like setup.py or something that need to be running again ._.
[https://i.imgur.com/nhSGt19.png](url)
and this is when i see /usr/share/set/ seems like set.config missing isn't it? but even set.config is missing from that directory my setoolkit works fine when i opened localhost only in directory /usr/share/set i can running setoolkit using command /setoolkit -_- when i run in directory root that's the result above.
here's my setoolkit folder.
[https://i.imgur.com/QmTUMvr.png](url)
is there anything else looks seems like something wrong? cause i think this is not absoultely correct like manually setting from kali linux itself.
like i said,my setoolkit was got removed with my ettercap when i uninstall nginx package i really don't understand why.
can you please solved this? and help me

Put here what the expected behaviour should be when reporting an issue
my setoolkit should be running in root folder clearly, but it's not.

**Actual Behaviour**
just tell me, is there something wrong with my setup?

Put here what the actual behaviour should be when reporting an issue

**Set Version**
Latest Version and FRESH cause im have accident that when i remove and purge my nginx package, my setoolkit and ettercap will got remove too, i do not understand  for this, got headache causing this.

_Set version_
Latest Version

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**
Kali-Rolling and up to date
Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	2019.4
Codename:	kali-rolling

````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by trustedsec** [comment]
There's no launcher created for it to operate, I just created a new setup.py file in 8.0.2 that you'll be able to run to install and launch from anywhere. Should be pushing this update soon.

**Comment by Nabeel-001** [comment]
> There's no launcher created for it to operate, I just created a new setup.py file in 8.0.2 that you'll be able to run to install and launch from anywhere. Should be pushing this update soon.

can you please elaborate on what is actually 8.0.2 is ? where do I actually create it?
