### ISSUE TITLE
When i clone a Facebook site, only meaningless data is harvested.

### ISSUE THREAD

**Issue by sodadayo** [trustedsec/social-engineer-toolkit#680]
Replicated sites are normally connected, but meaningless values are harvested when attempting to log in.
Below is the log when i tried to log in.Can you help me with this?

*] WE GOT A HIT! Printing the output:
PARAM: __a=1                                                                                               
PARAM: __beoa=0                                                                                            
PARAM: __csr=                                                                                              
PARAM: __dyn=7xe6Fo4OQ1PyUhxOnFwn84a2i5U4e1Fx-ewSwMxW0DUeUhw5cx60Vo1upE4W0OE2WxO0So5u1Qw5MKdwnU1oU881FU3rw 
PARAM: __hsi=6786935171120647638-0                                                                         
PARAM: __pc=PHASED:DEFAULT                                                                                 
PARAM: __req=1                                                                                             
PARAM: __rev=1001647252                                                                                    
PARAM: __s=b2xh44:zhr6mt:qe7jk8                                                                            
POSSIBLE PASSWORD FIELD FOUND: __spin_b=trunk                                                              
POSSIBLE PASSWORD FIELD FOUND: __spin_r=1001647252                                                         
POSSIBLE PASSWORD FIELD FOUND: __spin_t=1580206484                                                         
POSSIBLE USERNAME FIELD FOUND: __user=0                                                                    
PARAM: dpr=1                                                                                               
PARAM: jazoest=2678                                                                                        
PARAM: lsd=AVrGHZNf                                                                                        
POSSIBLE USERNAME FIELD FOUND: q=[{"user":"0","webSessionId":"b2xh44:zhr6mt:qe7jk8","app_id":"256281040558","posts":"gxHwaVtbImdrMl9leHBvc3VyZSIseyJpZGVudGlmaWVyIjoiMTA3MzUwMCIsImhhc2giOiJBVDVqa2JnLW1HZFVQUkEyIn0sMTU4MDIwNjUzMjk0MC44NDUsMCw1MF0sWyJyZXF1aXJlX2NvbmQVZBxfbG9nZ2luZ0JsAPBWQWEzMzZMLXpJYmVzUGxXWDQ1NWg0QWZaTnZoa3lUWnphVUNHdkIwc2RiblppY0M5WlNWOENqVnNPdldBZ2ZEUVR1QVd6a3ZwNms4Y3hqeU4wS2NxdkIwOqIAMDEuNDM1LDAsMTA0XSx6/gAUOTQ2ODk0Mv0AMHUyOGJyWGdfb0p5X3RCWwAENTABWwQ0OYJaABQ2NzY5MjIuWgA0N2RJUjFfdmhjWW1IX21GWgAINiwwolkAADAyWQAwdEQydENQYjUwaU1sazpZAAw1LjUyqlkAADEyWQAwb2IxaFhIQUk0U0ZEODpZAAw2Ljg0olkACDgzNy5ZADQ2UnlDY3pLWGR0VEJnbzpZAAg3LjaaWQAUMTExMzI0NloAMGtIMkp4VUJuUndnLTM6WgAMOC4zM1W7bHNjcmlwdF9wYXRoX2NoYW5nZSIseyJzb3VyY2UFFhgiOm51bGwsERMQdG9rZW4RFAhkZXMJOzgiOiIvbG9naW4ucGhwIiwJGQ0rGCJhZDk3NjQlrfBeaW1wcmVzc2lvbl9pZCI6IjBRcUttd2Q3YzF2WEZhRlRvIiwiY2F1c2UiOiJsb2FkIiwic2lkX3JhdyI6ImIyeGg0NDp6aHI2bXQ6cWU3ams4IiwicmVmZXJyZXIiOiIRehhlZl9wYWdlMqcAdHVyaSI6Imh0dHBzOi8vd3d3LmZhY2Vib29rLmNvbR2+AH156TAzMDE3Ljk4LDAsMjU1QewAcr7pA/BQUG5IUHhhNlBjME01cWVkTGNkenpOMzFfeXJDN3h3QW1rSWZhUDM2TGpTVU0wZEhHNkt1ODN1MUNfWmJZcGpTN1ZwOG5JdVZTVGlRWlhOc2k4Op8ADDguMDJhiwgxMDEBoHLkBBQ3Mjk2MjkugQI0N0syS215MXh3ejBfSE42WwAQMjAuMjeW2gIBWQAzNowDMHA3R1dOWC1rQ2FxSFZCWQAEMzABtAA0hj8EBVoyjQM0Nl9VN2MxWVpGWU9iNW5GWgAlDopaABQxMTMwNDYymgQwNWJpRzgtV0dCQnFHQ0YOAQQzOXU1cmcBFDEyMjAzNTIPATA2ZGFKdWstWDJQSy03Mk4FADMhaAQ0MZZaABQ2Nzc3NjIywQEsNlRka0ticjMyTEg4OrMAEDMyLjIxOWgAcrq7AvBMMTVGTkJzRGxDYWxuSkM3d1pLaUtNVWRNczkzYnpNZlZOdmdwaUpoemhrckZIbnFKRGVfYlR1aUhra2wtSTBTbzlEMnVQSGpFNUo4dyIyVAMBmeU9BDk1QbS+mQDwRDNwbzJTX25uejhsZG5SVTJXMmpkTTU1cEcxUXJrOERGaV94YTFrV0JFa3RoRnQ4YXJMRGJpMWU4MTdlb1NxcTg1bFNpQTY5AgGSwXgEODgBkQhnazL1xaENAGkuKQgUNzA4MjUzLoQBNDQ0Zi14WDNwTkdZUzk3OlkAKDkuMDksMCw0OV1d","snappy":true,"send_method":"beacon","snappy_ms":2},{"webSessionId":"b2xh44:zhr6mt:qe7jk8","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[21]}}},1580206533182.29,0,null]],"user":"0","app_id":"256281040558"},{"webSessionId":"b2xh44:zhr6mt:qe7jk8","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[21]}}},1580206533182.355,0,null]],"user":"0","app_id":"256281040558"}]                                                                                 
PARAM: ts=1580206533186

**Comment by trustedsec** [comment]
Happens, it's difficult automatically cloning sites, what I would recommend is going to facebook, saving the file, and then using the import page (index.html) as an option.
