### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by abi-psykid** [trustedsec/social-engineer-toolkit#719]
**Expected Behaviour**

Open SEToolkit

**Actual Behaviour**

/usr/local/bin/setoolkit: 3: ./setoolkit: Permission denied

**Set Version**

_Set version_

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by DropsThose** [comment]
Run it with sudo?

**Comment by abi-psykid** [comment]
doesn't work with sudo .
Although , python setoolkit install , opens set if it is already installed

**Comment by CRO-THEHACKER** [comment]
No need to do python setoolkit install, just do:

sudo su (to get SuperUser)
apt install python3-pip
pip3 install -r requirements.txt
python3 setup.py

after that you can run setoolkit with:

sudo setoolkit

**Comment by aawheatley** [comment]
In order for setoolkit to run, it requires **sudo**. 
So you have to run **sudo setoolkit**

**Comment by An-EnD** [comment]
you need to do the following

sudo su (to get SuperUser)
cd /usr/share/set
chmod +x *


now try opening SET. It worked for me

**Comment by An-EnD** [comment]
you need to do the following
`sudo su` (to get superuser)
`cd /usr/share/set`
`chmod +x *`

now try opening SET.

**Comment by abdallashalaby** [comment]
I had the same problem and when I typed sudo python3 setup.py it worked!

**Comment by samglish** [comment]
# simple test
1. `run sudo su` 
2.` cd /usr/share/set/ && ./setoolkit "$@"`
# permanent use
1. run `sudo nano /usr/local/bin/setoolkit`
2. clean and replace content 
```bash
#!/bin/sh
cd /usr/share/set/ && ./setoolkit "$@"
```
3. `Ctrl + X` for save
