### ISSUE TITLE
setoolkit issue

### ISSUE THREAD

**Issue by hiishaam** [trustedsec/social-engineer-toolkit#725]
Hello,

Please help. I have Kali 2020 installed on my machine. I tried setoolkit using web template function (I use google) after the page opened by another device and entering username and password it gives me this error

[] Cloning the website: http://www.google.com
[] This could take a little bit...

The best way to use this attack is if username and password form fields are available. Regardless, this captures all POSTs on a website.
[] The Social-Engineer Toolkit Credential Harvester Attack
[] Credential Harvester is running on port 80
[] Information will be displayed to you as it arrives below:
192.168.8.105 - - [22/Apr/2020 16:18:19] "GET /ServiceLoginAuth HTTP/1.1" 404 -
192.168.8.105 - - [22/Apr/2020 16:18:21] "GET /favicon.ico HTTP/1.1" 404 -
192.168.8.105 - - [22/Apr/2020 16:18:25] "GET /ServiceLoginAuth HTTP/1.1" 404 -
192.168.8.105 - - [22/Apr/2020 16:18:27] "GET /ServiceLoginAuth HTTP/1.1" 404 -
192.168.8.105 - - [22/Apr/2020 16:18:40] "GET / HTTP/1.1" 200 -
192.168.8.105 - - [22/Apr/2020 16:18:42] "GET /favicon.ico HTTP/1.1" 404 -
[] WE GOT A HIT! Printing the output:
Exception happened during processing of request from ('192.168.8.105', 55704)
Traceback (most recent call last):
File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.8/socketserver.py", line 720, in init
self.handle()
File "/usr/lib/python3.8/http/server.py", line 427, in handle
self.handle_one_request()
File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
method()
File "/usr/share/set/src/webattack/harvester/harvester.py", line 334, in do_POST
filewrite.write(cgi.escape("PARAM: " + line + "\n"))
AttributeError: module 'cgi' has no attribute 'escape'

**Comment by Skycrazy** [comment]
https://github.com/trustedsec/social-engineer-toolkit/issues/720#issuecomment-618090489

**Comment by hiishaam** [comment]
> [#720 (comment)](https://github.com/trustedsec/social-engineer-toolkit/issues/720#issuecomment-618090489)

I did that but the problem still exists.

**Comment by hiishaam** [comment]
> [#720 (comment)](https://github.com/trustedsec/social-engineer-toolkit/issues/720#issuecomment-618090489)

it worked now thanks

**Comment by Skycrazy** [comment]
Glad your sorted bud
