### ISSUE TITLE
SMS spoofing is deleted ? or its me ?

### ISSUE THREAD

**Issue by backl1n** [trustedsec/social-engineer-toolkit#816]
![image](https://user-images.githubusercontent.com/40395422/94109433-40b2a400-fe41-11ea-8dd9-015658adf99a.png)
why i have not sms spoofing

**Comment by Anirudh-johnson** [comment]
yes i think it is deleted

**Comment by backl1n** [comment]
why you think? @Anirudh-johnson

**Comment by Anirudh-johnson** [comment]
@backl1n well i checked it after my previous comment and found out that SET was using a api for sms spoofing and it stoped its support so they removed it

**Comment by Anirudh-johnson** [comment]
@backl1n see the line 40 of the  #screenshot. The feature got removed in update of version 8.0

![Screenshot from 2020-10-12 22-22-37](https://user-images.githubusercontent.com/22961036/95771943-8f818a00-0cd9-11eb-8ed3-583d7b8ea011.png)
