### ISSUE TITLE
Can't harvest password

### ISSUE THREAD

**Issue by ov1faruk** [trustedsec/social-engineer-toolkit#821]
when i try to login on my localhost this message is shown on SET ( no port forwarding , everything is up to date )

[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: -----------------------------410537787029587119873032971314                                                            
Content-Disposition: form-data; name="ts"                                  
                                                                           
1601856575772                                                              
-----------------------------410537787029587119873032971314                
Content-Disposition: form-data; name="q"                                   
                                                                           
[{"app_id":"256281040558","posts":"wR94W1sic2NyaXB0X3BhdGhfY2hhbmdlIix7InNvdXJjZQUWOCI6Ii9sb2dpbi5waHAiLBEbVHRva2VuIjoiYWQ5NzY0MjAiLCJkZXMJST4zAAUZSjEA8FBpbXByZXNzaW9uX2lkIjoiMElUUXRSWDh0ejJUMEpjeEMiLCJjYXVzZSI6ImxvYWQiLCJzaWRfcmF3IjoiYm9qd3lhOjl5aXc0bzozbHR5YWwZnzBlZl9wYWdlIjpudWxsFbV0dXJpIjoiaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tMucABbQ6RgAFFKpEAC1G8K5yZXN0b3JlZCI6dHJ1ZX0sMTYwMTg1NjU3MDA4NiwwLDM1MF0sWyJyZXF1aXJlX2NvbmRfZXhwb3N1cmVfbG9nZ2luZyIseyJpZGVudGlmaWVyIjoiQWEybFpRWkdGSjRRWEVDdjA3bVI0Nlh2bFJqbENFT3k4QkhvcmN1M0NfSHZtZTY2WkdNZkJkZDFyNGg5WFp2ZU5qSWdJbXV4ZWpZNkhrcHhlbEx3QmhBIn0sLp8AGDcsMCwxMDQBnwhnazIVlkEjAGkujgAUMTA3MzUwQQUIaGFzQQA8QVQ3b2U3RUk3bW5feG5Qc0pYAAn2clcAHDk0Njg5NCIsGVY0NkY2eV9MWnhMMWRtSjVKVgAENDmCrQAMNjc2OUWxFaw0NDFBcFJDTjZ0OXFIYVLWVgAUMTY1NjkxMgMBNDUtbEFTeHU3VUdsVnFqSlcAigMBBa0AMS4DATQ0X0l5blRxeHVoakMwTEpWAJYDAQg4MzcyVgAwaHJFRF8xdXo2a2p4MGJWAL6lAvBQM29oQXFxekFya3BmbjlQQnJvNFg1dlVINnFtMzFPWm5HVlgxOTd3R0o3a1E4QXJhclQxSlNjMlQyV3pIZUZ2WTR4dWdPejNpRWNxRW9WajlvSpoACDEwMCH0vpsA8FIxeDNIckwxeEFhSDZLLTVsN3pPQkFaTEl2ZXN0OUJ3U0tOOHcxRmtuQlVkbWdaZFF2NGdyaGNIT1NGUzRDUUVHLXNKMDh0MGE2MXZMS1p4dTktIjbcA2k9ADHOnADwVDJMSTZzN3RyNVUteEhyMk5MMnA4U1lRYXAwV0JfallVUTJtekxncmliQk9MaDdjb3c5VkNZR2poUktrSy1ZcklhRVdXWjU1RFJhQ1VVLU9iYUhsVHNSOwFl3PBEd2ViX2RldmljZV9wZXJmX2luZm9fbG9nIix7ImNwdV9jb3JlcyI6NSwiZ3B1X3ZlbmRvciI6IlZNd2FyZSwgSW5jLiIsBRwYcmVuZGVyZQEefGxsdm1waXBlIChMTFZNIDEwLjAuMSwgMjU2IGJpdHMpMo8AHDEyOCwwLDkzIS1yEwQYMTA5OTg5My67AjQ3Q0IxQW4zQ095NWpwSUpXAIpnAxgxMzk5MjE4LlcANDU0Zi1HSFIwUm1COGli1lcAEDcyOTYzMhQENDRrSDZxSGR4blRrVndfSlYAir4DFDEzODE3NjatADBhSHd0N2JGb1BoTW5HSlcAigQBBa02awQweG5ac3ZmWjAzQmV0UUpWAI6tABA2MjA4MDKxATQ1Q2JJWHdfcnJSRkNhYUpXAIqtABgxMjgxNTA1LrEBNDZJYmlhQ1o2d0ljcHN43lcADDkxMDI2rgAwcW5Bd3lpVGpzRy0tN+JXAAw0MTgyMq4AMFRmM2pEOHZOWjhneTjaVwAQNDAxMDYyYAI0NVhMakhqaVBZSWQwdFbeVwAMODUwNTJcATA0OW5ua0pyM19tNVRiNngHabuOswEQNTg0Nzk2dgYwVDJ4b0l2U1Z6cXRfRdquAAw2NDcyNgUBNDRyM09YY1JiYjQ1eGRK2lcAEDU5NzY0MrMBNDUwTFNKa1RMLXBPVjh62lcAEDcyMjAxMtQINDd2OUpudzl2TENfOWxE2lcADDY5NTg2vQM0NVExd3Y0NnNPVkJFRUPaVwAQNzQyNzkyCgI0Nkxvc2FSb3JrcHJ0Z2hiVwDCjgfwSkNxaWMybDE5NmtaWHJPZHU1UVoxaUhUWnBCWXpRcWJfRUZHUUhXOTZMQnFZU0NxclNSa2tiUTBLTXVEUjVidDFSVjJCNFBiaVJFQUqVAAQ5NcFawpUA8FQ3amdqUlpib2Rfc0c2OGhiQzNneE5ZYURwcWUzemRNajJMT2w3UG80NFRCSjMwSVdZdWYzdngwbmpIeGNOSm1DVTY5TUtPSHFEVlhET0Z0ZjhpTGUxSp8ABDEwBaAkY2xpY2tfcmVmXw73CzBlciIsWyIyUzJkIiwxHjQMIDU3NjYsImFjdDYUACg1LDEsInBhc3MiLAlGHQggLSIsInIiLCIv4c8QZnQiOnsJI0BfdHlwZSI6ImxlZnQifSwiZwEbPH19LDUwNywyNzIsMCwwLCIiWQ0EL2wiBQ4AXTKPAAA1DiQMiv8DEDY3Nzc2MlADNDREcVE5ZGprc3hqWUpuLhcBBeYAMI5fBhQ3MDgyNTMuWQU0N3RNWHl0VGlGYk9BcnbWVgAUMTQyNzMwMmIHNDY4cVFEeU5QdVo5MnRPSlcAKQM4Y2F0ZWdvcml6ZWRfb2RzIXMMMjk2NiF1TG1zLnRpbWVfc3BlbnQucWEud3d3ARgdFQ4ZCSguanNfaW5pdGlhbAFGGCI6WzFdfX0qWwooNTc2NywwLDcyXV0=","user":"0","webSessionId":"bojwya:9yiw4o:3ltyal","trigger":"categorized_ods","send_method":"ajax","compression":"snappy_base64","snappy_ms":3},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[38]}}},1601856575767,0,51]],"user":"0","app_id":"256281040558","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[38]}}},1601856575767,0,47]],"user":"0","app_id":"256281040558","compression":""}]                                              
-----------------------------410537787029587119873032971314--              
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.              
                                                                           
                                                                           
127.0.0.1 - - [04/Oct/2020 17:09:35] "POST /ajax/bz?__a=1&__beoa=0&__ccg=EXCELLENT&__comet_req=0&__csr=&__dyn=7xe6Fo4OQ1PyWwHBWo5O12wAxu13wqovzEdEc8uw9-3K4o1j8hwem0nCq1ewcG0KEswaq3a1nwt81sbzo5iaw5zwwwi831w9O0SU2swdq0Ho2ew4pw&__hsi=6879921555707970299-0&__pc=PHASED%3ADEFAULT&__req=1&__rev=1002768747&__s=bojwya%3A9yiw4o%3A3ltyal&__spin_b=trunk&__spin_r=1002768747&__spin_t=1601856564&__user=0&bz_orig=blue&dpr=1&jazoest=2937&lsd=AVpiQ0JFPuc HTTP/1.1" 302 -
[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: -----------------------------20656041555861792322849315727                                                             
Content-Disposition: form-data; name="ts"                                  
                                                                           
1601856578108                                                              
-----------------------------20656041555861792322849315727                 
Content-Disposition: form-data; name="q"                                   
                                                                           
[{"app_id":"256281040558","posts":[["click_ref_logger",["2S2d",1601856575766,"act",1601856575765,1,"pass","click","click","-","r","/",{"ft":{"click_type":"left"},"gt":{}},507,272,0,0,"3ltyal","/login.php"],1601856575765,1,150],["time_spent_bit_array",{"tos_id":"3ltyal","start_time":1601856570,"tos_array":[125,0],"tos_len":9,"tos_seq":0,"tos_cum":6,"sid_raw":"bojwya:9yiw4o:3ltyal"},1601856578106,0,132]],"user":"0","webSessionId":"bojwya:9yiw4o:3ltyal","trigger":"time_spent_bit_array","send_method":"ajax","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[3]}}},1601856578106,0,50]],"user":"0","app_id":"256281040558","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[4]}}},1601856578106,0,46]],"user":"0","app_id":"256281040558","compression":""}]                                                                    
-----------------------------20656041555861792322849315727--               
POSSIBLE PASSWORD FIELD FOUND: -----------------------------20656041555861792322849315727                                                             
Content-Disposition: form-data; name="ts"                                  
                                                                           
1601856578108                                                              
-----------------------------20656041555861792322849315727                 
Content-Disposition: form-data; name="q"                                   
                                                                           
[{"app_id":"256281040558","posts":[["click_ref_logger",["2S2d",1601856575766,"act",1601856575765,1,"pass","click","click","-","r","/",{"ft":{"click_type":"left"},"gt":{}},507,272,0,0,"3ltyal","/login.php"],1601856575765,1,150],["time_spent_bit_array",{"tos_id":"3ltyal","start_time":1601856570,"tos_array":[125,0],"tos_len":9,"tos_seq":0,"tos_cum":6,"sid_raw":"bojwya:9yiw4o:3ltyal"},1601856578106,0,132]],"user":"0","webSessionId":"bojwya:9yiw4o:3ltyal","trigger":"time_spent_bit_array","send_method":"ajax","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[3]}}},1601856578106,0,50]],"user":"0","app_id":"256281040558","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[4]}}},1601856578106,0,46]],"user":"0","app_id":"256281040558","compression":""}]                                                                    
-----------------------------20656041555861792322849315727--               
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.              
                                                                           
                                                                           
127.0.0.1 - - [04/Oct/2020 17:09:38] "POST /ajax/bz?__a=1&__beoa=0&__ccg=EXCELLENT&__comet_req=0&__csr=&__dyn=7xe6Fo4OQ1PyWwHBWo5O12wAxu13wqovzEdEc8uw9-3K4o1j8hwem0nCq1ewcG0KEswaq3a1nwt81sbzo5iaw5zwwwi831w9O0SU2swdq0Ho2ew4pw&__hsi=6879921555707970299-0&__pc=PHASED%3ADEFAULT&__req=2&__rev=1002768747&__s=bojwya%3A9yiw4o%3A3ltyal&__spin_b=trunk&__spin_r=1002768747&__spin_t=1601856564&__user=0&bz_orig=blue&dpr=1&jazoest=2937&lsd=AVpiQ0JFPuc HTTP/1.1" 302 -
[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: -----------------------------42497250629731508911557224329                                                             
Content-Disposition: form-data; name="ts"                                  
                                                                           
1601856580354                                                              
-----------------------------42497250629731508911557224329                 
Content-Disposition: form-data; name="q"                                   
                                                                           
[{"app_id":"256281040558","posts":"tAS4W1siY2xpY2tfcmVmX2xvZ2dlciIsWyIyUzJkIiwxNjAxODU2NTc1NzY2LCJhY3Q2FAAoNSwxLCJwYXNzIiwJRh0IRC0iLCJyIiwiLyIseyJmdCI6ewkjQF90eXBlIjoibGVmdCJ9LCJnARtUfX0sNTA3LDI3MiwwLDAsIjNsdHlhbAE+KGxvZ2luLnBocCJdMo8AeDUsMiwxNTBdLFsidGltZV9zcGVudF9iaXRfYXJyYXkBdRx0b3NfaWQiOhlOFHN0YXJ0XwEwBCI6FdwEMCwFKgk3HDpbMTI1LDBdCRQUbGVuIjo5CQwQc2VxIjoNLHxjdW0iOjYsInNpZF9yYXciOiJib2p3eWE6OXlpdzRvOg2/BH0sFWUkODEwNiwxLDEzMgGyAGOCcgEUODAzNTIsNnIBARQgMSwyLCJlbWFpIR0FRwAiOXvCcwEUMzIsMjE1jnMBMDgwMzUxLDAsMTUxXV0=","user":"0","webSessionId":"bojwya:9yiw4o:3ltyal","trigger":"click_ref_logger","send_method":"ajax","compression":"snappy_base64","snappy_ms":0},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[3]}}},1601856580352,0,50]],"user":"0","app_id":"256281040558","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[5]}}},1601856580353,0,46]],"user":"0","app_id":"256281040558","compression":""}]         
-----------------------------42497250629731508911557224329--               
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.              
                                                                           
                                                                           
127.0.0.1 - - [04/Oct/2020 17:09:40] "POST /ajax/bz?__a=1&__beoa=0&__ccg=EXCELLENT&__comet_req=0&__csr=&__dyn=7xe6Fo4OQ1PyWwHBWo5O12wAxu13wqovzEdEc8uw9-3K4o1j8hwem0nCq1ewcG0KEswaq3a1nwt81sbzo5iaw5zwwwi831w9O0SU2swdq0Ho2ew4pw&__hsi=6879921555707970299-0&__pc=PHASED%3ADEFAULT&__req=3&__rev=1002768747&__s=bojwya%3A9yiw4o%3A3ltyal&__spin_b=trunk&__spin_r=1002768747&__spin_t=1601856564&__user=0&bz_orig=blue&dpr=1&jazoest=2937&lsd=AVpiQ0JFPuc HTTP/1.1" 302 -
[*] WE GOT A HIT! Printing the output:
PARAM: accept_consent=false                                                
POSSIBLE USERNAME FIELD FOUND: __user=0                                    
PARAM: __a=1                                                               
PARAM: __dyn=7xe6Fo4OQ1PyWwHBWo5O12wAxu13wqovzEdEc8uw9-3K4o1j8hwem0nCq1ewcG0KEswaq3a1nwt81sbzo5iaw5zwwwi831w9O0SU2swdq0Ho2ew4pw                       
PARAM: __csr=                                                              
PARAM: __req=4                                                             
PARAM: __beoa=0                                                            
PARAM: __pc=PHASED:DEFAULT                                                 
PARAM: dpr=1                                                               
PARAM: __ccg=EXCELLENT                                                     
PARAM: __rev=1002768747                                                    
PARAM: __s=bojwya:9yiw4o:3ltyal                                            
PARAM: __hsi=6879921555707970299-0                                         
PARAM: __comet_req=0                                                       
PARAM: lsd=AVpiQ0JFPuc                                                     
PARAM: jazoest=2937                                                        
POSSIBLE PASSWORD FIELD FOUND: __spin_r=1002768747                         
POSSIBLE PASSWORD FIELD FOUND: __spin_b=trunk                              
POSSIBLE PASSWORD FIELD FOUND: __spin_t=1601856564                         
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.              
                                                                           
                                                                           
127.0.0.1 - - [04/Oct/2020 17:09:44] "POST /cookie/consent/ HTTP/1.1" 302 -
[*] WE GOT A HIT! Printing the output:
PARAM: jazoest=2937                                                        
PARAM: lsd=AVpiQ0JFPuc                                                     
PARAM: display=                                                            
PARAM: enable_profile_selector=                                            
PARAM: isprivate=                                                          
PARAM: legacy_return=0                                                     
PARAM: profile_selector_ids=                                               
PARAM: return_session=                                                     
POSSIBLE USERNAME FIELD FOUND: skip_api_login=                             
PARAM: signed_next=                                                        
PARAM: trynum=1                                                            
PARAM: timezone=420                                                        
PARAM: lgndim=eyJ3IjoxOTIwLCJoIjo5NzUsImF3IjoxOTIwLCJhaCI6OTQ0LCJjIjoyNH0= 
PARAM: lgnrnd=170924_Jsla                                                  
PARAM: lgnjs=1601856570                                                    
POSSIBLE USERNAME FIELD FOUND: email=hhvhvhvhv                             
PARAM: prefill_contact_point=                                              
PARAM: prefill_source=                                                     
PARAM: prefill_type=                                                       
PARAM: first_prefill_source=                                               
PARAM: first_prefill_type=                                                 
PARAM: had_cp_prefilled=false                                              
POSSIBLE PASSWORD FIELD FOUND: had_password_prefilled=false                
PARAM: ab_test_data=AAKKK/fKAKAAAAKAAAAAAAAAAAAAAAAAAAAKAAAAv/v/PPAPAAIAAA 
POSSIBLE PASSWORD FIELD FOUND: encpass=#PWD_BROWSER:5:1601856584:AT5QAIbyNPAJuLCR/gwgDNvm4FeK1fCkxfylwLq8aFbooOBNteJ7/+M8usWUPmM5QUQg+89mNQAi4zX7oHV9fgdUbMrYsDQu3HYsBZmOkAR7c8jTpJBfES/EKhBSUb3tBPBkJOQXSEYxrrMt                
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.              
                                                                           
                                                                           
10.0.2.15 - - [04/Oct/2020 17:09:44] "POST /device-based/regular/login/?login_attempt=1&lwv=100 HTTP/1.1" 302 -
[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: -----------------------------25487851361538073608814040230                                                             
Content-Disposition: form-data; name="ts"                                  
                                                                           
1601856584852                                                              
-----------------------------25487851361538073608814040230                 
Content-Disposition: form-data; name="q"                                   
                                                                           
[{"app_id":"256281040558","posts":"9QW4W1siY2xpY2tfcmVmX2xvZ2dlciIsWyIyUzJkIiwxNjAxODU2NTc1NzY2LCJhY3Q2FAAoNSwxLCJwYXNzIiwJRh0IRC0iLCJyIiwiLyIseyJmdCI6ewkjQF90eXBlIjoibGVmdCJ9LCJnARtUfX0sNTA3LDI3MiwwLDAsIjNsdHlhbAE+KGxvZ2luLnBocCJdMo8AeDUsMywxNTBdLFsidGltZV9zcGVudF9iaXRfYXJyYXkBdRx0b3NfaWQiOhlOFHN0YXJ0XwEwBCI6FdwEMCwFKgk3HDpbMTI1LDBdCRQUbGVuIjo5CQwQc2VxIjoNLHxjdW0iOjYsInNpZF9yYXciOiJib2p3eWE6OXlpdzRvOg2/BH0sFWUkODEwNiwyLDEzMgGyAGOCcgEUODAzNTIsNnIBARQgMSwyLCJlbWFpIR0FRwAiOXvCcwEUMzIsMjE1jnMBKDgwMzUxLDEsMTUxmsEAEDQ4MDMsOsEABRQIMywiJdUduRHJwsEAFDg2LDM1M5LBACw0ODAzLDAsMTUxXV0=","user":"0","webSessionId":"bojwya:9yiw4o:3ltyal","trigger":"click_ref_logger","send_method":"ajax","compression":"snappy_base64","snappy_ms":1},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[3]}}},1601856584849,0,50]],"user":"0","app_id":"256281040558","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[6]}}},1601856584849,0,46]],"user":"0","app_id":"256281040558","compression":""}]                    
-----------------------------25487851361538073608814040230--               
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.              
                                                                           
                                                                           
127.0.0.1 - - [04/Oct/2020 17:09:44] "POST /ajax/bz?__a=1&__beoa=0&__ccg=EXCELLENT&__comet_req=0&__csr=&__dyn=7xe6Fo4OQ1PyWwHBWo5O12wAxu13wqovzEdEc8uw9-3K4o1j8hwem0nCq1ewcG0KEswaq3a1nwt81sbzo5iaw5zwwwi831w9O0SU2swdq0Ho2ew4pw&__hsi=6879921555707970299-0&__pc=PHASED%3ADEFAULT&__req=5&__rev=1002768747&__s=bojwya%3A9yiw4o%3A3ltyal&__spin_b=trunk&__spin_r=1002768747&__spin_t=1601856564&__user=0&bz_orig=blue&dpr=1&jazoest=2937&lsd=AVpiQ0JFPuc HTTP/1.1" 302 -
[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: -----------------------------266198348718227902573662103509                                                            
Content-Disposition: form-data; name="ts"                                  
                                                                           
1601856585150                                                              
-----------------------------266198348718227902573662103509                
Content-Disposition: form-data; name="q"                                   
                                                                           
[{"app_id":"256281040558","posts":"9QW4W1siY2xpY2tfcmVmX2xvZ2dlciIsWyIyUzJkIiwxNjAxODU2NTc1NzY2LCJhY3Q2FAAoNSwxLCJwYXNzIiwJRh0IRC0iLCJyIiwiLyIseyJmdCI6ewkjQF90eXBlIjoibGVmdCJ9LCJnARtUfX0sNTA3LDI3MiwwLDAsIjNsdHlhbAE+KGxvZ2luLnBocCJdMo8AeDUsNCwxNTBdLFsidGltZV9zcGVudF9iaXRfYXJyYXkBdRx0b3NfaWQiOhlOFHN0YXJ0XwEwBCI6FdwEMCwFKgk3HDpbMTI1LDBdCRQUbGVuIjo5CQwQc2VxIjoNLHxjdW0iOjYsInNpZF9yYXciOiJib2p3eWE6OXlpdzRvOg2/BH0sFWUkODEwNiwzLDEzMgGyAGOCcgEUODAzNTIsNnIBARQgMSwyLCJlbWFpIR0FRwAiOXvCcwEUMzIsMjE1jnMBCDgwMwV8CDE1MZrBABA0ODAzLDrBAAUUCDMsIiXVHbkRycLBABQ4NiwzNTOSwQAsNDgwMywxLDE1MV1d","user":"0","webSessionId":"bojwya:9yiw4o:3ltyal","send_method":"beacon","compression":"snappy_base64","snappy_ms":0},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[2]}}},1601856585147,0,50]],"user":"0","app_id":"256281040558","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[6]}}},1601856585147,0,46]],"user":"0","app_id":"256281040558","compression":""}]                                                   
-----------------------------266198348718227902573662103509--              
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.              
                                                                           
                                                                           
127.0.0.1 - - [04/Oct/2020 17:09:45] "POST /ajax/bz?__a=1&__beoa=0&__ccg=EXCELLENT&__comet_req=0&__csr=&__dyn=7xe6Fo4OQ1PyWwHBWo5O12wAxu13wqovzEdEc8uw9-3K4o1j8hwem0nCq1ewcG0KEswaq3a1nwt81sbzo5iaw5zwwwi831w9O0SU2swdq0Ho2ew4pw&__hsi=6879921555707970299-0&__pc=PHASED%3ADEFAULT&__req=6&__rev=1002768747&__s=bojwya%3A9yiw4o%3A3ltyal&__spin_b=trunk&__spin_r=1002768747&__spin_t=1601856564&__user=0&bz_orig=blue&dpr=1&jazoest=2937&lsd=AVpiQ0JFPuc HTTP/1.1" 302 -
[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: -----------------------------147432236915771045002819621751                                                            
Content-Disposition: form-data; name="ts"                                  
                                                                           
1601856585153                                                              
-----------------------------147432236915771045002819621751                
Content-Disposition: form-data; name="q"                                   
                                                                           
[{"app_id":"256281040558","posts":"8QSQW1siY2F0ZWdvcml6ZWRfb2RzIix7IjI5NzkiOnsiYmFuemFpIgEK4Gx1ZV90b3RhbF9tZXNzYWdlc19yZWNlaXZlZCI6WzUxXX19fSwxNjAxODU2NTg1MTUxLDAsNTddLOphABxzZW50IjpbNlpdAAAzAV1Ec2NyaXB0X3BhdGhfY2hhbmdlAcEUc291cmNlBRY4IjoiL2xvZ2luLnBocCIsERtUdG9rZW4iOiJhZDk3NjQyMCIsImRlcwlJFCI6bnVsbA0RDSkJEjRjYXVzZSI6InVubG9hZAFOcGlkX3JhdyI6ImJvand5YTo5eWl3NG86M2x0eWFsASEAbwWKGGVmX3BhZ2URWg0WdHVyaSI6Imh0dHBzOi8vd3d3LmZhY2Vib29rLmNvbR23BH0sPlsBCDIxMQH/THRpbWVfc3BlbnRfYml0X2FycmF5IQEgdG9zX2lkIjoiGYkQdGFydF8BMAQiOhFNDDc4LCIBKgk3HDpbMTI3LDBdCRQAbCEfDSAUc2VxIjoxCRggY3VtIjoxMywievsARrMAEDEzM11d","user":"0","webSessionId":"bojwya:9yiw4o:3ltyal","send_method":"beacon","compression":"snappy_base64","snappy_ms":1},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_received":[4]}}},1601856585151,0,50]],"user":"0","app_id":"256281040558","compression":""},{"webSessionId":"bojwya:9yiw4o:3ltyal","posts":[["categorized_ods",{"2979":{"banzai":{"blue_messages_sent":[6]}}},1601856585151,0,46]],"user":"0","app_id":"256281040558","compression":""}]                               
-----------------------------147432236915771045002819621751--              
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.              
                                                                           
                                                                           
127.0.0.1 - - [04/Oct/2020 17:09:45] "POST /ajax/bz?__a=1&__beoa=0&__ccg=EXCELLENT&__comet_req=0&__csr=&__dyn=7xe6Fo4OQ1PyWwHBWo5O12wAxu13wqovzEdEc8uw9-3K4o1j8hwem0nCq1ewcG0KEswaq3a1nwt81sbzo5iaw5zwwwi831w9O0SU2swdq0Ho2ew4pw&__hsi=6879921555707970299-0&__pc=PHASED%3ADEFAULT&__req=7&__rev=1002768747&__s=bojwya%3A9yiw4o%3A3ltyal&__spin_b=trunk&__spin_r=1002768747&__spin_t=1601856564&__user=0&bz_orig=blue&dpr=1&jazoest=2937&lsd=AVpiQ0JFPuc HTTP/1.1" 302 -

**Comment by bipin-adhk** [comment]
Was the problem resolved? Cause I couldn't do it. Help me out with the same problem.
