### ISSUE TITLE
Does not prints any password, only harvests the email id

### ISSUE THREAD

**Issue by sukumar1210** [trustedsec/social-engineer-toolkit#829]
**Expected Behaviour** both password and email to be harvested

Put here what the expected behaviour should be when reporting an issue

**Actual Behaviour**

I get only the entered email address

**Set Version**

Version: 8.0.3

Array

(

    [jazoest] => 21090

    [lsd] => AVpaxjlYyqI

    [display] => 

    [enable_profile_selector] => 

    [isprivate] => 

    [legacy_return] => 0

    [profile_selector_ids] => 

    [return_session] => 

    [skip_api_login] => 

    [signed_next] => 

    [trynum] => 1

    [timezone] => -330

    [lgndim] => eyJ3IjoxNDQwLCJoIjo5MDAsImF3IjoxNDQwLCJhaCI6ODY5LCJjIjoyNH0=

    [lgnrnd] => 223314_JWQ8

    [lgnjs] => 1605163061

    [email] => sukumar.rtg@gmail.com

    [prefill_contact_point] => sukumar.rtg@gmail.com

    [prefill_source] => browser_dropdown

    [prefill_type] => contact_point

    [first_prefill_source] => browser_dropdown

    [first_prefill_type] => contact_point

    [had_cp_prefilled] => true

    [had_password_prefilled] => false

    [ab_test_data] => AAAAf/AA//f/AAffAAAAAAAAAAAAAAAAAAAAAAAAAA/ZMAlMMAGAAD

    [encpass] => #PWD_BROWSER:5:1605163068:AZZQANfXnHgco6d0UK8HHvM3YRwHsa2MNuI1T8yHZcCU4KciLyFHPByawLDVLl2czd+tcx+g2Qn1mNALcjKXH2Lf0AoYJC832oCWk8U2EfXtWI7PBnuv1aYj6pPUmN6TVjVf7qk39FkIwGDJ

)
the above text is shown when someone logs in the cloned website. i can see the email id above but not the password entered. also the user is directed to actual login page instead of directly logging in.

I also tried turning apache on and off from the "set.config" file in the root/etc/setoolkit/ directory
 Please help

**Comment by ManWuzi** [comment]
It'll help to give the website you're testing but based on what you've given. It looks like the password is encrypted in Javascript before it is sent to the server.

If you want to bypass this, you're most likely going to have to make changes to code of the cloned website before sending it to your target.

**Comment by sukumar1210** [comment]
> It'll help to give the website you're testing but based on what you've given. It looks like the password is encrypted in Javascript before it is sent to the server.
> 
> If you want to bypass this, you're most likely going to have to make changes to code of the cloned website before sending it to your target.

Thanx man👍

Btw i'll have to learn that... any suggestion how to do it or where to learn whatever needs tl be learnt before being able to do that?

**Comment by ManWuzi** [comment]
You can take a simple web development class or watch some tutorials on Youtube. It'll be better to start with the basics before looking at frameworks.

From there you should be able to understand how the request is sent from the client to the server and know what to edit.

**Comment by benchacham** [comment]
How I change the code ?

**Comment by sukumar1210** [comment]
> How I change the code ?

I don't know man... look it up on youtube🙂
