### ISSUE TITLE
Can you devs please help me i can run the setoolkit because of errors

### ISSUE THREAD

**Issue by premjit1998** [trustedsec/social-engineer-toolkit#845]
**Expected Behaviour**

Put here what the expected behaviour should be when reporting an issue

**Actual Behaviour**

Put here what the actual behaviour should be when reporting an issue

**Set Version**

_Set version_

Before opening an issue please make sure you are running the most up to date version of set

We see the same bug reports being opened for issues that have already been fixed in a new release

**Set in Kali**

Please make sure you are running kali-rolling and your system is up to date.
To update your system do the following ``apt update && apt full-upgrade``

Run the following to check your version of Kali ``lsb_release -rdc`` and you should see the following
output
```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````
If you do not see the following output download the ISO from http://cdimage.kali.org/kali-images/kali-weekly/

If you do all of the above and still have an issue then please open a issue.

**Comment by premjit1998** [comment]
mkdir: cannot create directory ‘/usr/share/setoolkit/’: No such file or directory
mkdir: cannot create directory ‘/etc/setoolkit/’: Read-only file system
cp: target '/usr/share/setoolkit/' is not a directory
cp: cannot create regular file '/etc/setoolkit/set.config': No such file or directory
[*] Creating launcher for setoolkit...
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/setoolkit/setup.py", line 15, in <module>
    filewrite = open("/usr/local/bin/setoolkit", "w")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/setoolkit'

**Comment by annabbruton** [comment]
I am having a similar issue, how did you end up solving this?
