### ISSUE TITLE
the SMS module

### ISSUE THREAD

**Issue by ghost** [trustedsec/social-engineer-toolkit#89]
Hey there, I really like the social engineer kit and been using it for some time.
The SMS module removed was a big dissapointment for me... That was the most used thing in the toolkit and that's how many people found out this amazing toolkit.
Can you please continue the maintenance of the SMS toolkit?
Or, atleast tell me what to do to get the version 5.4.8, where the SMS toolkit lives. I run Kali Linux.
I would really appreciate if you can help my issue.

Thanks!

**Comment by nullsign** [comment]
Well, lets discuss this, what all do you need us to do to 'maintain' it?

I'm game.
