### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by Karthi02116K** [trustedsec/social-engineer-toolkit#951]
Using legacy 'setup.py install' for pycrypto, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pefile, since package 'wheel' is not installed.
Using legacy 'setup.py install' for impacket, since package 'wheel' is not installed.
Using legacy 'setup.py install' for qrcode, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pillow, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pycryptodomex, since package 'wheel' is not installed.
Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
Using legacy 'setup.py install' for MarkupSafe, since package 'wheel' is not installed.
Building wheels for collected packages: pymssql, cryptography
  Building wheel for pymssql (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pymssql (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py: platform.system() => Linux
      setup.py: platform.architecture() => ('64bit', '')
      setup.py: platform.libc_ver() => ('libc', '')
      setup.py: include_dirs => []
      setup.py: library_dirs => []
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-310
      creating build/lib.linux-aarch64-cpython-310/pymssql
      copying src/pymssql/__init__.py -> build/lib.linux-aarch64-cpython-310/pymssql
      running build_ext
      cythoning src/pymssql/_mssql.pyx to src/pymssql/_mssql.c
      cythoning src/pymssql/_pymssql.pyx to src/pymssql/_pymssql.c
      building 'pymssql._mssql' extension
      creating build/temp.linux-aarch64-cpython-310
      creating build/temp.linux-aarch64-cpython-310/src
      creating build/temp.linux-aarch64-cpython-310/src/pymssql
      aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.10 -c src/pymssql/_mssql.c -o build/temp.linux-aarch64-cpython-310/src/pymssql/_mssql.o -DMSDBLIB
      src/pymssql/_mssql.c:699:10: fatal error: 'sqlfront.h' file not found
      #include "sqlfront.h"
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymssql
^X^C  Building wheel for cryptography (pyproject.toml) ... canceled
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/setoolkit/setup.py", line 10, in <module>
    subprocess.Popen("pip3 install -r requirements.txt", shell=True).wait()
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1936, in _wait
    (pid, sts) = self._try_wait(0)
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1894, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
u0_a379@localhost ~/setoolkit (master) [SIGINT]>
![Uploading Screenshot_2022-06-02-13-42-01-67_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by Eliezer181** [comment]
tengo el mismo problema
